### PR TITLE
Update pt-BR parseFloat page

### LINKED ISSUE #4769: pt-BR parseFloat page needs some work
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

It is missing some macros like {{Compat}} and {{Specifications}}. To Update content itself would be great as well.

en-US version: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

### PR DESCRIPTION
**Pull request by ghost**
Feito com muito carinho, então faça a review, por favor. Fix: [#4769](https://github.com/mdn/translated-content/issues/4769)

### CODE REVIEW

**Comment by victor0x16** [comment]
Hi @cw118, do you know why EmbedInteractiveExample macro has ```Try it``` as a title?

I don't see that in my local machine. Over here looks fine but in the preview not so much.

**Comment by cw118** [comment]
@victor0x16 I believe the title is part of the macro itself, so there's no need to worry about that. I also see it on the [English page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) and [French page](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/parseFloat).

As for why it didn't show up locally, I'm not quite sure but I'll try to look into it in a bit :)

**Comment by cw118** [comment]
@victor0x16 alright, I think I figured out why. Turns out the "Try it" title for `embedinteractiveexample` macros was just recently added (cf. mdn/yari#5667) and the version of yari used by mdn/content (and translated-content) hasn't been updated to have that "feature" yet, which is why we don't see it locally but it's there on deployment and preview.

**Comment by victor0x16** [comment]
@cw118 ,  thank you for looking it up!

I do believe that this title on the macro seems unnecessary and it doesn't fit in the pages specially to translated ones. But maybe there is something I'm missing here.

**Comment by cw118** [comment]
> I do believe that this title on the macro seems unnecessary and it doesn't fit in the pages specially to translated ones. But maybe there is something I'm missing here.

There is valid motivation for adding the title, notably improving navigation for readers (cf. [this discussion on yari](https://github.com/mdn/yari/discussions/5453)); yes, we're also concerned about the effect of this addition on locales and are discussing ways to potentially localize it :)

**Comment by SphinxKnight** [comment]
@mdn/yari-content-pt-br is there something blocking this from being reviewed?

**Review by josielrocha — APPROVED** [review]
LGTM ;)

**Comment by josielrocha** [comment]
Obrigado pela contribuição @victor0x16!

**Pull request merged**
