### PR TITLE
chore: remove deprecated XULAttr macro

### LINKED ISSUE #8840: chore: remove deprecated XULAttr macro
The `XULAttr` macro has been deprecated and should be removed. Here are the places it is still in use.

| macro | yari | en-us | es | fr | ja | ko | pt-br | ru | zh-cn | zh-tw |
|:----- | ----:| -----:| --:| --:| --:| --:| -----:| --:| -----:| -----:|
| XULAttr 🗑 |  |  | <span title="/web/css/-moz-user-input/index.md …">1</span> | <span title="/mozilla/firefox/releases/12/index.md …">4</span> | <span title="/mozilla/firefox/releases/12/index.md …">3</span> |  |  |  |  |  |

### PR DESCRIPTION
**Pull request by schalkneethling**
The XULAttr macro has been deprecated and should be removed.

fix #8840

### CODE REVIEW

**Review by SphinxKnight — APPROVED** [review]
OK for @mdn/yari-content-fr 
🤞 for conflicts w/ #8822

**Comment by schalkneethling** [comment]
> OK for @mdn/yari-content-fr 🤞 for conflicts w/ #8822

Haha! Yes, I know, I was thinking about that :) I will handle it if it comes to pass :+1:

**Comment by potappo** [comment]
LGTM for `ja` files

**Review by potappo — APPROVED** [review]

**Review by Graywolf9 — APPROVED** [review]
Looks good to `es` 

doubt: the link isn't necesary anymore?

**Review by yin1999 — COMMENTED** [review]
Approved by all three locales, let's merge this :)

**Comment by yin1999** [comment]
> Looks good to `es`
> 
> doubt: the link isn't necesary anymore?

The links to those items (some old documents) seems to be broken. I thinks it's ok to remove them.

**Pull request merged**
