### PR TITLE
fix unicode space --> ascii space

### PR DESCRIPTION
**Pull request by fwqaaq**

### CODE REVIEW

**Comment by Jack-Zhang-1314** [comment]
Sorry, I have closed the previous  branches.

**Comment by Jack-Zhang-1314** [comment]
`zh-cn/web/api`

**Comment by yin1999** [comment]
please fetch upstream in main branch, and then checkout this branch, using command `git rebase -i main` to resolve conflict (just delete conflicting html file)

**Comment by yin1999** [comment]
> please fetch upstream in main branch, and then checkout this branch, using command `git rebase -i main` to resolve conflict (just delete conflicting html file)

If you are not familiar with this, I can help you

**Comment by Jack-Zhang-1314** [comment]
> please fetch upstream in main branch, and then checkout this branch, using command git rebase -i main to resolve conflict (just delete conflicting html file)

I see. 
1. First, update upstream
2. Second, use command `git rebase main` in this branch
3. third, delete conflict files, this step that I need your help

**Comment by yin1999** [comment]
are you using vs code?

**Comment by Jack-Zhang-1314** [comment]
> are you using vs code?

yeah, but i can't use GUI

**Comment by yin1999** [comment]
If so, you can see conflict file in git extension, just delete those file there. and then run `git rebase --continue`

**Comment by Jack-Zhang-1314** [comment]
I will give it a try

**Comment by Jack-Zhang-1314** [comment]
I don't know wether I should git commit

**Review by yin1999 — APPROVED** [review]

**Comment by yin1999** [comment]
checked locally

**Comment by Jack-Zhang-1314** [comment]
* Excuse me, why do I mention so many participants in this #7008 ?
* I think that I don't solve content conflict.
* I hope you can explain this reason.

**Comment by Jack-Zhang-1314** [comment]
When I merge conflicts, other's commits are included, is it normal?

**Comment by yin1999** [comment]
> * Excuse me, why do I mention so many participants in this [fix zh-CN:zh-cn/web/api unicode space --> ascii space #7008](https://github.com/mdn/translated-content/pull/7008) ?

The previous commit has been changed

image

It's better to using [`git rebase`](https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%8F%98%E5%9F%BA) to make changes be at the head of `upstream main`.

**Comment by yin1999** [comment]
> When I merge conflicts, other's commits are included, is it normal?

Please see document: https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%88%86%E6%94%AF%E7%9A%84%E6%96%B0%E5%BB%BA%E4%B8%8E%E5%90%88%E5%B9%B6

**Comment by Jack-Zhang-1314** [comment]
So, I see, beacuse I didn't solve this conflict. If perfect solving this conflict would not so much part  participants.
* like this

* right ?

**Comment by yin1999** [comment]
> So, I see, beacuse I didn't solve this conflict. If perfect solving this conflict would not so much participants.
> 
> * like this
>   
> * right ?

No, you've resolved. But you are using `git merge`, so the commit in main branch will be modified. Github will consider those commits as changes in Pull Request.

**Comment by Jack-Zhang-1314** [comment]
I see，but this pr I also used 'git merge'.And, I need to use 'git add .' ,before I used 'git rebase --continue'.Then， I would enter vim mode to fix some modified.But i don't fix this modified, so it became merge instead of rebase？

**Comment by Jack-Zhang-1314** [comment]
And I use git rebase to fetch upstream. But I don't know why it became 'merge'.or like I said above

**Comment by Jack-Zhang-1314** [comment]
sorry，my mean i don't konw why it bacame merge.Beacuse I looked gui for this branch，it was like using mergeimage

**Comment by Jack-Zhang-1314** [comment]
I see. I don't add parameter 'I'.

**Pull request merged**
