### PR TITLE
fix some more zh-cn macros

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@mfuji09 please could you have a look at this PR and let us know if everything is OK with it, or if some things are broken? Many thanks!

**Comment by mfuji09** [comment]
> @mfuji09 please could you have a look at this PR and let us know if everything is OK with it, or if some things are broken? Many thanks!

@chrisdavidmills I don't understand Chinese, but I think this PR is appropriate for removing errors in macro usage.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I don't understand Chinese, but I think this PR is appropriate for removing errors in macro usage.

I'm so sorry. I got the language wrong.

In which case, @irvin can you please have a look at these changes and let us know if everything is OK with it, or if some things are broken? Many thanks!

**Review by chrisdavidmills — APPROVED** [review]
This all looks OK to me, @fiji-flo ; let's get it merged.

**Pull request merged**
