### PR TITLE
fix(RU): in `Client-side_JavaScript_frameworks` article

### PR DESCRIPTION
**Pull request by scffs**

### CODE REVIEW

**Review by myshov — APPROVED** [review]
thanks!

**Comment by myshov** [comment]
Sorry, as I see the pr is in a draft state

**Comment by scffs** [comment]
> Sorry, as I see the pr is in a draft state

Don't worry, as soon as I can, I'll translate it all

**Comment by myshov** [comment]
@scffs hi! Do you plan to translate other parts of the page? Can I start to review what already here? :)

**Comment by scffs** [comment]
> 
@myshov , да, через неделю постараюсь доделать, пока нет времени:(

**Comment by queengooborg** [comment]
To help out a little, I've just fixed merge conflicts for this PR, so that it'll be a little easier to update and review!

**Pull request closed without merging**
