### PR TITLE
Typofix (missing "pas")

### PR DESCRIPTION
**Pull request by PAHE69**
"il ne remplace pas les vérifications"... au lieu de "il ne remplace les vérifications"...

### CODE REVIEW

**Comment by PAHE69** [comment]
ok. merged.

**Comment by cw118** [comment]
Hi @PAHE69, the change proposed here is valid. Was there any reason for closing this? 

Don't hesitate if help or discussion is needed :)

**Comment by PatriceHenryZeendoc** [comment]
Hi @cw118 , sorry wasn't so familiar with this. Is there a way to let it opened ? Regards !

**Comment by SphinxKnight** [comment]
@PatriceHenryZeendoc it seems like you have two accounts, I guess the first one (@PAHE69 ) gives you access to the "Reopen" button. Anyway, you'll need the first account if you want to push new commits to this branch :) 

That being written, let's reopen this one now.

**Review by SphinxKnight — APPROVED** [review]
Merci @PAHE69 :)

**Pull request merged**
