### PR TITLE
remove `Tools` section from `es`

### PR DESCRIPTION
**Pull request by yin1999**
Part of #4822

Removed by running go script [here](https://github.com/mdn/translated-content/issues/4822#issuecomment-1079841949)

### CODE REVIEW

**Comment by JuanVqz** [comment]
@yin1999 thank you for opening this PR, I'm not pretty sure what this PR does, but it seems like it didn't break any test, so, I'll approve it. :+1:

**Comment by yin1999** [comment]
Hi @JuanVqz All files under `tools` folder have been removed by this pr. And there is no folder left.

And those links in `Tools` section are redirected to `Firefox Developer Tools docs` (see commits in `files/es/_redirects.txt`). Reference: mdn/content#14140

image

**Comment by Graywolf9** [comment]
Thank you so much @yin1999! There's a reason to have that difference?

Captura de Pantalla 2022-03-31 a la(s) 11 49 58

**Comment by yin1999** [comment]
You mean we shoud apply all the redirects about `/en-US/docs/Tools/*` in [mdn/content](https://github.com/mdn/content) to the `l10n` repo?

This may help with some documents which do not  exist but are referenced in `l10n`. So I have made a test about it:

I have added a link to `/es/docs/Tools:Validators` which does not exist in `es` (not defined in `files/es/_redirects.txt` neither), and [mdn/yari](https://github.com/mdn/yari) could resolve this link correctly (to <https://firefox-source-docs.mozilla.org/devtools-user/validators/index.html> which is defined in `files/en-us/_redirects.txt`)

image

So I think we may only need to resolve those documents which is in `l10n`. Any ideas @SphinxKnight ?

**Comment by cw118** [comment]
@yin1999 @Graywolf9 adding redirects for existing l10n pages should be good, I don't see the need to add more especially since yari handles the rest thanks to `en-us` redirects :)

**Comment by Graywolf9** [comment]
@yin1999 @cw118 I see it, thank you much for your time and contribution!

**Pull request merged**
