### PR TITLE
correcting some phrases

### PR DESCRIPTION
**Pull request by jotagarciaz**
I make a few changes for make the page more correctly translated.

I don't find which minify was used previously, for reducing the size of the document, that's why appears to be great different since I didn't minified the index.html document.

But I hope it could be useful in some way to make the page more comprehensive

### CODE REVIEW

**Comment by JuanVqz** [comment]
Hi @jotagarciaz, could you sync the content with [English version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), please?
(including changing to `Markdown` format)

**Comment by jotagarciaz** [comment]
> Hi @jotagarciaz, could you sync the content with [English version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), please?
> (including changing to `Markdown` format)

Of course I will be glad doing it, just give me a few days, since there are a lot of changes.

**Comment by JuanVqz** [comment]
> > Hi @jotagarciaz, could you sync the content with [English version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), please?
> > (including changing to `Markdown` format)
> 
> Of course I will be glad doing it, just give me a few days, since there are a lot of changes.

for sure! take your time, let us know if you need some help, thank you!

**Comment by Graywolf9** [comment]
> > Hi @jotagarciaz, could you sync the content with [English version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), please?
> > (including changing to `Markdown` format)
> 
> Of course I will be glad doing it, just give me a few days, since there are a lot of changes.

Hi! @jotagarciaz , I hope you're great, I want to know how's going the changes, [let us know if you need some help](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org), thank you!

**Comment by jotagarciaz** [comment]
> > > Hi @jotagarciaz, could you sync the content with [English version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), please?
> > > (including changing to `Markdown` format)
> > 
> > 
> > Of course I will be glad doing it, just give me a few days, since there are a lot of changes.
> 
> Hi! @jotagarciaz , I hope you're great, I want to know how's going the changes, [let us know if you need some help](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org), thank you!

Hi @Graywolf9 ! I am sorry but I couldn't manage the time to do it, although I have the first part of it complete, should I pull it here for someone to continue over that point?

**Comment by jotagarciaz** [comment]
@JuanVqz @Graywolf9 thank you for giving me enough time for doing it. I just finished it now.

**Review by Vallejoanderson — COMMENTED** [review]
Hola @jotagarciaz. Muchas gracias por tu valiosisimo aporte, a continuacion algunas observaciones que puedes commitear desde aqui mismo en la pagina. Adicional a eso, dale una mirada a `Files changed` ya que aun esta en escena el archivo `.html` y solo uno puede pasar a la rama principal ya que ambos no deben coexistir en el mismo directorio. Tendrias que borrarlo en tu carpeta y luego borrar con `git rm` el cual es el contrario de `git add`, por ejemplo:

`files rm files/es/web/http/headers/cache-control/index.html`

Cualquier duda, escribenos y te ayudamos :)

**Comment by jotagarciaz** [comment]
> Hola @jotagarciaz. Muchas gracias por tu valiosisimo aporte, a continuacion algunas observaciones que puedes commitear desde aqui mismo en la pagina. Adicional a eso, dale una mirada a `Files changed` ya que aun esta en escena el archivo `.html` y solo uno puede pasar a la rama principal ya que ambos no deben coexistir en el mismo directorio. Tendrias que borrarlo en tu carpeta y luego borrar con `git rm` el cual es el contrario de `git add`, por ejemplo:
> 
> `files rm files/es/web/http/headers/cache-control/index.html`
> 
> Cualquier duda, escribenos y te ayudamos :)

Gracias por los tips y por la revisión, me lo apunto para la próxima.

**Review by Vallejoanderson — APPROVED** [review]

**Pull request merged**
