### PR TITLE
fix a bug of legacy http:// URL references

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
Sorry all reviewers pinged. Anybody can review this. And if you can merge, please go ahead and squash and merge.

**Review by hochan222 — COMMENTED** [review]
LGTM :)

**Comment by irvin** [comment]
i had rebase merge instead of squash, due to one thing per commit principle.

**Comment by peterbe** [comment]
> i had rebase merge instead of squash, due to one object per commit principle.

I don't understand. If you use "Squash and merge" that's actually a form of rebase too. But it makes it so there's only 1 commit. 
If you use "Rebase and merge" it just pretends that all commits started from the tip of `main` but all commits are kept. 

We use "Squash and merge" on mdn/content and mdn/yari.

**Comment by irvin** [comment]
one commit is “fix http:// URL” and another commit is “remove wiki. prefixes”, i think it would be better to keep them separate because it’s actually two separate issues?

**Comment by peterbe** [comment]
> one commit is “fix http:// URL” and another commit is “remove wiki. prefixes”, i think it would be better to keep them separate and not merging into one commit because it’s actually two separate issues?

Fair! It was "sloppy" to fix two separate things in one PR. 

Great work! ...as always. Please keep it up!

**Pull request merged**
