### PR TITLE
Popover api

### PR DESCRIPTION
**Pull request by JeremiePat**
### Description

Translate the whole Popover API into french.

### Motivation

It was not done yet and this API is about to become main stream.

### Additional details

Quite a few change that worth noting : Beyond adding the new API landing page, the API `HTMLElement`, `HTMLButtonElement` and `HTMLInputElement` has been updated for completeness. Same for the HTML `<button>` and `<input>` element to be sure they have the related attributes documented as well.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Thanks @JeremiePat :)  🐻 
I'll check that as soon as possible. In the meantime, could you please add a frontmatter key with the "last english commit which this content translates"

```
l10n:
  sourceCommit: fullHash
```

**Comment by SphinxKnight** [comment]
@JeremiePat tu préfères une revue avec suggestion ou je peux pousser des commits ?

**Comment by SphinxKnight** [comment]
@JeremiePat j'ai mis mes modifications en attente sur https://github.com/JeremiePat/mdn-fr/pull/2 j'attends quelques jours au chaud pour ton retour. Par défaut, je fusionne un peu avant Noël :)

**Comment by SphinxKnight** [comment]
allez c'est parti :santa:

**Comment by JeremiePat** [comment]
@SphinxKnight Désolé pour le silence radio... les vacances de noël. Merci pour le merge 😁 A la prochaine

**Pull request merged**
