### PR TITLE
Remove obsolete `HTMLBaseFontElement` interface

### PR DESCRIPTION
**Pull request by leon-win**
### Description

This PR remove obsolete `HTMLBaseFontElement` interface from MDN translated content.

### Motivation

It has been removed from en-US locale a long time ago.

### Related issues and pull requests

Relates to #13499, https://github.com/mdn/content/pull/18320

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for zh-TW. Thank you @leon-win

**Review by saionaro — APPROVED** [review]
LGTM for RU

**Review by tristantheb — APPROVED** [review]
Ok for `fr`

**Review by josielrocha — APPROVED** [review]
Approve for `pt-BR`

**Pull request merged**
