### PR TITLE
Prepare CSS section for Markdown conversion

### PR DESCRIPTION
**Pull request by SphinxKnight**
- [x] Remove `summary` and `seoSummary` classes
- [x] Deal with `hidden` code blocks in live samples
- [x] Remove hidden div/paragraphs for interactive examples
- [x] Remove `hidden` elements that don't contain code blocks in a live sample
- [x] Remove `id`  attributes except on headings
- [x] Remove `notranslate` class
- [x] Convert/fix note/warning cards
- [x] Fix broken `dd` elements
- [x] Deal with `sup` and `sub`
- [x] Remove nested partial `strong` in `code`
- [x] Deal with `<div class="index">`
- [x] Fix live samples that use IDs which are not derived from heading text
- [x] Remove random CSS classes and unsupported elements
- [x] Remove links with deki
(list shamelessly plagiarized from https://github.com/mdn/content/issues/5865 )

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Note for review: I intentionally left some `<sup>`s and `<sub>`s for French typography consistency

**Comment by SphinxKnight** [comment]
@tristantheb I'm sorry to inflict this on you :x 
I guess checking the conversion report on your side after running  `yarn run md h2m web/css --locale fr --mode dry` and checking a sample of pages should be enough?

**Comment by wbamberg** [comment]
> N.B. I don't know why there is a dl which is not handled for CSS Counter Styles :/

There's a bug in the converter where it will fail to convert `<dd>` elements that have some content (like a list, or a code block) which is not preceded by some text. See https://github.com/mdn/yari/issues/4307 .

In practice, every instance of this that I have seen would be improved by adding some text explaining what the nested list is, or by reworking the markup entirely.

In this case I replaced the whole `<dl>` with a nested list, which was more consistent with other CSS module pages and seemed to have better semantics (the list of at-rule descriptors do not define the at-rule): https://raw.githubusercontent.com/mdn/content/main/files/en-us/web/css/css_counter_styles/index.md .

**Comment by SphinxKnight** [comment]
Thanks @wbamberg :) I was looking at the wrong commit on the English side. (fwiw, it's really helpful to look at the state of things at the last commit (before conversion) on the mdn/content repo (to apply similar fixes on French), maybe a git tag would be helpful, I'm not 100% sure)

Here is the conversion report after all this: https://gist.github.com/SphinxKnight/87da8b54884a035e27a2556bd91a33e4

A few notes:
* `<sup>`/ `<sub>` are left for typography (the ones in mathematical expressions where a `^` was acceptable were removed)
* `<i lang="en">` is left as well, again for typography in French.

**Review by tristantheb — APPROVED** [review]

**Pull request merged**
