### PR TITLE
修复代码注释中的错误

### LINKED ISSUE #2047: It should be a translation error
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting

#### What information was incorrect, unhelpful, or incomplete?

The text reads as follows:
const firstString = '2 + 2'; //创建一个字符串字面量
const secondString = new String('2 + 2'); // 创建一个字符串对象
eval(firstString); // 返回数字 4
eval(secondString); // 返回字符串 "2 + 2"

The comment on the last line should be changed：//返回对象 [String: '2 + 2']

#### Specific section or headline?
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting#%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1

Web 开发技术->JavaScript->JavaScript 指南->Text formatting

#### What did you expect to see?
The comment on the last line should be changed：//返回对象 [String: '2 + 2']

#### Did you test this? If so, how?
Yes,This is the result of the code running on Node:

> const firstString = '2 + 2'; //创建一个字符串字面量
undefined
> const secondString = new String('2 + 2'); // 创建一个字符串对象
undefined
> eval(firstString); // 返回数字 4
4
> eval(secondString); // 返回字符串 "2 + 2"
[String: '2 + 2']

image-20210813152538116

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/guide/text_formatting`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/text_formatting/index.html
* Last commit: https://github.com/mdn/translated-content/commit/88a0fb5f5447955f55b4e7679c788f92aa320af3
* Document last modified: 2021-08-12T14:29:03.000Z

</details>

### PR DESCRIPTION
**Pull request by zhoushengdao**
Fixes #2047
转换为 Markdown 格式。

谢谢

### CODE REVIEW

**Review by KevinZonda — CHANGES_REQUESTED** [review]
Most document im this repo is done by html not markdown

**Review by t7yang — CHANGES_REQUESTED** [review]
Markdown not yet ready.

**Comment by irvin** [comment]
It's better to do one thing per commit / PR, which can help people learn your contribution much faster. And as @t7yang said, there are still issues with markdown on locales besides English, so we will stay at HTML for some more time.

**Comment by zhoushengdao** [comment]
@KevinZonda @t7yang @irvin OK, I will fix it.Thank you!

**Comment by zhoushengdao** [comment]
Now, I update PR, it only does one thing. I'm sorry to take up your time. Can you review it again now? Thanks! 
By the way, do you have any other suggestions for making contributions here?

**Review by t7yang — APPROVED** [review]

**Comment by t7yang** [comment]
> Now, I update PR, it only does one thing. I'm sorry to take up your time. Can you review it again now? Thanks!
> By the way, do you have any other suggestions for making contributions here?

A translation guide for zh-TW can find [here](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md). Although the content is mainly for zh-TW translator, I believe you still can find many useful information for what should or shouldn't do when contributing translation to zh content.

You can also find [here](https://developer.mozilla.org/en-US/docs/MDN/Contribute) for the whole content of how to contributing to MDN, especially [Writing style guide](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide), the [zh-TW](https://developer.mozilla.org/zh-TW/docs/MDN/Guidelines/Writing_style_guide) version which updated by me provide many useful tips for zh translator when translating en-US content to zh.

**Pull request merged**
