### PR TITLE
Update French translation of the `@media` reference

### PR DESCRIPTION
**Pull request by audrasjb**
This PR fixes a broken link on French translation of the `@media` reference.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Hmm, I think the French page should stick to the way the English page is presenting information here. The {{page}} macro is a good tool as well as an old macro.
If that's OK, I'll fiddle a commit to fix this macro call and (hopefully) get the same result as in English rather than transforming the table into a link.

That being written: good spot :) and thanks for providing a fix.

**Comment by audrasjb** [comment]
OK good point! Since I spotted the issue directly while using MDN as an end-user, I opened this PR directly from GitHub interface and not using my IDE so feel free to handle that the way you'd like :D

**Comment by SphinxKnight** [comment]
Well, I think I'll actually update the whole page 😶

**Comment by audrasjb** [comment]
:D feel free to close that PR then

**Comment by SphinxKnight** [comment]
@audrasjb I'm shamelessly using this PR : ]
Let me know if this looks OK for you :)

**Comment by audrasjb** [comment]
yeah sure, do as you wish!

**Review by tristantheb — APPROVED** [review]

**Pull request merged**
