### PR TITLE
fix various fixable flaws in Learn tree (ru)

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by sashasushko** [comment]
Hi @peterbe Sorry I'm in vacation now. So if someone from @mdn/yari-content-ru can review, it will be beautiful

**Review by mpstv — APPROVED** [review]
I made some edits. And I think I can merge this.

**Comment by mpstv** [comment]
@peterbe PR contains not used file: `files/ru/learn/forms/form_validation/error-chrome-win7.png`. And I can't remove it.

**Comment by peterbe** [comment]
@mpstv Merge now?

**Pull request merged**
