### PR TITLE
ko: Remove trailing punctuation in headers

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the trailing punctuation in headers for the Korean locale.

### CODE REVIEW

**Comment by queengooborg** [comment]
Pinging @mdn/yari-content-ko for review!

**Review by hochan222 — APPROVED** [review]
@queengooborg I don't know why, but you mentioned the yari-content-ko team, but **I didn't get a notification for every recent PRs.** Hmm.. is it a problem with the system? I'll merge in a few days in case you missed the comment. Git Actions PR test failed, but the content is all good!

@mdn/yari-content-ko [국립 국어원에 아래와 같은 규칙](https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=225670&pageIndex=1)이 존재하는군요..! 또 [MD026 - Trailing punctuation in header](https://github.com/updownpress/markdown-lint/blob/master/rules/026-no-trailing-punctuation.md)의 markdown-lint 규칙도 존재합니다.

> 문장 형식으로 된 제목이나 표어 등에는 마침표를 쓰지 않는 것이 원칙

앞으로 제목에는 Trailing punctuation을 추가하지 않도록 안내서에 추가하겠습니다. 참고 부탁드려요~!

**Comment by queengooborg** [comment]
That's really bizarre...  I'll relay this info to the rest of the Mozilla team!

**Comment by hochan222** [comment]
@queengooborg , Oh, I thought you belonged to the MDN team, but you didn't. From my experience so far, I know that if you don't belong to the MDN team, you won't get a notification even if you ping the team. If you don't belong to a team, you have to mention the ID directly..! Korean contributors are also mentioning my ID because of this.

It would be nice to talk to the Mozilla team for detailed policies.

**Comment by queengooborg** [comment]
Actually, I am a part of the MDN team!  I'm an independent contractor working for both Mozilla and Open Web Docs to maintain MDN, I simply don't have the same org-wide privileges as Ruth, Brian, etc.  Thanks for the head's up there, I'll reach out to them and get that resolved!

**Pull request merged**
