### PR TITLE
JavaScript object basics: fix Next page button link

### LINKED ISSUE #7716: Issue with "JavaScript object basics": (Next page button pointing to a wrong page)
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Basics

#### What information was incorrect, unhelpful, or incomplete?

The next page button at the end of the page points to "https://.../docs/Learn/JavaScript/Objects/Classes_in_JavaScript", but according to the left sidebar it should point to "https://.../docs/Learn/JavaScript/Objects/Object_prototypes"

*Note: this happens on every language version of the page except for English.

#### Specific section or headline?

The next page button.

#### What did you expect to see?

The button should point to "https://.../docs/Learn/JavaScript/Objects/Object_prototypes" on every language version of the page.

#### Did you test this? If so, how?

I've checked all language versions and only English version is correct.

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/39bb7ce86d6da4db189643d9c5961dcf38f69599
* Document last modified: 2022-08-07T14:01:32.000Z

</details>

### PR DESCRIPTION
**Pull request by miguelfernandezdev**
Fixes #7716 

Changes proposed in this pull request:

- Fixed JavaScript object basics Next page button for all languages

### CODE REVIEW

**Review by cw118 — APPROVED** [review]
`fr` looks good (and fwiw `de` seems correct as well), thank you @miguelfdezc :)

**Review by Graywolf9 — APPROVED** [review]
everything ok with `es`, thank you so much.

**Review by yin1999 — APPROVED** [review]
LGTM for zh-CN and zh-TW

**Review by josielrocha — APPROVED** [review]
LGTM `i10n-pt-br`

**Review by yujo11 — APPROVED** [review]
`ko` LGTM!

**Comment by mfuji09** [comment]
Parallelly the file in the `ja` locale has been converted into markdown.
So, I have re-applied the change into the new version.

`ja` locale is okay now.

**Review by mfuji09 — APPROVED** [review]

**Comment by yin1999** [comment]
Is there anyone can review this @mdn/yari-content-ru

**Comment by sashasushko** [comment]
@yin1999 all is ok. Thanks and sorry for late response

**Pull request merged**
