### PR TITLE
chore(l10n): update discussion channel in l10n-zh

### LINKED ISSUE #19534: [zh-CN] Mainland's community has been disbanled.
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content#chinese_zh-cn_zh-tw

### 与此议题相关的小节或标题？

_No response_

### 哪些信息是错误、无用或不完善的？

@yin1999 群主被请🍵了

### 你期望看到什么？

我们是否需要一个新的（Telegram、discord 等更自由的平台），而不是使用 WeChat。

### 你有什么支持的链接、参考或引用？

_No response_

### 你还想补充什么内容？

_No response_

### MDN metadata

_No response_

### PR DESCRIPTION
**Pull request by jasonren0403**
### Description

Reflect mdn/content#33118 changes in l10n documents

### Related issues and pull requests

upstream: mdn/content#33118

#19534

### CODE REVIEW

**Review by leon-win — APPROVED** [review]

**Comment by leon-win** [comment]
Ok for `ru` :+1:

**Review by SphinxKnight — APPROVED** [review]
OK for `fr`, thanks @jasonren0403 
I've just noticed the PR is a draft: is it intentional?

**Comment by jasonren0403** [comment]
> OK for `fr`, thanks @jasonren0403 I've just noticed the PR is a draft: is it intentional?

It was waiting for upstream changes to be merged(and now it has merged now)

**Review by JuanVqz — APPROVED** [review]
Looks good for ES team :shipit:

**Review by mfuji09 — APPROVED** [review]
It looks good for `ja`!

**Pull request merged**
