### PR TITLE
Fixes #4

### LINKED ISSUE #4: Typo
The following section contains typo errors:

使用 JavaScript 开发交互
学习用时: 135–185 小时

预备知识
学习 CSS 前需要有基础的 HTML 知识，请至少学习完 HTML 介绍 再开始。

Original Reference: [MDN web learning page](https://developer.mozilla.org/zh-CN/docs/learn/Front-end_web_developer#%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF%E5%9B%BE) 

Content to be corrected: replace CSS to JavaScript.

使用 JavaScript 开发交互
学习用时: 135–185 小时

预备知识
学习 JavaScript 前需要有基础的 HTML 知识，请至少学习完 HTML 介绍 再开始。

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Replaced CSS by JavaScript Fixes #4

### CODE REVIEW

**Comment by irvin** [comment]
改錯地方

**Review by irvin — CHANGES_REQUESTED** [review]
改錯地方，請參照原文與 issue 指出的行數：
https://github.com/mdn/content/blob/main/files/en-us/learn/front-end_web_developer/index.html#L97
fix wrong lines.

**Comment by CreaTorAlexander** [comment]
@irvin have I made the changes at the wrong place?

**Comment by irvin** [comment]
yap

**Pull request closed without merging**
