### PR TITLE
continue updating translation

### PR DESCRIPTION
**Pull request by AlwaysReVaule**
After PR: https://github.com/mdn/translated-ontent/pull/5756#issue-1243876007

### CODE REVIEW

**Comment by irvin** [comment]
please merge into #5756

**Comment by AlwaysReVaule** [comment]
> please merge into #5756

@irvin could you give me some tips about how to merge different PR together? or you mean merge different branch? to be honest, this confused me several day. I don't think if we merge those PR separately will cause any conflict, since they all work on different part of this page.  Happy to get your feedback, thanks~

**Comment by irvin** [comment]
> > please merge into #5756
> 
> @irvin could you give me some tips about how to merge different PR together? or you mean merge different branch? to be honest, this confused me several day. I don't think if we merge those PR separately will cause any conflict, since they all work on different part of this page. Happy to get your feedback, thanks~

it's probably won't cause conflict on the git part, but it can cause trouble for multiple reviewers to review the same docs in a short time. You should just translate them within one PR. It's ok to open PR and still edit it. 

How do you translate docs and send PR? with the Github interface, git command-line tool, or other git clients?

**Comment by AlwaysReVaule** [comment]
> 
@irvin right now, I just use Github interface for this translation task. I will take your suggestion and next time I will try to submit one PR for whole page translation. But, for this case, its better you just merge my each PR into main Branch, just my opinion.

**Comment by irvin** [comment]
> @irvin right now, I just use Github interface for this translation task. I will take your suggestion and next time I will try to submit one PR for whole page translation. But, for this case, its better you just merge my each PR into main Branch, just my opinion.


ok, 

next time you can click the edit at any file of an opened pr to add more edit to it.

截圖 2022-05-24 下午10 08 53

**Pull request merged**
