### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ViktorOn**
Changes:
- some fixes of the Russian translation

### CODE REVIEW

**Comment by sashasushko** [comment]
@ViktorOn thank you for your help. I remember about your PR. And I'll review it ASAP. Peace 🕊

**Comment by nschonni** [comment]
Because of the Markdown conversion, this probably needs to be redone on https://github.com/mdn/translated-content/blob/main/files/ru/learn/index.md. Not sure a rebase will work

**Comment by ViktorOn** [comment]
> Because of the Markdown conversion, this probably needs to be redone on https://github.com/mdn/translated-content/blob/main/files/ru/learn/index.md. Not sure a rebase will work

Probably in this case I'll just close my PR

**Comment by sashasushko** [comment]
> Probably in this case I'll just close my PR

@ViktorOn Leave it to me, please

**Comment by queengooborg** [comment]
Since this PR has been sitting around for a while, I've gone ahead and made the appropriate changes to effectively rebase this onto the Markdown version.  In the process, I also made some changes to the structure of a certain section.  This should now be ready to review!

**Review by sashasushko — APPROVED** [review]

**Comment by sashasushko** [comment]
@ViktorOn спасибо. Прошу прощения, что так долго.

**Pull request merged**
