### PR TITLE
fix array fill typo

### LINKED ISSUE #3250: Issue with "Array.prototype.fill()": (One Chinese character might be wrong)
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

#### What information was incorrect, unhelpful, or incomplete?
代码区域倒数第三行：
// 需要注意如果fill的参数为引用类型，会导致都执行`都`一个引用类型

#### Specific section or headline?
示例

#### What did you expect to see?
// 需要注意如果fill的参数为引用类型，会导致都执行`同`一个引用类型

#### Did you test this? If so, how?
Yes, 根据上下文，我认为将`都一个`...改为`同一个`...更合理。

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array/fill`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/fill/index.html
* Last commit: https://github.com/mdn/translated-content/commit/10bd926d9da3c32a9cb4442d5e8a8157fc6d1d75
* Document last modified: 2021-12-02T00:11:03.000Z

</details>

### PR DESCRIPTION
**Pull request by btea**
fix #3250

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@btea could you please update your branch to have/merge https://github.com/mdn/translated-content/pull/3350 5045d50 in it? There was a mistake in a PR (totally unrelated to your changes :( ) which prevents the continuous integration to succeed.

**Comment by btea** [comment]
@SphinxKnight If you can help me merge it, I will be very grateful

**Comment by SphinxKnight** [comment]
@btea done, I've applied `git merge upstream/main` (after having done `git fetch upstream` locally)

I've pushed this to your branch so if you want to do some other work here, don't forget to pull/fetch locally :)

**Comment by btea** [comment]
@SphinxKnight I see,  thank you very much :)

**Review by t7yang — APPROVED** [review]

**Pull request merged**
