### PR TITLE
remove index.html files in folders where an index.md file already exists

### PR DESCRIPTION
**Pull request by LeoMcA**
done automatically with `find . -name 'index.*' -type f -printf '%h\n' | sort | uniq -d | while read -r line; do git rm "${line}/index.html"; done`

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for l10n-zh.

**Review by cw118 — APPROVED** [review]
Looks good for `l10n-fr`, thank you @LeoMcA !

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja` files

**Comment by LeoMcA** [comment]
Thanks for the reviews, merging now so https://github.com/mdn/translated-content/pull/6580 can move forward.

@Saionaro feel free to open another PR restoring `files/ru/learn/forms/your_first_form/index.html` if it shouldn't have been deleted.

**Pull request merged**
