### PR TITLE
docs: add Russian translation for ru/glossary/ipv4/index.md and ru/glossary/ipv6/index.md

### PR DESCRIPTION
**Pull request by impocode**
docs: add Russian translation for ru/glossary/ipv4/index.md and ru/glossary/ipv6/index.md

docs: update Russian translation for ru/glossary/internet/index.md and ru/glossary/ip_address/index.md

### CODE REVIEW

**Comment by impocode** [comment]
@lex111

Привет! Очень жду обратную связь)

**Comment by sashasushko** [comment]
@impocode thank you for your help. Sorry for long response. I remember about your PR. And I'll review it ASAP. Peace 🕊

**Comment by sashasushko** [comment]
It's ok. I'll resolve conflicts.

**Comment by queengooborg** [comment]
Since this PR has been sitting around for a while, I've gone ahead and made the appropriate changes to effectively rebase this.  I took the liberty of also adding the `sourceCommit` property to track how in-sync the pages are with upstream content.  This should now be ready to review!

**Comment by queengooborg** [comment]
Ah, wait- I just noticed that the source repository was actually deleted altogether so there's no branch to push to.  In this case, I'll open a new PR!

**Pull request closed without merging**
