### PR TITLE
Convert /glossary folder to Markdown (es)

### PR DESCRIPTION
**Pull request by queengooborg**
This PR converts the `/glossary` folder to Markdown for the Spanish locale, using my fork of the [`mdn-markdown` repository](https://github.com/queengooborg/markdown/tree/improve-conversion), followed by manual tweaks as needed.  Some files were removed in this PR, either because they were deleted upstream or are too far out of sync with upstream.

This effectively reverts #7469 by re-performing #7376 including updates from #7436.

_Disclaimer: I am an English content writer rather than a localization expert, and as such I strive to keep my changes purely editorial._

### CODE REVIEW

**Comment by queengooborg** [comment]
CC @JuanVqz who reviewed the original PR.

**Comment by Graywolf9** [comment]
Hi again @queengooborg did you think this PR can be split too to do a better review?

**Comment by queengooborg** [comment]
Of course, that's the plan!  I've marked this as a draft so it can be used as a breakdown list.  👍

**Comment by Graywolf9** [comment]
Thank you so much!

**Pull request closed without merging**
