### PR TITLE
[ja]: add sidebar to all Glossary pages

### PR DESCRIPTION
**Pull request by leon-win**
### Description

Add sidebar (with list of terms) to all Glossary pages in Japanese locale.

### Motivation

Sidebar is useful for navigation in Glossary, so this change will improve user experience.

### Related issues and pull requests

Fixes #16942
Relates to #16863, #16943, #16970

### CODE REVIEW

**Comment by mfuji09** [comment]
@leon-win ,
This pull request is too large to review at once. The user interface for the review has been very heavy. Please split this PR into several PRs.

**Comment by leon-win** [comment]
> @leon-win , This pull request is too large to review at once. The user interface for the review has been very heavy. Please split this PR into several PRs.

Hello @mfuji09 !

Yes, this PR turned out to be very large in terms of the number of changed files =(
However, all the changes are trivial: I added `{{GlossarySidebar}}` macro to all pages of the `ja` Glossary, this can be seen in the tree of changed files (that is, files from other sections are not affected):
image image

I can split the PR into several parts, but I don’t know on what principle to do this splitting =( Now (despite the large number of changed files) the PR is logically complete and has a specific goal -- to add a sidebar to all pages of the `ja` Glossary.

**Comment by mfuji09** [comment]
@leon-win 
I think your change for each files will be trivial, but I can't confirm whether they are correct or not because the review user interface can't deal such a lot of files.
Please split into several pull requests which have about maximum 100 change files, as like other pull requests.

**Comment by leon-win** [comment]
> @leon-win I think your change for each files will be trivial, but I can't confirm whether they are correct or not because the review user interface can't deal such a lot of files. Please split into several pull requests which have about maximum 100 change files, as like other pull requests.

@mfuji09, I split changes to several PR's: #17031, #17032, #17033, #17034, #17035, #17036
Now it will be more comfortable to do a review :)

I am closing this request :ok_hand:

**Pull request closed without merging**
