### PR TITLE
:globe_with_meridians: refactor the zh-CN Webextensions index page according to the en-US page.

### PR DESCRIPTION
**Pull request by tolerious**

### CODE REVIEW

**Comment by irvin** [comment]
you need to first mv index.html to index.md as first commit, and change the content of the file as second one.

**Comment by yin1999** [comment]
You can create a new pr, or using `git reset` to undo those commit (soft reset will not delete `.md` file)

**Comment by yin1999** [comment]
> You can create a new pr, or using `git reset` to undo those commit (soft reset will not delete `.md` file)

then:

1. copy the content in `.md` file
2. undo changes in `.html` file
3. using `git mv` to rename `.html` file to `.md`, and then commit
4. paste content to `.md` file, and then commit

**Comment by tolerious** [comment]
> You can create a new pr, or using `git reset` to undo those commit (soft reset will not delete `.md` file)

OK。

**Comment by tolerious** [comment]
> > You can create a new pr, or using `git reset` to undo those commit (soft reset will not delete `.md` file)
> 
> then:
> 
>     1. copy the content in `.md` file, and then delete `.md` file
> 
>     2. undo changes in `.html` file
> 
>     3. using `git mv` to rename `.html` file to `.md`, and then commit
> 
>     4. paste content to `.md` file, and then commit
> 
>     5. force push to remote



> > You can create a new pr, or using `git reset` to undo those commit (soft reset will not delete `.md` file)
> 
> then:
> 
>     1. copy the content in `.md` file, and then delete `.md` file
> 
>     2. undo changes in `.html` file
> 
>     3. using `git mv` to rename `.html` file to `.md`, and then commit
> 
>     4. paste content to `.md` file, and then commit
> 
>     5. force push to remote

@yin1999  Is that right now?

**Comment by yin1999** [comment]
> You should use `git reset` to undo all previous commits first. If you're not familiar with that just create a new PR.

```bash
git reset HEAD~N # to undo the previous N commits
```

Reference: http://www.runoob.com/git/git-reset.html

**Pull request closed without merging**
