### PR TITLE
zh-cn/learn, replace unicode space to ascii space

### PR DESCRIPTION
**Pull request by fwqaaq**
The `.html` file in the zh-cn have all replaced unicode space with ascii space.

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
checked locally

**Comment by Jack-Zhang-1314** [comment]
There should be no more in the zh-cn.

**Comment by Jack-Zhang-1314** [comment]
Previous translation issues need to be addressed. I'll improve it.
<https://github.com/mdn/content/issues/17799#event-7037357843>

**Comment by Jack-Zhang-1314** [comment]
But english documnet has not been changed, do we need to change it in advance?

**Comment by yin1999** [comment]
> But english documnet has not been changed, do we need to change it in advance?

[`mdn/yari`](https://github.com/mdn/yari/actions/workflows/prod-build.yml) builds those documents and serving them on aws s3 at 00:00 UTC everyday. So the changes may not be applyed immediately, just follow the [raw document](https://github.com/vvswps/content/blob/main/files/en-us/web/api/textdecoderstream/index.md) in mdn/content

**Comment by Jack-Zhang-1314** [comment]
Oh, I see. I will improve it.

**Pull request merged**
