### PR TITLE
fix: Markdownlint cleanup for KO

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by hochan222** [comment]
@cos18  님, 안녕하세요. PR 리뷰가 지연되고 있어서 확인 부탁드립니다 🙇🙇

**Comment by nschonni** [comment]
@hochan222 I think you could review it as well to land it (if you have time), the assignment is just random based on the team

**Comment by hochan222** [comment]
I assigned a team to reviewers. I will review after dealing with other issues.

Thank you for your contribution.

**Comment by hochan222** [comment]
If the same issue occurs later, please mention me or @mdn/yari-content-ko :)

**Comment by nschonni** [comment]
Will do, but I'm not sure I can mention the team, because I'm not a member of the MDN org

**Comment by hochan222** [comment]
`mdn/yari-content-ko` is a team that only local Korean reviewers belong to. `mdn/yari-content-ko` is also in charge of Korean PR-related reviews, so if it is an important problem that is being delayed due to more than two weeks of PR like now, I don't know what other locales are, but feel free to comment.

Perhaps, from my experience so far, other locales are also welcome to comment if you have questions about the locale or have difficulties contributing :)

**Comment by nschonni** [comment]
I meant that when I type in @mdn/yari-content-ko the team doesn't get mentioned/notified 😉 
It's a GitHub feature to reduce notification spam from people outside the organization 😄

**Review by cos18 — APPROVED** [review]
Sorry for the delay :(
LGTM!

**Pull request merged**
