### PR TITLE
fix: make the link's  content are the same

### LINKED ISSUE #6191: The links are the same, but the content of the link is different.
The links are the same, but the content of the link is different.

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/index.html#L59

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/normal_flow/index.html#L93

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/supporting_older_browsers/index.html#L232

### PR DESCRIPTION
**Pull request by liulinboyi**
close #6191

Make the link's  content are the same.
The link is `/zh-CN/docs/Learn/CSS/CSS_layout/Responsive_Design`

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/index.html#L59

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/normal_flow/index.html#L93

https://github.com/mdn/translated-content/blob/cfdbbbc886765b2d7bf5880173de99eb8a60a7ab/files/zh-cn/learn/css/css_layout/supporting_older_browsers/index.html#L232

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
Thanks a lot. Welcome aboard

**Comment by liulinboyi** [comment]
> Thanks a lot. Welcome aboard

image
There is also a mistake here, but i cant find the location of the mistake in the project😉.

**Comment by yin1999** [comment]
> > Thanks a lot. Welcome aboard
> 
> image There is also a mistake here, but i cant find the location of the mistake in the project😉.

See: https://github.com/mdn/yari/blob/12e438190d7221da87f0db2d342fd3611f317461/kumascript/macros/LearnSidebar.ejs#L1130

**Comment by liulinboyi** [comment]
> > > Thanks a lot. Welcome aboard
> > 
> > 
> > image There is also a mistake here, but i cant find the location of the mistake in the project😉.
> 
> See: [mdn/yari@`12e4381`/kumascript/macros/LearnSidebar.ejs#L1130](https://github.com/mdn/yari/blob/12e438190d7221da87f0db2d342fd3611f317461/kumascript/macros/LearnSidebar.ejs#L1130)

Thanks!😉

**Comment by yin1999** [comment]
> > Thanks a lot. Welcome aboard
> 
> image There is also a mistake here, but i cant find the location of the mistake in the project😉.

If you pick this job, please  pin me for a review

**Comment by liulinboyi** [comment]
> > > Thanks a lot. Welcome aboard
> > 
> > 
> > image There is also a mistake here, but i cant find the location of the mistake in the project😉.
> 
> If you pick this job, please pin me for a review

Got it!

**Comment by liulinboyi** [comment]
> > > Thanks a lot. Welcome aboard
> > 
> > 
> > image There is also a mistake here, but i cant find the location of the mistake in the project😉.
> 
> If you pick this job, please pin me for a review

Fixed! https://github.com/mdn/yari/pull/6513

**Pull request merged**
