### PR TITLE
Fixes #4686, #4691, #4692

### LINKED ISSUE #4686: Broken link to example on "API tierces"
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

#### What information was incorrect, unhelpful, or incomplete?
Link to API MapQuest example is broken

#### Specific section or headline?
Qu'est-ce qu'une API tierce ?

#### What did you expect to see?
The example

#### Did you test this? If so, how?
Yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

### LINKED ISSUE #4691: Broken learning-area link on "API tierces"
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

#### What information was incorrect, unhelpful, or incomplete?
Link to 'https://mdn.github.io/learning-area/javascript/apis/third-party-apis/mapquest/' in 'Qu'est-ce qu'une API tierce ?' is broken

#### Specific section or headline?
Qu'est-ce qu'une API tierce ?

#### What did you expect to see?
See the example

#### Did you test this? If so, how?
Yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

### LINKED ISSUE #4692: Issue with "API tierces": (short summary here please)
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

#### What information was incorrect, unhelpful, or incomplete?
Links to starting files to test New York Times API are broken:
- https://github.com/mdn/learning-area/blob/main/javascript/apis/third-party-apis/nytimes/nytimes_start.html
- https://github.com/mdn/learning-area/blob/main/javascript/apis/third-party-apis/nytimes/nytimes.css

#### Specific section or headline?
https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs#obtenir_une_cl%C3%A9_de_d%C3%A9veloppement

#### What did you expect to see?
Files source code

#### Did you test this? If so, how?
Yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

### PR DESCRIPTION
**Pull request by SphinxKnight**
This intends to update the Third party APIs article in French (vs en-US) to fix #4686, #4691, #4692.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@StephaneRegnie sorry for bothering you after quite some time regarding this, but if you have a few minutes to spare, I would greatly appreciate a check on the updated page to be sure I didn't miss a link :)

Thanks a lot and sorry for the lag :)

**Comment by StephaneRegnie** [comment]
@SphinxKnight #4691 OK 👍

**Comment by StephaneRegnie** [comment]
@SphinxKnight About #4692, still KO, I took some captures for you. Little precision if needed: the problem is only in the FR version, EN links are working fine.
 
image
Capture d’écran 2022-05-02 101912
image

**Comment by SphinxKnight** [comment]
@StephaneRegnie thanks a lot :pray: really appreciate.
For MapQuest, I think this is due to the API key not being provided (I'll dig further to (in)validate this)

For #4692, I gather from the screenshots that this is the "current"/production version (located under https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs ), what I meant was a check on the proposed patched page:  https://pr5322.content.dev.mdn.mozit.cloud/fr/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs (it looks to me this is OK and moreover after your screenshots) but I just wanted to be sure. This PR intends to fix those and, as far as I know, there has been no other patch yet, that's why the links still fail on production.

**Comment by StephaneRegnie** [comment]
@SphinxKnight OK, my bad ^^ I confirm you that the link is working fine on the proposed patched page 👍

**Comment by SphinxKnight** [comment]
Thanks a lot for your time and patience, I'll get this merged then :)

**Pull request merged**
