### PR TITLE
update links for zh-CN: `en-US` -> `zh-CN`

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
use `/en-US` -> `/zh-CN`

### CODE REVIEW

**Comment by yin1999** [comment]
Hi @awxiaoxian2020, could you provide the script you have used to process this?

**Comment by awxiaoxian2020** [comment]
> Hi @awxiaoxian2020, could you provide the script you have used to process this?

I just use a replacement `/en-US` -> `/zh-CN` and make it case senstive in vscode...

**Comment by yin1999** [comment]
> I just use a replacement `/en-US` -> `/zh-CN` and make it case senstive in vscode...

This is not reliable, some `/en-US` may not appear in the link. And there are too many files, it's a bit difficult to review all of those changes.

Could you try to parse markdown file and replace string only in links?

**Comment by awxiaoxian2020** [comment]
> > I just use a replacement `/en-US` -> `/zh-CN` and make it case senstive in vscode...
> 
> This is not reliable, some `/en-US` may not appear in the link. And there are too many files, it's a bit difficult to review all of those changes.
> 
> Could you try to parse markdown file and replace string only in links?

I have no experience about it. 

But I use a different way to replace(`](/en-US`) and git diff and get the following result:


Now we have no reasons to remain any `/en-US` in our docs on my side, which potential errors can be corrected easily.
If you think it is not reliable, I can just close it :)

**Comment by yin1999** [comment]
In some live sample, we have used some image from en-US, so the uri will be `/en-us/docs/...`, the changes you have made will break this

**Comment by yin1999** [comment]
Please replace `](/en-US/` and `](</en-US/` and do not replace widely

**Comment by yin1999** [comment]
> Please replace `](/en-US/` and `](</en-US/` and do not replace widely

after that, you can replace `href="/en-US/`. There won't be too many files.

**Comment by yin1999** [comment]
Hi @awxiaoxian2020, if you want to help with this, please try [this yari branch](https://github.com/yin1999/yari/tree/update-to-locale). You can run `yarn tool fix-flaws --locale zh-CN` to replace `/en-US/` and `/en/` with `/zh-CN/` only for links.

Note that, please spread the fixes into multiple PRs (see the number of changed files, less than 200).

**Pull request closed without merging**
