### PR TITLE
ru: Further translate Learn/JavaScript/Client-side_web_APIs/Client-side_storage

### PR DESCRIPTION
**Pull request by TLohinava**
Частичный перевод про IndexedDB

### CODE REVIEW

**Comment by sashasushko** [comment]
@TLohinava thank you for your help. I remember about your PR. And I'll review it ASAP. Peace 🕊

**Comment by myshov** [comment]
@TLohinava hi! Sorry for the long delay with review :( MDN content has changed a bit and now we use Markdown files. Could you please to update your translation to Markdown format?

**Comment by queengooborg** [comment]
Since there hasn't been any response for a while, I decided to perform the Markdown conversion and unblock this; it didn't feel right to close this as idle and lose the translation work.  This is now ready to be reviewed!  (CC @sashasushko @myshov)

**Comment by queengooborg** [comment]
Since this PR has been sitting around for over a year, I am going to go ahead and merge it. I apologize if there are inaccuracies in the translation (I don't speak Russian), but it does not feel right to simply close the PR and waste the contributor's efforts.

**Pull request merged**
