### PR TITLE
[RU] <col>

### PR DESCRIPTION
**Pull request by scffs**
1. Обновил title.
2. Перевёл некоторый текст.

### CODE REVIEW

**Comment by Saionaro** [comment]
@scffs привет! Почему PR - draft? Тут ещё ведётся работа?

**Comment by scffs** [comment]
> @scffs привет! Почему PR - draft? Тут ещё ведётся работа? 

Да... сегодня постараюсь доделать

**Comment by queengooborg** [comment]
Hey @scffs, sorry for the delay in reviewing this!  It looks like nobody was assigned to review the PR -- I've gone ahead and assigned someone for you.  Additionally, I've taken the liberty to rebase this PR, and make a few tweaks (namely, replacing the deprecated macro calls and adding the `sourceCommit` front matter key so we can track synchronization with upstream).  Thank you for your hard work!

**Comment by queengooborg** [comment]
Since this PR has been sitting around for over a year, I am going to go ahead and merge it. I apologize if there are inaccuracies in the translation (I don't speak Russian), but it does not feel right to simply close the PR and waste the contributor's efforts.

**Pull request merged**
