### PR TITLE
Fix some <code> tags

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This PR replaces some `<font>` tags with `<code>` to harmonize the paragraphs they're in, as well as moving some punctuation out of other tags.

### CODE REVIEW

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Thanks for the PR! 
However, this page is significantly lagging behind the English version (see https://github.com/mdn/content/blob/main/files/en-us/web/manifest/index.html )
Before merging the following points should be addressed:

* Change the compat table to use {{Compat("html.manifest")}} instead of the table and its notes
* Remove other <font> in the document
* Remove all of the <span>s in the code sample which are due to "rich" copy paste in the old editor :/ 

@LaurentTreguier let me know if this sounds OK to you or if you need help editing on your branch :)

**Comment by SphinxKnight** [comment]
@LaurentTreguier do you need help with this one?

**Comment by LaurentTreguier** [comment]
Sorry, this slipped from my mind; I'll check how to properly setup my environment to do the changes.
If you know what changes need to be made though, I'll gladly accept some help, as I'm not sure what the changes actually entail yet (this PR and #74 were my first look at those docs and I'm not familiar with them)

**Comment by SphinxKnight** [comment]
Hello, no need for excuses :) 

Regarding the local setup, I wrote this https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer which may help. For the changes I've requested, let me know if any of them is unclear or if help is needed on a specific aspect.

Hope this helps :)

**Review by SphinxKnight — APPROVED** [review]

**Pull request merged**
