### PR TITLE
fix: replace TT tags with backticks

### PR DESCRIPTION
**Pull request by nschonni**
### Description

The tag is depreciated and not used upstream anymore. Left the ones in an orphan file and the code examples that upstream also kept

### CODE REVIEW

**Review by SphinxKnight — APPROVED** [review]
Thanks @nschonni :bow: :)

**Review by Graywolf9 — APPROVED** [review]
Thank you so much!

**Review by yin1999 — APPROVED** [review]
LGTM for zh-CN and zh-TW :)

**Review by pje1740 — APPROVED** [review]
LGTM!

**Comment by nschonni** [comment]
I think each of the locales has signed off, if someone wants to land it

**Pull request merged**
