### PR TITLE
Fix a typo in README.md

### PR DESCRIPTION
**Pull request by Marketionist**
### Description

Fix a typo in README.md.

### Motivation

I want to help other readers and contributors to have a cleaner text.

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM. Thanks @Marketionist.

**Comment by yin1999** [comment]
Welcome to the community @Marketionist 🎉

**Comment by Marketionist** [comment]
Thank you @yin1999! I'd like to continue contributing - is it possible to be added to https://github.com/mdn organization to be able to suggest improvements directly without forking this repository?

**Comment by yin1999** [comment]
Hey @Marketionist. We have some requirements to be an organization member and have a specified org role (see [MDN Web Docs roles and teams](https://developer.mozilla.org/en-US/docs/MDN/Community/Roles_teams#summary_of_the_roles)). If you want to be an org member, please participate in and contribute to the MDN Web Docs project regularly.

You could also check the [teams listed here](https://developer.mozilla.org/en-US/docs/MDN/Community/Roles_teams#teams) (as some additional rights like write permission to some repos are assigned based on teams) and [contact us](https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels) for more information about join a specified team.

**Comment by Marketionist** [comment]
Sounds great, thanks @yin1999!

**Pull request merged**
