### PR TITLE
fix: Remove compat macro from WebAssembly overview pages

### PR DESCRIPTION
**Pull request by bsmth**
### Description

The macro was removed in https://github.com/mdn/content/pull/30635

### Motivation

Builds were reporting errors that the macro is not rendering.

### Related issues and pull requests

- [x] https://github.com/mdn/content/pull/30635

## Approvals

- [x] `es`
- [x] `fr`
- [x] `ru` 
- [x] `zh-CN`
- [x] `ja`
- [x] `pt-br`
- [x] `ko`

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for zh. Thank you @bsmth

**Review by JuanVqz — APPROVED** [review]
Looks Good for ES Team :+1: , @Graywolf9

**Review by wisedog — APPROVED** [review]
Thank you @bsmth.👍 LGTM for ko.

**Review by saionaro — APPROVED** [review]
LGTM for ru

**Review by tristantheb — APPROVED** [review]
👍🏻 Ok for fr

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`!

**Comment by SphinxKnight** [comment]
@mdn/yari-content-pt-br if you have some spare minutes, that would be appreciated :) don't hesitate if you have questions/feedback

**Comment by bsmth** [comment]
Quick reminder @mdn/yari-content-pt-br if someone could have a look, it would be great to merge this! Thank you!

**Review by josielrocha — APPROVED** [review]
Approve for `pt-BR`

**Pull request merged**
