### PR TITLE
deleted duplicated mdn/content images/assets #4545

### PR DESCRIPTION
**Pull request by yechoi42**
#4545 에서 명기된 파일을 모두 삭제하였습니다

### CODE REVIEW

**Comment by cw118** [comment]
Hi there, just a quick but important note that these files should stay until mdn/yari#5652 is fixed, otherwise Korean live samples will be broken (cf. French pages which have this problem :/). 

The assets fix had worked locally in dev but does not currently work in prod, so please don't merge this before the yari issue is resolved.

**Comment by cw118** [comment]
> @cw118 Would it be okay to merge now?

Hello, as far as I know the issue is unfortunately still not resolved, so if this is merged then Korean live samples that use images from mdn/content will not work (cf. [the fr CSS filter page](https://developer.mozilla.org/fr/docs/Web/CSS/filter#blur) for examples).

**Comment by hochan222** [comment]
Thank you for your reply. It's been quite some time for PR, so I asked once. 

Have a nice day :)

**Comment by yin1999** [comment]
Hi @hochan222, we can go ahead now. The platform issue has been fixed by mdn/yari#7917. We can now safely remove duplicated images/assets. Please merge main branch and check the related content changes :)

**Review by hochan222 — APPROVED** [review]
LGTM :)

**Pull request merged**
