### PR TITLE
Migrate CompatibilityTable to Compat macro (pt-br)

### LINKED ISSUE #354: Migrate CompatibilityTable to Compat macro
I have created a macro that migrates `{{CompatibilityTable}}` macro to `{{Compat()}}` macro.
https://gist.github.com/YujiSoftware/420641a79d12c074a96210e644953038

First, apply to Japanese.
Apply to other languages if needed.

----

`{{CompatibilityTable}}` マクロを `{{Compat()}}` マクロに移行するマクロを作成しました。
これを、MDN に適用します。

まずは、日本語に適用します。
必要であれば、他の言語にも適用します。

### PR DESCRIPTION
**Pull request by YujiSoftware**
# Related Issue

fix #354

# Work

I applied the issue-described site compatibility table migration script to the Compat macro for the documentation.
This script does the following:

* Delete {{CompatibilityTable}} to the line before the next h2 tag in each file
* Added the {{Compat()}} macro described in the English version (of the same path)

### CODE REVIEW

**Comment by cw118** [comment]
@mdn/yari-content-pt-br could someone please take a look? After this is merged, many deprecated compat macros will (likely) be removed from `translated-content` and could be deleted :)

**Comment by josielrocha** [comment]
> @mdn/yari-content-pt-br could someone please take a look? After this is merged, many deprecated compat macros will (likely) be removed from `translated-content` and could be deleted :)

Hi @cw118!
Thank you for your work!
Unfortunatelly there are some conflicts here. I think it is caused by markdown conversion pull requests. Could you please resolve them? As soon as it is resolved I can review it again.

**Comment by cw118** [comment]
Thank you for replying @josielrocha :)

On second thought, @YujiSoftware would it be possible to close this and create a new PR, so that you are executing your script on an updated fork of `translated-content`? This one has so many conflicts and would likely be difficult to resolve and review.

**Comment by YujiSoftware** [comment]
Thank you for comments @cw118 , @josielrocha 
Once again, I created #7640. Please check this.

**Pull request closed without merging**
