### PR TITLE
feat: update \s match character

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Review by yin1999 — COMMENTED** [review]
Good catch. @btea would you mind to modify this line in en-US: https://github.com/mdn/content/blob/b4c032caa3815d7805c10f4ef0c337f882afddda/files/en-us/web/javascript/guide/regular_expressions/character_classes/index.md?plain=1#L164

and this line for zh-CN: https://github.com/mdn/translated-content/blob/251de96d1c5186b6fe0f82b0366c16f3589e8f34/files/zh-cn/web/javascript/guide/regular_expressions/character_classes/index.md?plain=1#L87

For this file, we'd better the remove the whole table (for we have remove this part from this document) we can do this in the future PR

**Comment by btea** [comment]
I have created a [pr](https://github.com/mdn/content/pull/23490).

**Comment by yin1999** [comment]
> I have created a [pr](https://github.com/mdn/content/pull/23490).

Thanks, let's wait until mdn/content landed this

**Comment by yin1999** [comment]
Please apply the changes made in content repo. I'll merge this PR after that.

**Comment by btea** [comment]
> Please apply the changes made in content repo. I'll merge this PR after that.

Updated.

**Review by yin1999 — APPROVED** [review]
Thank you

**Pull request merged**
