### PR TITLE
Update the resource link about module example

### LINKED ISSUE #5981: Issue with "Módulos JavaScript": (github repo: page not found)
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Modules

All examples from the github repo, when I try access page is not found.

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/guide/modules/index.html
* Last commit: https://github.com/mdn/translated-content/commit/da778d8d0a9e9622c6a7fba6d1f9fb7d3ebf4a04
* Document last modified: 2021-08-19T13:37:01.000Z

</details>

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
close #5981 .
sync with https://github.com/mdn/js-examples/pull/17 and https://github.com/mdn/content/pull/16197.
use `master/modules` -> `master/module-examples`.
I don't know whether there are all updated and there are side effects. Please have a review.

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@yin1999 could you have a review about this PR again?

**Review by yin1999 — APPROVED** [review]
LGTM for zh-CN

**Review by yin1999 — APPROVED** [review]

**Review by cos18 — APPROVED** [review]
LGTM in KO
Thank you for contribution!

**Review by JuanVqz — APPROVED** [review]
@awxiaoxian2020 Thank you! @mdn/yari-content-es :+1:

**Review by sashasushko — APPROVED** [review]
Approve from @mdn/yari-content-ru

**Comment by sashasushko** [comment]
@awxiaoxian2020 thank you for your help 🤝

**Pull request merged**
