### PR TITLE
zh-cn: update the translation of glossary - application context

### PR DESCRIPTION
**Pull request by PassionPenguin**
PTAL [@JasonLamv-t ](https://github.com/mdn/translated-content/pull/19923#issuecomment-2087971237)

(#19923 incorrectly push another unrelated md to the branch...)

### CODE REVIEW

**Comment by yin1999** [comment]
Hey @PassionPenguin. If you find that you have miss-added another unreleated files to the PR. You can simply delete the file and make one more commit.

**Comment by PassionPenguin** [comment]
> Hey @PassionPenguin. If you find that you have miss-added another unreleated files to the PR. You can simply delete the file and make one more commit.

yeap, but since no one had begun reviewing, creating a clean pr with clean file modification could be a better choice?

**Comment by yin1999** [comment]
> > Hey @PassionPenguin. If you find that you have miss-added another unreleated files to the PR. You can simply delete the file and make one more commit.
> 
> yeap, but since no one had begun reviewing, creating a clean pr with clean file modification could be a better choice?

Closing a PR and then creating a new one makes a lot of noise (in fact, the localization team members will be notified when a PR is created or closed). So, it would be better to resolve the problem within the original PR (reset and force push, or make a file deletion commit, either of them is ok).

**Review by JasonLamv-t — APPROVED** [review]
LTGM! Thank you! @PassionPenguin

**Pull request merged**
