### PR TITLE
Fix #16073

### LINKED ISSUE #16073: Redundancy when using a Request object in the Fetch API
### MDN URL

https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch

### What specific section or headline is this issue about?

[Fournir votre propre objet requête](https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch#fournir_votre_propre_objet_requ%C3%AAte)

### What information was incorrect, unhelpful, or incomplete?

```
var myHeaders = new Headers();

var myInit = {
  method: "GET",
  headers: myHeaders,
  mode: "cors",
  cache: "default",
};

var myRequest = new Request("flowers.jpg", myInit);

fetch(myRequest, myInit)       ///// Look at this line 
  .then(function (response) {
    return response.blob();
  })
  .then(function (myBlob) {
    var objectURL = URL.createObjectURL(myBlob);
    myImage.src = objectURL;
  });

```
### What did you expect to see?

```
var myHeaders = new Headers();

var myInit = {
  method: "GET",
  headers: myHeaders,
  mode: "cors",
  cache: "default",
};

var myRequest = new Request("flowers.jpg", myInit);

fetch(myRequest)           ////// I think, this is more appropriate
  .then(function (response) {
    return response.blob();
  })
  .then(function (myBlob) {
    var objectURL = URL.createObjectURL(myBlob);
    myImage.src = objectURL;
  });

```
### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

when creating a **Request** object, it is possible to provide the **init** parameter directly in the constructor of the Request object, so it is no longer necessary to provide it as a parameter of the **fetch()** function. I think it is appropriate to replace it in the document, although the code still works.
### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

### PR DESCRIPTION
**Pull request by SphinxKnight**
A general update of the page to fix #16073 along the way.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@Max-Sunder using the preview link from the bot, could you please let me know if you agree this version is exempt from the "double init" issue raised in #16073? Thanks a lot!

**Comment by Max-Sunder** [comment]
That's great. It was a pleasure.

**Comment by tristantheb** [comment]
@SphinxKnight Je t'ai corrigé un lien sur le bas de page ;)

**Review by tristantheb — APPROVED** [review]
Looks good

**Pull request merged**
