### PR TITLE
Markdown fixes part 1 (fr/web/a*)

### PR DESCRIPTION
**Pull request by cw118**
A follow-up of #3850 in a way (missed lots of files there :/). Removes spaces in code spans, link text and emphasis markers (`**` and `*`), which tend to render incorrectly.

Part 1 covers `web/accessibility` and `web/api`. I've linted all modified files to try to make sure nothing problematic was injected in the process and hopefully make reviewing easier (let me know how I can help with this or how these types of fixes should be done in the future).

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@cw118 thanks a lot, I'll review this shortly 🙏

Regarding this kind of "massive/batch" changes, I'd be enclined to keep a single kind of change in such PRs and would not mix removal of xref macros and the like (esp. if the PR title 

That being written, we can keep this one as is, I don't consider it to be blocking here but it really help reviewing when the scope is limited to one kind of change for a large volume of file. (and I know I may have not followed this rule in the past 😖)

**Comment by SphinxKnight** [comment]
and +1 to split this into different PRs

**Comment by cw118** [comment]
> Regarding this kind of "massive/batch" changes, I'd be enclined to keep a single kind of change in such PRs and would not mix removal of xref macros and the like (esp. if the PR title stays the same)
>
> That being written, we can keep this one as is, I don't consider it to be blocking here but it really help reviewing when the scope is limited to one kind of change for a large volume of file. (and I know I may have not followed this rule in the past 😖)

Understood, my bad for complicating things. Wasn't sure what scope to limit it to here but I'll keep this in mind!

**Comment by SphinxKnight** [comment]
> Understood, my bad for complicating things. Wasn't sure what scope to limit it to here but I'll keep this in mind!

No worries :) (it's quite difficult to let go of issues when we're seeing them while fixing others ^^ )

**Review by SphinxKnight — APPROVED** [review]
J'ai échantillonné la revue sur la moitié des pages, c'est OK pour moi. Merci beaucoup pour tout ce travail @cw118.

**Comment by SphinxKnight** [comment]
Je pense que les regexp suivantes peuvent permettre de détecter les cas pour les fragments de code (avec certains légers faux positifs): 

* ```
  `(\w*?) `\w
  ```
* ```
  \w` (\w*?)`
  ```
* ```
  \*\*`([^*]*?) `\*\*
  ```
* ```
  \*\*` ([^*]*?)`\*\*
  ```

Ce qui nous donne, avec la disjonction de tout ça, cette magnifique (non) expression
```
(`(\w*?) `\w)|(\w` (\w*?)`)|(\*\*`([^*]*?) `\*\*)|(\*\*` ([^*]*?)`\*\*)
```

**Comment by SphinxKnight** [comment]
Pour les liens :

```
[ ]\]\(
```
et 
```
\[[ ](.*)\]\(
```

**Comment by cw118** [comment]
Merci beaucoup pour la relecture et ces regexp magnifiques 😄

**Pull request merged**
