### PR TITLE
typos fix

### PR DESCRIPTION
**Pull request by maxiller**

### CODE REVIEW

**Comment by sashasushko** [comment]
@maxiller thank you for your help. Sorry for long response. I remember about your PR. And I'll review it ASAP. Peace 🕊

**Review by yanaklose — APPROVED** [review]

**Comment by yanaklose** [comment]
@maxiller please, rebase changes so the branch can be merged. Thank you!

**Comment by yin1999** [comment]
@yanaklose conflicts are resolved

/cc @mdn/yari-content-ru

**Review by myshov — APPROVED** [review]

**Comment by myshov** [comment]
@maxiller thanks!

**Pull request merged**
