### PR TITLE
[pt-BR] Replace @api/deki references

### PR DESCRIPTION
**Pull request by joaodinizgit**
### Description
Part of #10487 for pt-BR.

### Additional details
Script used:
grep -riE "\(\/@api\/deki\/files\/[0-9]*\/=([^\)]+)\)" files/pt-br/ -l | xargs -I {} sed -i -E s/"\(\/@api\/deki\/files\/[0-9]*\/=([^\)]+)\)"/"(\L\1)"/ig {}
grep -riE "\/@api\/deki\/files\/[0-9]*\/=([^\)]+)\"" files/pt-br/ -l | xargs -I {} sed -i -E s/"\/@api\/deki\/files\/[0-9]*\/=([^\)]+)\""/"\L\1\""/g {}

### Related issues and pull requests
Part of #10487.

### CODE REVIEW

**Comment by caugner** [comment]
Hi @joaodinizgit, did you intentionally close this PR?

**Comment by joaodinizgit** [comment]
Hi, @caugner. Yes, I closed. I used the script, it changed as expected, but the check show a lot of errors from "prettier".

**Comment by caugner** [comment]
@joaodinizgit When you encounter prettier errors, you should be able to run `yarn run fix:md` to resolve them.

PS: Usually that command should run automatically via [lint-staged](https://github.com/mdn/translated-content/pull/14195) when you commit changes to Markdown files. 🤔

**Comment by joaodinizgit** [comment]
@cauner I will re do.

**Pull request closed without merging**
