### PR TITLE
feat: update latest location.reload() doc from content repo into zh-c…

### PR DESCRIPTION
**Pull request by liunnn1994**
The old documents are out of date. I translate from the [content repo](https://github.com/mdn/content) and moved html to md.

### CODE REVIEW

**Comment by yin1999** [comment]
For converting document from `index.html` to `index.md`, please using the following commits:

1. use a single commit to rename the file (from `.html` to `.md`), this will help us to track the history

    commit: convert to `.md` for some document

       git mv /path/to/some/index.html /path/to/some/index.md # 

2. use the second commit to convert the content and sync with english version

    commit: convert to markdown and sync with english version

You can refer: [commits in #4583](https://github.com/mdn/translated-content/pull/4583/commits)

**Comment by asdjgfr** [comment]
> For converting document from `index.html` to `index.md`, please using the following commits:
> 
> 1. use a single commit to rename the file (from `.html` to `.md`), this will help us to track the history
>    commit: convert to `.md` for some document
>    ```
>    git mv /path/to/some/index.html /path/to/some/index.md # 
>    ```
> 2. use the second commit to convert the content and sync with english version
>    commit: convert to markdown and sync with english version
> 
> You can refer: [commits in #4583](https://github.com/mdn/translated-content/pull/4583/commits)

done 😃

**Comment by yin1999** [comment]
Hi @asdjgfr, just keep only two commit in this pr. You should use `git rebase` to squash the last two commit.

**Comment by asdjgfr** [comment]
> 

done

**Comment by asdjgfr** [comment]
> Hi @asdjgfr, just keep only two commit in this pr. You should use `git rebase` to squash the last two commit.

done

**Comment by asdjgfr** [comment]
@irvin Can we merge this pr? I think online version is wrong. It will mislead some people, thx.

**Pull request merged**
