### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by halcance**
### Description

The article was not complete, the last 2 paragraphs was in English.

### Related issues and pull requests

Issue #9042

### CODE REVIEW

**Comment by cw118** [comment]
Hi @halcance, welcome to mdn/translated-content 🎉 (to the pt-br team, I hope it's OK for me to jump in here :))

> there is a conflict here. Could you please fix it?

I believe @josielrocha was referring to the **merge conflict** (near the bottom of this PR page it says "This branch has conflicts that must be resolved"), but thank you for fixing the links as well. There are 2 somewhat simple ways to resolve the merge conflict problem:

- Use git on the command line to resolve the conflict (e.g. with the command `git merge` and a code editor)
- *or* close this PR, update your fork (go to <https://github.com/halcance/translated-content> -> click "Sync fork" -> click on the button "Update branch"), then open a new pull request to make the same changes

Choose whichever "option" you prefer, and feel free to let us know if help is needed (if you would like/are OK with it I could also resolve the merge conflict for you and push/add a commit directly to your branch)! That being said, thank you so much for working on the issue :)

**Comment by halcance** [comment]
Thank you @cw118 for your help! I commited only the links cuz I was switching the editor and I didn't want to lose the modifications. I finished the flaws, can someone check?

**Comment by cw118** [comment]
I am not on the pt-br review team so I will let them review the content changes (i.e. the flaws), but I see that there is still a ***merge conflict* needs to be resolved first**. 

N.B. a *merge conflict* means that the file you edited is not up-to-date anymore because others modified it some time before/while you created this PR, so this repository has a newer version of the file while your PR has an older version with your changes. We need to **update your branch** so that you have the newer version of the file *and* the modifications you brought.

[See my comment above](https://github.com/mdn/translated-content/pull/9053#issuecomment-1271066733) for 2 solutions that I think are the simplest, and let us know if we can help :)

**Comment by halcance** [comment]
It's clear now, thank you again @cw118 I'll close this PR and update my branch

**Comment by halcance** [comment]
The conflict is that the HTML file was moved and converted to markdown

**Pull request closed without merging**
