### PR TITLE
[ko] fix: NOTE syntax

### PR DESCRIPTION
**Pull request by hochan222**
### Description

`> [!NOTE]`은 새로 추가된 github markdown으로 영어로만 사용 가능합니다. 

AS IS
```markdown
> [!참고] 
```

TO BE
```markdown
> [!NOTE] 
```

[[Markdown] An option to highlight a "Note" and "Warning" using blockquote (Beta)](https://github.com/orgs/community/discussions/16925)

cc. @mdn/yari-content-ko , @givvemee

### Related issues and pull requests

https://github.com/mdn/translated-content/pull/22796

### CODE REVIEW

**Comment by hochan222** [comment]
Hello, @queengooborg.

A markdown lint error occurred even though the content is identical to GFM Alerts. Do you have any guesses as to what the problem might be?

**Comment by queengooborg** [comment]
This is because of a [Prettier bug](https://github.com/prettier/prettier/issues/16454), unfortunately, where if the first character of the first line after the magic keyword is a special character (`, *, etc.), it combines the first and second lines.  For now, these blocks will have to use the original MDN syntax, until the issue is resolved in Prettier.

**Comment by hochan222** [comment]
@queengooborg I understand. Thank you. Have a great day :)

@wisedog prettier 오류로 린트 "https://github.com/prettier/prettier/issues/16454" 수정 전까지 린트 수정하지 않고 병합해도 좋을 듯합니다.

**Comment by givvemee** [comment]
오! 감사합니다. 
이전에 이렇게 번역한 것들이 몇 개 있었던 것 같은데 ... 시간 내서 다시 NOTE 로 되돌리는 PR 을 올려볼게요.

**Review by wisedog — APPROVED** [review]

**Comment by hochan222** [comment]
`yarn tool macro-usage-report --deprecated-only`

**AS IS**

| macro | yari | en-us | es | fr | ja | ko | pt-br | ru | zh-cn | zh-tw |
|:----- | ----:| -----:| --:| --:| --:| --:| -----:| --:| -----:| -----:|
|  CSSAnimatedProperties 🗑  |  -  |  -  |  -  |  <span title="/web/css/css_animated_properties/index.md …">1</span>  |  -  |  <span title="/web/css/css_animated_properties/index.md …">1</span>  |  -  |  -  |  -  |  -  |
|  DOMAttributeMethods 🗑  |  -  |  -  |  <span title="/web/api/element/getattributenodens/index.md …">3</span>  |  -  |  <span title="/web/api/element/getattributenode/index.md …">13</span>  |  <span title="/web/api/element/setattribute/index.md …">1</span>  |  -  |  -  |  -  |  -  |
|  event 🗑  |  -  |  -  |  -  |  -  |  -  |  <span title="/web/api/filereader/index.md …">61</span>  |  <span title="/conflicting/web/api/element/click_event/index.md …">76</span>  |  <span title="/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.md …">125</span>  |  -  |  -  |
|  no_tag_omission 🗑  |  -  |  -  |  <span title="/web/html/element/a/index.md …">27</span>  |  <span title="/web/html/element/i/index.md …">29</span>  |  -  |  <span title="/web/html/element/a/index.md …">59</span>  |  <span title="/web/html/element/a/index.md …">32</span>  |  <span title="/web/html/element/abbr/index.md …">49</span>  |  -  |  -  |
|  page 🗑  |  -  |  -  |  -  |  -  |  -  |  -  |  <span title="/web/api/batterymanager/charging/index.md …">47</span>  |  -  |  -  |  -  |
|  unimplemented_inline 🗑  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |

**TO BE**

| macro | yari | en-us | es | fr | ja | ko | pt-br | ru | zh-cn | zh-tw |
|:----- | ----:| -----:| --:| --:| --:| --:| -----:| --:| -----:| -----:|
|  CSSAnimatedProperties 🗑  |  -  |  -  |  -  |  <span title="/web/css/css_animated_properties/index.md …">1</span>  |  -  |  -  |  -  |  -  |  -  |  -  |
|  DOMAttributeMethods 🗑  |  -  |  -  |  <span title="/web/api/element/getattributenodens/index.md …">3</span>  |  -  |  <span title="/web/api/element/getattributenode/index.md …">13</span>  |  <span title="/web/api/element/setattribute/index.md …">1</span>  |  -  |  -  |  -  |  -  |
|  event 🗑  |  -  |  -  |  -  |  -  |  -  |  -  |  <span title="/conflicting/web/api/element/click_event/index.md …">76</span>  |  <span title="/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.md …">125</span>  |  -  |  -  |
|  no_tag_omission 🗑  |  -  |  -  |  <span title="/web/html/element/a/index.md …">27</span>  |  <span title="/web/html/element/i/index.md …">29</span>  |  -  |  <span title="/web/html/element/a/index.md …">58</span>  |  <span title="/web/html/element/a/index.md …">32</span>  |  <span title="/web/html/element/abbr/index.md …">49</span>  |  -  |  -  |
|  page 🗑  |  -  |  -  |  -  |  -  |  -  |  -  |  <span title="/web/api/batterymanager/charging/index.md …">47</span>  |  -  |  -  |  -  |
|  unimplemented_inline 🗑  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |  -  |

**Pull request merged**
