### PR TITLE
getting rid of .alllinks links

### PR DESCRIPTION
**Pull request by peterbe**
URLs like `/ja/docs/tag/Accessibility` don't work any more so no point making the links.

### CODE REVIEW

**Comment by peterbe** [comment]
This is breaking now because of https://github.com/mdn/yari/pull/3496 
so once Yari is upgraded, I'll update this PR.

**Comment by peterbe** [comment]
@dynamis Tests are passing now. r?

**Comment by peterbe** [comment]
@mfuji09 r?

**Review by mfuji09 — APPROVED** [review]
It seems good.

**Pull request merged**
