### PR TITLE
[ko] fix typo on page-report-ko.yml of issue template for korean

### PR DESCRIPTION
**Pull request by Shinhm**
### Description

fix typo on page-report-ko.yml of issue template for korean

### Motivation

When creating an issue, you will be able to use the template as it is without having to modify it individually.

### CODE REVIEW

**Comment by cw118** [comment]
Poking @mdn/yari-content-ko for a review on this :)

Aside: I had tried to configure the codeowners so that changes to `page-report-ko.yml` requests a review from the ko team, but it doesn't seem to be working and I am not sure why.

**Comment by Shinhm** [comment]
> Poking @mdn/yari-content-ko for a review on this :)
> 
> Aside: I had tried to configure the codeowners so that changes to `page-report-ko.yml` requests a review from the ko team, but it doesn't seem to be working and I am not sure why.

i can not found @mdn/yari-content-ko tag.
how do i contact to @mdn/yari-content-ko team.

**Comment by cw118** [comment]
Hi @Shinhm, MDN teams can only be seen by members of the MDN organization on GitHub, but the members of the yari-content-ko team are written here: https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams. I hope this helps, don't hesitate if I can help in any way :)

**Comment by Shinhm** [comment]
> Hi @Shinhm, MDN teams can only be seen by members of the MDN organization on GitHub, but the members of the yari-content-ko team are written here: https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams. I hope this helps, don't hesitate if I can help in any way :)

Hi @cw118, Thank you so much!

i will try contact to yari-content-ko team

**Comment by Shinhm** [comment]
@sunhpark42 님, 안녕하세요
문서에 오타가 있는것 같아서 pr 작성했는데 확인한번 부탁드립니다!

**Review by hochan222 — APPROVED** [review]
@Shinhm 님 안녕하세요. 

리뷰가 늦어져서 죄송합니다. 기여해주셔서 감사합니다. 좋은 주말 보내세요 :)

**Comment by hochan222** [comment]
@mdn/core-dev The content seems to be fine. This PR is failed as below. What should I do?

> If you're an admin, you have you use your admin privileges to override.
> If you're not an admin, please ping someone for a review.
> Error: Process completed with exit code 1.

**Comment by hochan222** [comment]
I found the same case in another PR, and since it was merged, there seems to be no problem. It's a simple typo change, so I'll just merge it.

Have a nice day :)

@Shinhm 님 안녕하세요. PR이 지연되어서 너무 죄송합니다. 

기여해주셔서 정말 감사드립니다. 좋은 하루 보내세요 :)

**Pull request merged**
