### PR TITLE
Remove occurrences of oaa-accessibility.org which has now nothing to do with Accessibility

### LINKED ISSUE #2377: Content bug: Redirection to bitcoin website
## What page(s) did you find the problem on?

https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

## Specific page section or heading?

image

## What is the problem?

There is a redirection to bitcoin website.

## What did you expect to see?

Maybe we should remove those ?

## Did you test this? If so, how?

With Firefox on ubuntu on the french version.

### PR DESCRIPTION
**Pull request by SphinxKnight**

### CODE REVIEW

**Review by mfuji09 — APPROVED** [review]
I have sent an additional commit to keep the article natural. It removes parts in Japanese articles which isn't already in English version.

**Comment by SphinxKnight** [comment]
> 
> 
> I have sent an additional commit to keep the article natural. It removes parts in Japanese articles which isn't already in English version.

Thanks @mfuji09

**Review by t7yang — APPROVED** [review]

**Review by mpstv — APPROVED** [review]

**Review by irvin — APPROVED** [review]

**Review by tristantheb — APPROVED** [review]

**Comment by SphinxKnight** [comment]
To anyone who approved this: thanks for the swift feedback.
@mdn/yari-content-ko @mdn/yari-content-pt-br : could you have a look please?

**Review by hochan222 — APPROVED** [review]
ko-locale clear!

**Pull request merged**
