### PR TITLE
Update index.md to fix a  calculate mistake

### PR DESCRIPTION
**Pull request by noobHuKai**

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
Good catch. Could you also update this line in en-US?

https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/cbrt/index.md?plain=1#L51

**Comment by noobHuKai** [comment]
> 接得好。您也可以在 en-US 中更新这一行吗？
> 
> https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/cbrt/index.md?plain=1#L51

**Comment by noobHuKai** [comment]
i'm sorry,this is my first pr. so...
en-US no problem !!!

**Comment by yin1999** [comment]
> i'm sorry,this is my first pr. so...
> en-US no problem !!!
> 

Never mind. If you have any problem on it, feel free to ping me for help.

**Review by yin1999 — APPROVED** [review]
Thanks. Welcome to the community: 🎉

**Pull request merged**
