### PR TITLE
Update Web Speech API demo links

### PR DESCRIPTION
**Pull request by mikecat**
### Description

Update URLs of Web Speech API demo to point the new repository.

### CODE REVIEW

**Review by sashasushko — APPROVED** [review]
Thanks 🙏 Approve from `ru`

**Review by yin1999 — APPROVED** [review]
LGTM for l10n-zh. Thank you!

**Review by SphinxKnight — APPROVED** [review]
✔️ for @mdn/yari-content-fr

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es`, thank you!

**Comment by Graywolf9** [comment]
I think is it only missing @mdn/yari-content-ja and @mdn/yari-content-pt-br ?

**Review by josielrocha — APPROVED** [review]
LGTM for `pt-BR`, thank you!

**Comment by SphinxKnight** [comment]
@mfuji09 / @potappo if you have some spare time :)

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja` content.

**Pull request merged**
