### PR TITLE
fr: Synchronize /Web/CSS/Shorthand_properties with upstream

### PR DESCRIPTION
**Pull request by queengooborg**
This PR replaces the tables in the `Web/CSS/Shorthand_properties` page of the French locale with unordered lists, just like it is in upstream.  This helps us mitigate a Prettier-Markdownlint conflict due to Prettier unindenting the HTML elements, and synchronizes the page more with upstream.

Note: **I did not add alt. text to the images because I don't speak French.  Reviewers, please add alt. text to the images before merging this pull request.**

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@queengooborg if you don't mind, I'll push a commit to update the whole page :)

**Comment by queengooborg** [comment]
Much appreciated!  Go for it, @SphinxKnight!

**Comment by SphinxKnight** [comment]
💅 DLs are underrated 💅 (as in, I went with what I think are slight improvement over the current English state)

**Comment by SphinxKnight** [comment]
@cw118 whenever you have time for this, I would appreciate a second pair of eyes :) (no rush :))

**Review by cw118 — APPROVED** [review]
Thank you @queengooborg and @SphinxKnight, let's merge this one 🎉

**Pull request merged**
