### PR TITLE
Chrome OS -> ChromeOS

### PR DESCRIPTION
**Pull request by queengooborg**
This PR changes all instances where "Chrome OS" is mentioned to say "ChromeOS", as is the correct spelling per Google's webpages and documentation.

Upstream PR: https://github.com/mdn/content/pull/30466

### CODE REVIEW

**Review by SphinxKnight — APPROVED** [review]
Thanks @queengooborg, as an exception, since this is quite transparent for every locale, I'm going to merge this one

**Comment by SphinxKnight** [comment]
Aaand just saw https://github.com/mdn/content/pull/30466#discussion_r1402948444. I guess we'll follow up with a new PR if necessary

**Comment by queengooborg** [comment]
Looks like no follow-up is needed; the page affected by that comment has not yet been localized!

**Comment by SphinxKnight** [comment]
> Looks like no follow-up is needed; the page affected by that comment has not yet been localized!

Lol, good news for once :)

**Pull request merged**
