### PR TITLE
zh-cn/web/api clear unnecessary metadata

### PR DESCRIPTION
**Pull request by fwqaaq**

### CODE REVIEW

**Review by yin1999 — CHANGES_REQUESTED** [review]
Please check PR test error

**Comment by Jack-Zhang-1314** [comment]
```
error: The document's slug () doesn't match its disk folder name (zh-cn/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces)
```

**Comment by Jack-Zhang-1314** [comment]
```
slug: >-
  Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces
tags:
  - DOM
translation_of: >-
  Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces
```

how to correct it

**Comment by yin1999** [comment]
> ```
> slug: >-
>   Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces
> tags:
>   - DOM
> translation_of: >-
>   Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces
> ```
> 
> how to correct it

```yaml
slug: >-
  Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces
```

**Review by yin1999 — APPROVED** [review]

**Pull request merged**
