### PR TITLE
update glossary of character_encoding translate for zh-cn

### PR DESCRIPTION
**Pull request by buuug7**
update glossary of character_encoding translate for zh-cn

### CODE REVIEW

**Review by irvin — CHANGES_REQUESTED** [review]
@buuug7 與線上的版本有衝突，可以協助 rebase 嗎？感謝。

**Review by irvin — APPROVED** [review]

**Review by irvin — CHANGES_REQUESTED** [review]
與線上的版本仍然有衝突。

**Comment by buuug7** [comment]
the file path is changed from `files/zh-cn/glossary/字符编码/index.html` to `files/zh-cn/glossary/character_encoding/index.html`, the PR will be closed and make a new PR

**Comment by buuug7** [comment]
@irvin the new  #2620 is submitted and this pr will be closed.

**Pull request closed without merging**
