### PR TITLE
fix the EmbedGHLiveSample in 3D WebGL tutorials

### LINKED ISSUE #11623: webGL教程中的演示页地址错误
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL

### 与此议题相关的小节或标题？

Creating 3D objects using WebGL

### 哪些信息是错误、无用或不完善的？

image

点击查看全部源代码 跳转到的github地址为  https://github.com/mdn/webgl-examples/tree/main/tutorial/sample5  ， 这个库应该是被修改了，正确的地址应为  https://github.com/mdn/webgl-examples/tree/main/webgl-examples/tutorial/sample5

### 你期望看到什么？

webGL渲染立方体的演示地址正常显示

image

### 你有什么支持的链接、参考或引用？

其他的教程页演示用的github地址也需要修改

### 你还想补充什么内容？

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/webgl_api/tutorial/creating_3d_objects_using_webgl`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/webgl_api/tutorial/creating_3d_objects_using_webgl/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b5b4590e12242feaf7ef337171bfb2ef6a68dc35
* Document last modified: 2022-12-08T14:07:47.000Z

</details>

### PR DESCRIPTION
**Pull request by yin1999**
### Description

update broken links to fix livesamples.

### Related issues and pull requests

Fixes: #11623

### CODE REVIEW

**Review by saionaro — APPROVED** [review]
LGTM, thank you!

**Review by SphinxKnight — APPROVED** [review]
LGTM for @mdn/yari-content-fr , thanks @yin1999 :)

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`. Thanks!

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es`, thank you!

**Review by yin1999 — COMMENTED** [review]
Thank you all. I'm going to merge this:)

**Pull request merged**
