### PR TITLE
Fix Reflect.construct description (fr)

### PR DESCRIPTION
**Pull request by targos**
The second parameter is not optional.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
quick note: this PR touches JS files which are pending conversion on https://github.com/mdn/translated-content/pull/1835

**Comment by targos** [comment]
I can update this PR after https://github.com/mdn/translated-content/pull/1835 is merged, if that's easier for you.

**Comment by SphinxKnight** [comment]
@targos thanks a lot for the proposal :) I'd gladly accept if that's not too much of a burden for you.
I hope #1835 to be merged in the coming days now that other related PRs are approaching closure :)

**Comment by SphinxKnight** [comment]
@targos the whole migration has now been merged. Let me know if you need help with this one :)

**Comment by targos** [comment]
updated :)

**Pull request merged**
