### PR TITLE
Remove last `{{draft}}` occurrences from localized content

### PR DESCRIPTION
**Pull request by SphinxKnight**
Should help with https://github.com/mdn/translated-content/issues/5599 and https://github.com/mdn/yari/pull/4943

See also https://github.com/mdn/translated-content/pull/3085

### CODE REVIEW

**Review by JuanVqz — APPROVED** [review]
ready to go, related ES files.
Thank you!

**Review by josielrocha — APPROVED** [review]
pt-BR LGTM ;)

**Review by hochan222 — APPROVED** [review]
ko-locale LGTM :)

**Comment by SphinxKnight** [comment]
@mdn/yari-content-ru could you please have a quick look? I think I'll wait a week or two before merging this one.

**Review by queengooborg — APPROVED** [review]
The removal of this macro is LGTM!

**Pull request merged**
