### PR TITLE
fix(tr): wrong closing tag

### LINKED ISSUE #1604: Issue with "<tr> : l'élément de ligne d'un tableau": wrong closing tags
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/tr

#### What information was incorrect, unhelpful, or incomplete?

Code example uses wrong closing html tags (`</td>` instead of `</th>`). That's the case for most of the code example on the page

#### Specific section or headline?

```
<th>Margaret Nguyen</td>
(...)
<th>Edvard Galinski</td>
(...)
<th>Hoshi Nakamura</td>
```

#### What did you expect to see?

```
<th>Margaret Nguyen</th>
(...)
<th>Edvard Galinski</th>
(...)
<th>Hoshi Nakamura</th>
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/html/element/tr`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/tr
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/tr/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a202cd53d99359a85256c72dceb5c05d0f270f48
* Document last modified: 2021-07-16T00:36:29.000Z

</details>

### PR DESCRIPTION
**Pull request by mattlavio**
This PR fixes https://github.com/mdn/translated-content/issues/1604 by updating some erroned closing tags in the `tr` content page. The issue was initially reported in French, but the issue was also present in the japan version of the content too

### CODE REVIEW

**Review by SphinxKnight — APPROVED** [review]
OK for fr

**Comment by SphinxKnight** [comment]
@m4thieulavoie I pushed a few commits to update the page as well and remove "macros" in the French page. I'll let the Japanese team review this.
I think it would be better to make a distinct PR for each locale (though I don't think it's a blocker for this one).

**Comment by SphinxKnight** [comment]
@mdn/yari-content-ja hello :) could you have a look at https://github.com/mdn/translated-content/pull/1696/files#diff-56c3ee37297a0592168601a0d048d839466781aa45d5c70a329945b03dab8ea7 for this PR? This is a minor change to the content (markup fix) and I could merge as is but I prefer having your go :)

**Review by mfuji09 — APPROVED** [review]
I approve it for ja translation.

**Pull request merged**
