### PR TITLE
fix fixable flaws in ko/docs/Web/JavaScript/data_structures

### PR DESCRIPTION
**Pull request by peterbe**
Wanted to test https://github.com/mdn/yari/issues/4323

### CODE REVIEW

**Comment by hochan222** [comment]
- https://github.com/mdn/translated-content/pull/1698

Thank you for your help. Regarding the contents, I will close it by reflecting it in the above PR. From now on, I will record the log. 

Have a nice day :)

**Comment by peterbe** [comment]
>     * [[ko] convert html to markdown (1) /web/javascript #1698](https://github.com/mdn/translated-content/pull/1698)
> 
> 
> Thank you for your help. Regarding the contents, I will close it by reflecting it in the above PR. From now on, I will record the log.
> 
> Have a nice day :)

When I pressed "Fix flaws", it was when the file was a `index.HTML`. Perhaps you were getting errors after you had already converted it to `index.MD`?
Either way, keep an eye out on the terminal for stacktraces from Node.

**Comment by hochan222** [comment]
I reproduced it. you're right. If you do fix flaw while it is an .md file, you will get that error. I already converted it to `index.MD`. If so, should I reopen that issue?

**Comment by peterbe** [comment]
https://github.com/mdn/yari/blob/186b3e1244391e828609646d891756938b4b3802/build/flaws/index.js#L85 
:(

The conversion to Markdown wasn't easy. But they managed to at least build the code so that flaws can be noticed/logged in Markdown content. 

I think we can at least remove the "Fix fixable flaws" button for now.

**Comment by hochan222** [comment]
> I think we can at least remove the "Fix fixable flaws" button for now.

Can you leave the "Fix fixable flaws" button as it is? Because it really saves a lot of work. For the Korean locale, a minimum of 10 flaws and a maximum of 60 flaws can be resolved per page. The average is about 20.

It's for developers, not for production, so wouldn't it be okay if there was a related notice?

**Pull request closed without merging**
