### PR TITLE
Remove the notranslate class which still exists in mdn/translated-content (es)

### LINKED ISSUE #3437: Remove the notranslate class which still exists in mdn/translated-content (es)
Reading [this discussion](https://github.com/mdn/translated-content/discussions/3370) about unfreezing the Spanish content

I went through this [example](https://github.com/mdn/translated-content/discussions/2474) and I started covering the pre-requirements to convert Spanish content to markdown.

I just tackle step 1 section tree `You may also remove the notranslate class which still exists in mdn/translated-content` on this PR #3414 

Should I do something else before my PR will be accepted?
Do you have any suggestions?

Happy Christmas Day you all!

### PR DESCRIPTION
**Pull request by JuanVqz**
As @rumyra pointed up,
I'm following this [guide to make the (es) update easier.](https://github.com/mdn/translated-content/discussions/2474)

- [x] You may also remove the notranslate class which still exists in mdn/translated-content

[Discussion's link](https://github.com/mdn/translated-content/discussions/3370)

Closes #3437

### CODE REVIEW

**Comment by sergiogval** [comment]
Hi, @JuanVqz! 

Reading this, it seems that we,  as CR s, will apply the algorithm to all incoming PRs that aren't a .md file yet, am I right? 
Or we will ask to the contributor to do the changes themselves? 

If the first tough is correct, I believe the best is to create a parser script to avoid manual work and therefore errors in the output. 
Let me know what you think.

Regards.

**Comment by SphinxKnight** [comment]
If I may, you have two options there: 
- convert all the files at once so that later on, all PRs will apply on Markdown
- convert progressively (possibly based on contributions/PRs)

When I look at the scope of the files in this PR, I'd think the first approach is taken.

**Comment by sergiogval** [comment]
@SphinxKnight sounds good. we have around 200 PR, It will be faster if we convert them on batch.

**Comment by SphinxKnight** [comment]
@sergiogval alright, I hadn't realize the deal with already existing PR, in this case, my opinion would be to start with those (they most probably are using HTML) before tackling the conversion process

**Comment by sergiogval** [comment]
divide and conquer, then? @SphinxKnight @JuanVqz

**Comment by sergiogval** [comment]
@JuanVqz I think that the best approach is to divide the PR, refactoring if possible and then merge them. Otherwise it will be double work. Also I think that we should add a readme with clear instructions for the PR from now on.

**Comment by sergiogval** [comment]
@JuanVqz @SphinxKnight I had a BIG mistake. The real number are 13PR and 20 Issues with the label corresponding to spanish.

**Comment by sergiogval** [comment]
So, each one of us can take , lets say... 7 tasks, solve them quickly and be up to date and ready for the new ones. @mdn/yari-content-es

**Comment by JuanVqz** [comment]
> So, each one of us can take , lets say... 7 tasks, solve them quickly and be up to date and ready for the new ones. @mdn/yari-content-es

Okay, I'll start it, right now, thank you!

**Comment by JuanVqz** [comment]
> If I may, you have two options there:
> 
> * convert all the files at once so that later on, all PRs will apply on Markdown
> * convert progressively (possibly based on contributions/PRs)
> 
> When I look at the scope of the files in this PR, I'd think the first approach is taken.

@SphinxKnight I was following this [discussion](https://github.com/mdn/translated-content/discussions/2474) in order to clean the Spanish documentation up but seeing your comment here I think we can take another approach, (which is just convert all the HTML files to Markdown files at once).

What did you do in the past for another documentation?
Which one do you recommend?
Thank you!

**Comment by SphinxKnight** [comment]
> What did you do in the past for another documentation?
> Which one do you recommend?

@JuanVqz for the French part, I worked "section" by section (i.e. converting Web/JavaScript, then Web/CSS, etc) This can be seen in the meta issue https://github.com/mdn/translated-content/issues/3012 
I took this approach and would recommend it so that PR "construction" and review can be as "digestible" as possible but so that we can have complete markdown coverage in a timely manner.

On the other hand, if I'm not mistaken, @mfuji09 is converting pages progressively for ja. Since HTML will keep being supported (at least for a while), that's a far easier approach in regards to PR reviews. 

Also, keep in mind that in the end it doesn't really matter to have MD or HTML stored content, the most important (and difficult) part is to have up to date (or at least non-obsolete) content (in other words, it's clearly subpar to have an old doc which is converted in MD rather than an up-to-date doc in HTML).

**Pull request closed without merging**
