### PR TITLE
fix a bug

### PR DESCRIPTION
**Pull request by silence1018**
Compared with the English version of the document, the Chinese version of the document has one less period here

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
Thanks @silence1018. Welcome aboard :)

**Comment by silence1018** [comment]
我什么时候能在MDN看到这个bug修改后的页面

**Comment by yin1999** [comment]
The updated content would be deployed every 24 hours. See: https://developer.mozilla.org/zh-CN/docs/MDN/Community/Pull_requests

> 查看已发布更改：`mdn/content`（本地化内容则是 `mdn/translated-content`）更改的内容将在合并后的一天内通过每 24 小时一次的网站重新构建发布。

**Comment by silence1018** [comment]
好的  谢谢

**Pull request merged**
