### PR TITLE
remove `Tools` section from `ja`

### LINKED ISSUE #4822: `Firefox Developer Tools docs` is removed from `mdn/content`
## What is the problem?

`Firefox Developer Tools docs` in `en-US` is now redirected to [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) by mdn/content#14140

Should we follow this changes in this repo?

### PR DESCRIPTION
**Pull request by yin1999**
Fixes #4822. (As the last part of it)

Removed by running go script [here](https://github.com/mdn/translated-content/issues/4822#issuecomment-1079841949)

### CODE REVIEW

**Comment by cw118** [comment]
@mdn/yari-content-ja could someone take a look at this please? The main file to review is `_redirects.txt` :)

**Comment by mfuji09** [comment]
This PR seems to make Japanese pages redirects to documentation in English
Where is an internationalized version?

**Comment by yin1999** [comment]
I can only find the english version there.

**Comment by cw118** [comment]
A priori the "new" devtools docs are only available in English, unfortunately :/ So (for now?) we're redirecting all translated-content Tools pages to the Firefox Devtools docs in English.

I haven't quite had time to look into localization of the devtools docs, but the page [Contribute code to Firefox](https://firefox-source-docs.mozilla.org/setup/contributing_code.html#how-to-contribute-code-to-firefox) there might mention/lead to something (cf. https://github.com/mdn/content/discussions/15288 for the brief discussion).

**Comment by mfuji09** [comment]
`Tools` has been moved to https://github.com/mozilla-japan/mdn-devtools-user by https://github.com/mozilla-japan/translation/issues/609 .
So, we can delete it safe.

**Review by mfuji09 — APPROVED** [review]
It is ready to delete them.

**Pull request merged**
