### PR TITLE
Fixes translation error

### LINKED ISSUE #468: Issue with "runtime.onStartup": incorrect French translation
MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onStartup

#### What information was incorrect, unhelpful, or incomplete?

On the French version, it is written "Lancé lorsqu'un premier profil a cette extension installée."
It is not a correct translation of the English version "Fired when a profile that has this extension installed first starts up."

#### What did you expect to see?

"Lancé quand un profil ayant cette extension installée démarre une session."

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/mozilla/add-ons/webextensions/api/runtime/onstartup`
* MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onStartup
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/mozilla/add-ons/webextensions/api/runtime/onstartup/index.html
* Last commit: https://github.com/mdn/translated-content/commit/61fca3157b624a64c3ba9a65348cc55bc6b5ce73
* Document last modified: 2021-04-08T17:56:48.000Z

</details>

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Fixes https://github.com/mdn/content/issues/3984

### CODE REVIEW

**Review by tristantheb — CHANGES_REQUESTED** [review]
Hello @CreaTorAlexander,

Thank you for this translation correction!
I notice further down the lines a mix up in the translation:
https://github.com/CreaTorAlexander/translated-content/blob/35b3db10291b640b6d91fe28be6c74fc48ee9dd8/files/fr/mozilla/add-ons/webextensions/api/runtime/onstartup/index.html#L29-L36

One change that should be added is to replace the following line as follows:
```diff
- <dd>Arrêtez d'écouter cet événement. L'argument <code>listener</code> est l'écouteur à supprimer.</dd>
+ <dd>Arrête d'écouter cet événement. L'argument <code>listener</code> est l'écouteur à supprimer.</dd>
```
This way the translation is identical for all three descriptive lines.

A few lines further on too:
https://github.com/CreaTorAlexander/translated-content/blob/35b3db10291b640b6d91fe28be6c74fc48ee9dd8/files/fr/mozilla/add-ons/webextensions/api/runtime/onstartup/index.html#L45

```diff
! <p>Une fonction qui sera appelée lorsque cet événemetn se produit.</p>
```
I notice that the word "event" is not spelled correctly.

The two blocks in `class="hidden"` can be removed ^^

Is it ok for you in terms of changes to add? 😃

**Comment by CreaTorAlexander** [comment]
@tristantheb I have to mention that I don't speak french. 😄

**Comment by tristantheb** [comment]
It's translated 😃

**Comment by CreaTorAlexander** [comment]
@tristantheb What do you mean by blocks in class="hidden"?

How should *événement* spelled correctly? My translator said that the spelling is fine.

**Comment by tristantheb** [comment]
For `événement`, it's the the of the word : `metn` => `ment` ;)
```diff
- <p>Une fonction qui sera appelée lorsque cet événemetn se produit.</p>
+ <p>Une fonction qui sera appelée lorsque cet événement se produit.</p>
```

**Comment by CreaTorAlexander** [comment]
@tristantheb, oh didn't see it actually 😄

**Review by tristantheb — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
