### PR TITLE
chore(ci): bump prettier to v3.0.2 and re-format documents

### PR DESCRIPTION
**Pull request by yin1999**
### Description

bump prettier to v3.0.2 and re-format documents

### Motivation

[Breaking changes in v3.0.3](https://github.com/prettier/prettier/blob/main/CHANGELOG.md#302).

### Related issues and pull requests

Follow: mdn/content#28648.

### CODE REVIEW

**Review by jasonren0403 — APPROVED** [review]
LGTM for all(they are just code block changes) 👍 

BTW, I see reviewdog still suggesting old-version corrections, will they be resolved after prettier update?

**Comment by yin1999** [comment]
> BTW, I see reviewdog still suggesting old-version corrections, will they be resolved after prettier update?

Yes. The "Lint and review content files" workflow would use the "main" version of "package.json".

**Review by queengooborg — APPROVED** [review]
Thanks, all changes look good!

**Review by Graywolf9 — COMMENTED** [review]
👍

**Pull request merged**
