### PR TITLE
chore: fix url locales

### PR DESCRIPTION
**Pull request by yin1999**
### Description

fix url locales

### CODE REVIEW

**Review by jasonren0403 — APPROVED** [review]
LGTM for l10n-zh 👍

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`. Thank you, @yin1999 !

**Review by hochan222 — APPROVED** [review]
LGTM for `ko locale`. Thank you :)

**Comment by hochan222** [comment]
Since the review appears to be complete, I will merge it. Have a nice weekend everyone :)

**Pull request merged**
