### PR TITLE
Add French translation for :playing reference

### PR DESCRIPTION
**Pull request by audrasjb**

### CODE REVIEW

**Comment by audrasjb** [comment]
Oops there's an issue with a /ja/ redirect file…

**Comment by SphinxKnight** [comment]
@audrasjb : there is a problem in the history of this PR which touches a Japanese file without any reason (as far as I understand), could we see together to fix this history issue?

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
cf. comment

**Comment by audrasjb** [comment]
issue fixed @SphinxKnight :)

**Review by SphinxKnight — APPROVED** [review]
Merci @audrasjb :)

**Pull request merged**
