### PR TITLE
ko: Format /web/api using Prettier (part 1)

### PR DESCRIPTION
**Pull request by queengooborg**
This PR formats the `/web/api` of the Korean locale using Prettier.  This is the first part.

### CODE REVIEW

**Comment by hochan222** [comment]
@queengooborg Hello!

I'm planning to write a guide for Korean contributors to run the checker before contributing. (Which ones should I add?)

I wonder if you plan to provide guidance in the future with an English version or force git actions.

**Comment by queengooborg** [comment]
Husky will help with linting locally, and then soon, I'll be porting over the workflows used in upstream content to enforce Prettier styling and the likes!

**Comment by queengooborg** [comment]
(Oh P.S., please feel free to ignore the build failure -- it's failing due to an existing issue unrelated to these changes!)

**Review by hochan222 — APPROVED** [review]
LGTM :)

**Pull request merged**
