### PR TITLE
Remove unwanted macros from French

### LINKED ISSUE #4593: Unwanted macros in French content
As part of #4579, these macros should be removed from French pages:

<details>
<summary><code>gecko_minversion_header</code> (30 results in 30 files)</summary>

- [ ] conflicting/learn/html/multimedia_and_embedding/video_and_audio_content_040b1c36f4218ba488ffb0284dfe52bf/index.html
- [ ] conflicting/web/javascript/reference/lexical_grammar/index.html
- [ ] mozilla/firefox/releases/3/full_page_zoom/index.md
- [ ] orphaned/web/api/parentnode/firstelementchild/index.html
- [ ] web/api/document/enablestylesheetsforset/index.md
- [ ] web/api/document/laststylesheetset/index.md
- [ ] web/api/document/mozsetimageelement/index.md
- [ ] web/api/document/preferredstylesheetset/index.md
- [ ] web/api/document/readystate/index.md
- [ ] web/api/document/releasecapture/index.md
- [ ] web/api/document/selectedstylesheetset/index.md
- [ ] web/api/document/stylesheetsets/index.md
- [ ] web/api/document_object_model/locating_dom_elements_using_selectors/index.md
- [ ] web/api/element/setcapture/index.md
- [ ] web/api/filelist/index.md
- [ ] web/api/history_api/index.md
- [ ] web/api/timeranges/index.md
- [ ] web/api/window/mozinnerscreenx/index.md
- [ ] web/api/window/mozinnerscreeny/index.md
- [ ] web/api/window/mozpaintcount/index.md
- [ ] web/api/windoweventhandlers/onpopstate/index.md
- [ ] web/css/\_colon\_-moz-broken/index.md
- [ ] web/css/\_colon\_-moz-handler-blocked/index.md
- [ ] web/css/\_colon\_-moz-handler-crashed/index.md
- [ ] web/css/\_colon\_-moz-handler-disabled/index.md
- [ ] web/css/\_colon\_-moz-loading/index.md
- [ ] web/css/\_colon\_-moz-locale-dir(ltr)/index.md
- [ ] web/css/\_colon\_-moz-locale-dir(rtl)/index.md
- [ ] web/css/\_colon\_-moz-suppressed/index.md
- [ ] web/css/\_colon\_-moz-user-disabled/index.md

</details>

<details>
<summary><code>gecko_minversion_inline</code> (51 results in 18 files)</summary>

- [ ] conflicting/learn/html/multimedia_and_embedding/video_and_audio_content_040b1c36f4218ba488ffb0284dfe52bf/index.html
- [ ] conflicting/web/api/element/namespaceuri/index.html
- [ ] web/api/attr/namespaceuri/index.md
- [ ] web/api/canvasrenderingcontext2d/index.md
- [ ] web/api/document/index.md
- [ ] web/api/element/namespaceuri/index.md
- [ ] web/api/file/index.md
- [ ] web/api/filereader/index.md
- [ ] web/api/globaleventhandlers/onerror/index.md
- [ ] web/api/history/index.md
- [ ] web/api/mouseevent/index.md
- [ ] web/api/node/index.md
- [ ] web/api/window/index.md
- [ ] web/api/windoweventhandlers/onhashchange/index.md
- [ ] web/api/xmlhttprequest/index.md
- [ ] web/api/xmlhttprequest/response/index.md
- [ ] web/api/xmlhttprequest/xmlhttprequest/index.md
- [ ] web/mathml/attribute/index.md

</details>

<details>
<summary><code>IncludeSubnav</code> (53 results in 53 files)</summary>

- [ ] conflicting/games/index.md
- [ ] conflicting/learn/css/first_steps/how_css_works/index.html
- [ ] conflicting/learn/css/styling_text/fundamentals_9e7ba587262abbb02304cbc099c1f0d8/index.html
- [ ] games/anatomy/index.md
- [ ] games/examples/index.md
- [ ] games/introduction/index.md
- [ ] games/introduction_to_html5_game_development/index.md
- [ ] games/techniques/index.md
- [ ] games/techniques/2d_collision_detection/index.md
- [ ] games/techniques/3d_on_the_web/index.md
- [ ] games/techniques/3d_on_the_web/basic_theory/index.md
- [ ] games/techniques/audio_for_web_games/index.md
- [ ] games/tools/index.md
- [ ] games/tools/asm.js/index.md
- [ ] games/tutorials/index.md
- [ ] games/tutorials/2d_breakout_game_phaser/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/build_the_brick_field/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/collision_detection/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/create_the_canvas_and_draw_on_it/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/game_over/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/move_the_ball/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/paddle_and_keyboard_controls/index.md
- [ ] games/tutorials/2d_breakout_game_pure_javascript/track_the_score_and_win/index.md
- [ ] games/tutorials/html5_gamedev_phaser_device_orientation/index.md
- [ ] learn/common_questions/available_text_editors/index.md
- [ ] learn/common_questions/common_web_layouts/index.md
- [ ] learn/common_questions/design_for_all_types_of_users/index.md
- [ ] learn/common_questions/thinking_before_coding/index.md
- [ ] learn/common_questions/what_are_browser_developer_tools/index.md
- [ ] mdn/contribute/howto/index.md
- [ ] mdn/structures/index.md
- [ ] mdn/tools/index.md
- [ ] mdn/yari/index.md
- [ ] web/api/canvas_api/index.md
- [ ] web/api/webgl_api/by_example/index.md
- [ ] web/api/webgl_api/by_example/basic_scissoring/index.md
- [ ] web/api/webgl_api/by_example/boilerplate_1/index.md
- [ ] web/api/webgl_api/by_example/canvas_size_and_webgl/index.md
- [ ] web/api/webgl_api/by_example/clearing_by_clicking/index.md
- [ ] web/api/webgl_api/by_example/clearing_with_colors/index.md
- [ ] web/api/webgl_api/by_example/color_masking/index.md
- [ ] web/api/webgl_api/by_example/detect_webgl/index.md
- [ ] web/api/webgl_api/by_example/hello_glsl/index.md
- [ ] web/api/webgl_api/by_example/hello_vertex_attributes/index.md
- [ ] web/api/webgl_api/by_example/raining_rectangles/index.md
- [ ] web/api/webgl_api/by_example/scissor_animation/index.md
- [ ] web/api/webgl_api/by_example/simple_color_animation/index.md
- [ ] web/api/webgl_api/by_example/textures_from_code/index.md
- [ ] web/api/webgl_api/by_example/video_textures/index.md

</details>

<details>
<summary><code>languages</code> (26 results in 25 files)</summary>

- [ ] conflicting/learn/css/building_blocks/index.html
- [ ] conflicting/learn/css/styling_text/fundamentals_8249b1bf53d09b06ed51f43697880b5b/index.html
- [ ] conflicting/learn/html/multimedia_and_embedding/video_and_audio_content_040b1c36f4218ba488ffb0284dfe52bf/index.html
- [ ] conflicting/web/api/canvas_api/tutorial/index.html
- [ ] conflicting/web/api/document_object_model_03f6e13c52ad7c539d9b4c33c51ac4a3/index.html
- [ ] conflicting/web/api/web_storage_api/index.html
- [ ] conflicting/web/api/xsltprocessor_197eea6e529b0a946d29ce7cc292e7ef/index.html
- [ ] conflicting/web/css/index.html
- [ ] conflicting/web/css/border-collapse/index.html
- [ ] conflicting/web/css/color_value/index.html
- [ ] conflicting/web/css/font-variant/index.html
- [ ] conflicting/web/css/pseudo-classes/index.html
- [ ] conflicting/web/guide/index.html
- [ ] conflicting/web/guide/events/creating_and_triggering_events/index.html
- [ ] conflicting/web/http/basics_of_http/mime_types/index.html
- [ ] conflicting/web/javascript/reference/global_objects/object/tosource/index.html
- [ ] conflicting/web/javascript/reference/lexical_grammar/index.html
- [ ] conflicting/web/xpath/introduction_to_using_xpath_in_javascript/index.html
- [ ] orphaned/web/api/elementcssinlinestyle/style/index.html
- [ ] orphaned/web/api/navigatoronline/online_and_offline_events/index.html
- [ ] web/accessibility/keyboard-navigable_javascript_widgets/index.md
- [ ] web/exslt/index.md
- [ ] web/exslt/exsl/node-set/index.md
- [ ] web/svg/tutorial/clipping_and_masking/index.md
- [ ] web/svg/tutorial/positions/index.md

</details>

### PR DESCRIPTION
**Pull request by cw118**
Fixes #4593 ~(should `conflicting` and `orphaned` be removed from this?)~

### CODE REVIEW

**Comment by SphinxKnight** [comment]
There is a CI build error for a `conflicting` file a priori.

The easy solution seem to be to remove those folders from this PR.

N.B. Whatever, I need to get my head around about the best strategies to deal with `orphaned` and `conflicting`, that's another topic.

**Comment by cw118** [comment]
I'll remove them tonight 👍 

Let me know how I can help with orphaned and conflicting, I'm not 100% sure how they should be treated

**Comment by SphinxKnight** [comment]
@cw118 sorry for the conflicts 👉 👈

**Review by SphinxKnight — APPROVED** [review]
:rocket:

**Pull request merged**
