### PR TITLE
"Truthy" 0n value in Chinese version

### LINKED ISSUE #3180: Issue with "Truthy": (short summary here please)
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Truthy

#### What information was incorrect, unhelpful, or incomplete?
‘在 JavaScript 中，truthy（真值）指的是在布尔值上下文中，转换后的值为真的值。所有值都是真值，除非它们被定义为 假值（即除 false、0、""、null、undefined 和 NaN 以外皆为真值）。’
In the Chinese version of MDN, 0n is recognized as true by definition, but Boolean (0n) should be false.
I see that the English version has been corrected, but the Chinese version has not been updated.
#### What did you expect to see?
‘在 JavaScript 中，truthy（真值）指的是在布尔值上下文中，转换后的值为真的值。所有值都是真值，除非它们被定义为 假值（即除 false、0、""、null、undefined 、0N和 NaN 以外皆为真值）。’

#### Did you test this? If so, how?
 Boolean (0n) is false.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/truthy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Truthy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/truthy/index.md
* Last commit: https://github.com/mdn/content/commit/2b5f34043f1c60cb5d13eeee8609cac00bea1873
* Document last modified: 2021-10-29T16:31:10.000Z

</details>

### PR DESCRIPTION
**Pull request by rohini-ranjanR**
### Description

Making some change in Chinese version of MDN, where 0n is recognized as true by definition, but Boolean (0n) should be false. 
### Related issues and pull requests
Fixes #3180

### CODE REVIEW

**Review by yin1999 — CHANGES_REQUESTED** [review]
Hi @rohini-ranjanR, could you pure the main branch?

There are some unrelated files in this PR.

**Comment by yin1999** [comment]
If you need any help on this. Feel free to poke me.

**Comment by rohini-ranjanR** [comment]
Hello @yin1999
Those files are related to other issues but it is mentioned in this PR I commit [036e5e1](https://github.com/mdn/translated-content/pull/11078/commits/036e5e132892f1a5eaee4e55afbe7d983977ece2) and [2e03738](https://github.com/mdn/translated-content/pull/11078/commits/2e03738b58f82c11bc31134d8ad3241e20dc1bf4) the issue is mentioned in commit description.

**Comment by yin1999** [comment]
It seems that we have [added this missing `0n` in this line](https://github.com/mdn/translated-content/blob/d14dd885a3dfbe6ff2a84e03d3ac59276f5be335/files/zh-cn/glossary/truthy/index.md?plain=1#L6). I'm going to close this PR.

For pure the main branch. The easiest way is delete the fork when all the related PRs have been resolved. And then create a new fork. For the future PRs, please always create a new branch to resolve them, instead of modify the main branch directly :)

**Pull request closed without merging**
