### PR TITLE
convert to markdown for web/api/abortcontroller zh-CN

### PR DESCRIPTION
**Pull request by fwqaaq**

### CODE REVIEW

**Comment by yin1999** [comment]
duplicate #6988

**Comment by yin1999** [comment]
markdown convertion guide: <https://github.com/mdn/translated-content/blob/main/docs/zh-cn/h2m-guide.md>

**Comment by Jack-Zhang-1314** [comment]
@yin1999 Commits copy yours, but translation content is Abortcontroller. Beacuse I am testing this yari

**Comment by yin1999** [comment]
> @yin1999 Commits copy yours, but translation content is Abortcontroller. Beacuse I am testing this yari

Thank you, would you mind merging this commit to my pr with a [`Co-authored-by`](https://docs.github.com/cn/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) magic.

**Comment by Jack-Zhang-1314** [comment]
> would you mind merging this commit to my pr with a [Co-authored-by](https://docs.github.com/cn/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) magic.

* Your mind is that you go doing everything?

**Comment by yin1999** [comment]
> * Your mind is that you go doing everything?

I mean:

> but translation content is Abortcontroller

If you want, you can take part in markdown convertion, see #6173 (but, please follow the [guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/h2m-guide.md))

**Comment by Jack-Zhang-1314** [comment]
* I understand what you mean now. So have you done all the pre-transformation work? 
* [Co-authored-by](https://docs.github.com/cn/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) Do you need my email?

**Comment by yin1999** [comment]
> * I understand what you mean now. So have you done all the pre-transformation work?

Still with to tasks:

- replace all unicode space to ascii space
- remove all title in `<a>` tags

> * [Co-authored-by](https://docs.github.com/cn/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) Do you need my email?

No, I can use github no-reply email, I can got that.

So may I go ahead for merging commit?

**Comment by Jack-Zhang-1314** [comment]
Yeah

**Comment by Jack-Zhang-1314** [comment]
* how to distinguish unicode space and ascii space?
* how should I find them?

**Comment by Jack-Zhang-1314** [comment]
unicode space-->U+00a0,  replace them?

**Comment by yin1999** [comment]
I'm using go script to do those tasks:

## remove unicode space:

replace all `\u00A0` and `\u3000` with space ` `. If you are not using go, you can just create a python script to do this.

```go
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

var limit = flag.Int("l", -1, "set limit, -1 means no limit")

var exclude = []string{"conflicting", "orphaned"}

func main() {
	dir := flag.String("d", ".", "set walk dir") // example `-d mdn/translated-content/files/zh-cn` to run jobs on `zh-CN`
	flag.Parse()
	os.Chdir(*dir)
	err := filepath.WalkDir(".", visit)
	if err != nil && err != errLimitReached {
		fmt.Printf("occur an error: %s\n", err.Error())
	}
}

var errLimitReached = errors.New("limit reached")

func visit(path string, d fs.DirEntry, err error) error {
	if d.IsDir() {
		for i := range exclude {
			if strings.HasPrefix(d.Name(), exclude[i]) {
				return filepath.SkipDir
			}
		}
		return nil
	}

	switch filepath.Ext(path) {
	case ".html":
		resolve(path)
	}
	if *limit == 0 {
		return errLimitReached
	}
	return err
}

var (
	space1 = []byte(string([]rune{'\u00A0'}))
	space2 = []byte(string([]rune{'\u3000'}))
)

func resolve(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Printf("[warn] cannot open file, err: %s\n", err.Error())
		return err
	}
	newData := bytes.ReplaceAll(data, space1, []byte{' '})
	newData = bytes.ReplaceAll(newData, space2, []byte{' '})
	if bytes.Equal(data, newData) {
		return nil
	}
	return os.WriteFile(path, newData, 0644)
}
```

**Comment by Jack-Zhang-1314** [comment]
I see

**Comment by yin1999** [comment]
Seems the title it not correct, reopen this one. Please follow the convertion guide.

**Comment by Jack-Zhang-1314** [comment]
I write node to fix unicode space errors, repair so many at a time, I don't know if there is any problem
* <https://github.com/mdn/translated-content/pull/7008/files>

**Comment by Jack-Zhang-1314** [comment]
> Seems the title is not correct, reopen this one. Please follow the convertion guide.

```
---
title: AbortController
---
```
* is it this one? I can't understand what your mind

**Comment by Jack-Zhang-1314** [comment]
Or you can close this pr, I just to test yari

**Comment by yin1999** [comment]
> Or you can close this pr, I just to test yari

I've force push to clear commits

**Pull request merged**
