### PR TITLE
fix cache type graph link

### LINKED ISSUE #885: Issue with "HTTP caching": Error in the shared cache graph
Page: <https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Caching#不同種類的快取>

zh_TW: 

image

en_US:

image

The middle box is incorrectly annotated as "Browser 1" instead of "Shared cache".

### PR DESCRIPTION
**Pull request by btea**
fix #885

### CODE REVIEW

**Comment by btea** [comment]
I visited the Preview URLs, and the picture address was 404. Cannot set picture address as absolute path? Or is it because of the preview?

**Comment by sashasushko** [comment]
Maybe
изображение

**Comment by btea** [comment]
I still failed to preview using relative path. Maybe it's normal in a formal environment.

**Comment by sashasushko** [comment]
@btea do you see it locally?

**Comment by btea** [comment]
@sashasushko I'm sorry. I have some problems with my local environment, so I didn't preview it locally.

**Comment by sashasushko** [comment]
@btea it's ok. I checked your last commit locally. And I see the picture. So, I think you can change absolute URL to relative in all rest files.

**Review by sashasushko — APPROVED** [review]
Approve from @mdn/yari-content-ru

**Review by irvin — APPROVED** [review]

**Review by yujo11 — APPROVED** [review]

**Review by potappo — APPROVED** [review]

**Review by josielrocha — APPROVED** [review]

**Pull request merged**
