### PR TITLE
update(docs-zh): function.bind sync

### PR DESCRIPTION
**Pull request by songhn233**
- remove polyfill and add links to `core-js` implementation

### CODE REVIEW

**Review by mfuji09 — CHANGES_REQUESTED** [review]
Change of Japanese files seems already applied in the repository.
Can you update this branch by merging the latest upstream/main branch into it?

**Comment by irvin** [comment]
please rebase, and suggest to keep one change per MR.

**Comment by songhn233** [comment]
> please rebase, and suggest to keep one change per MR.

I have updated this branch.

**Review by mfuji09 — COMMENTED** [review]
I think it is okay about Japanese files.

**Review by mfuji09 — APPROVED** [review]

**Comment by SphinxKnight** [comment]
What is the intent of this PR regarding /fr/ files?
I'm not sure I understand why this scopes for other locales.

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Awaiting for clarification about fr docs edition.

**Comment by irvin** [comment]
I'm going to close this PR. Please re-submit it without pollute other files that is not related to your work.
這一個 PR 內動到了其他語系不相關的檔案，請整理後再重新提交一次。

**Pull request closed without merging**
