### PR TITLE
Add image files for "Animations basiques"

### LINKED ISSUE #3266: Issue with "Animations basiques": missing images
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations

#### What information was incorrect, unhelpful, or incomplete?
https://yari-demos.prod.mdn.mozit.cloud/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_sun.png
https://yari-demos.prod.mdn.mozit.cloud/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_moon.png
https://yari-demos.prod.mdn.mozit.cloud/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_earth.png

HTTP status code 404

#### Specific section or headline?
https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations#un_syst%C3%A8me_terrestre_anim%C3%A9

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/api/canvas_api/tutorial/basic_animations`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/canvas_api/tutorial/basic_animations/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a81cea7d8b08d1765dcc5ea62e6238dd1d596a05
* Document last modified: 2021-12-03T18:38:15.000Z

</details>

### PR DESCRIPTION
**Pull request by cw118**
Add missing image files for interactive examples in the Canvas API "Animations basiques" page

Fixes #3266

### CODE REVIEW

**Comment by cw118** [comment]
Hello, I've been notified of an error with the PR review companion:
> Unhandled error: Error: No matched build artifacts. Perhaps nothing built in the "PR test" workflow

I'm still quite new to the MDN web docs, especially the translated content, so I'm not sure about how/what to do to fix this issue. I'm also not very familiar with the way embedded live samples work and I have a feeling the changes I'm trying to make are more complex than they seem.

Are there any fixes I can help make or would it be better to close this PR?

**Comment by SphinxKnight** [comment]
hello @cw118 thanks for the fix, I'll look at this on a local environment. Please don't worry too much about the error from PR Companion (follow up on https://github.com/mdn/yari/issues/4972 )

**Comment by SphinxKnight** [comment]
@cw118 Thanks again for this, I've pushed another commit in the doc to remove the "side by side comparaison" which is missing an actual screenshot and, most importantly, is not even in the English doc.
Regarding the "complexity" of this, normally, translated-content resolves assets by fallbacking on mdn/content (e.g. finding an image if it's not in the translated-content tree). *However* this is not true for EmbedLiveSample embedded resources (i.e. assets which are used in scripts in code samples)

**Review by SphinxKnight — APPROVED** [review]
LGTM

**Comment by cw118** [comment]
I see, thank you so much for taking the time to explain!

**Pull request merged**
