### PR TITLE
WebRTC glossary translated

### PR DESCRIPTION
**Pull request by Pacifist-Penguin**
Пожалуйста, обратите внимание на 16 и 24 строку. Не уверен, что так нужно было обозначать аудио и видеочаты, но вопрос оказался слишком спорным

### CODE REVIEW

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Hello @NewPirateOfUASeas, thanks a lot for your contribution with this PR :)
Even though I'm no Russian speaker, I would ask if you could remove the .DS_Store from this PR? 
Let us know if you need help :)

**Comment by NewPirateOfUASeas** [comment]
Hi @SphinxKnight, thanks for your attention. Please, take a look if i did it right.

**Comment by SphinxKnight** [comment]
@NewPirateOfUASeas Yes, that looks good :) Thanks for the swift action.
I'll let @lex111 review the Russian update ^- ^

(@Gregoor seems good to me, I'll let you have a look if needed).

**Review by SphinxKnight — APPROVED** [review]

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@NewPirateOfUASeas thanks!

**Pull request merged**
