### PR TITLE
[ko] handler.defineProperty()

### PR DESCRIPTION
**Pull request by SnowMarble**

### CODE REVIEW

**Review by caugner — CHANGES_REQUESTED** [review]
File is outside of `files` directory, please move it here: `files/ko/web/javascript/reference/global_objects/proxy/proxy/defineproperty/index.md`

**Comment by SnowMarble** [comment]
@caugner I apologize for my mistake. And as you said, I moved the file. Thanks!😸

**Comment by SnowMarble** [comment]
@pje1740  제가 실수로 리뷰를 취소해버린것 같습니다.🥲 확인해주시면 감사하겠습니다..😭

**Review by pje1740 — APPROVED** [review]
확인했습니다! 고생하셨습니다! 😊

**Pull request merged**
