### PR TITLE
Base64 - Correspondance de contenu et correction des examples de code brisé

### PR DESCRIPTION
**Pull request by duboisp**
### Description

Matching the French translation with the current English version. Fixing the broken code sample in French to match the one in English. And removed a few broken links.

### Motivation

These changes will help the reader to understand the code sample and access in French a version equivalent to the English corresponding content.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Merci beaucoup pour cette PR @duboisp et d'avoir repris la version anglaise comme référence ! Je vais regarder tout ça prochainement.

En attendant une revue humaine, il semble que le linter se plaigne d'un blanc en fin de ligne https://github.com/mdn/translated-content/pull/11311/files#diff-44c086c52cb27a7ed3f99d0047b4c545667b9f694fb450534f31d8aa2c62f60eR245

**Comment by duboisp** [comment]
I removed the trailing space and fixed the reported broken links.

**Comment by SphinxKnight** [comment]
@duboisp I've "relocated" the review into https://github.com/duboisp/translated-content/pull/1/files to (I hope) make things easier. Please let me know if you have any question!

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
cf. https://github.com/duboisp/translated-content/pull/1/files

**Review by SphinxKnight — APPROVED** [review]

**Pull request merged**
