### PR TITLE
In line 50 , you write console.table() , i change it to console.log()

### PR DESCRIPTION
**Pull request by Ombre2**

### CODE REVIEW

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Could you please indicate the reasons for this change?

**Comment by SphinxKnight** [comment]
@Ombre2 is there any reason behind this change?

**Comment by Ombre2** [comment]
Hello , i change it because console.table() give an error on the console if
it executed to the browser so the correct sintax is console.log()

Cordialement ,

Ombres

Le mar. 14 juin 2022 22:05, SphinxKnight ***@***.***> a
écrit :

**Comment by SphinxKnight** [comment]
@Ombre2 thanks for the feedback, however the example works in my browser and `console.table()` seems to be fairly well supported: https://developer.mozilla.org/en-US/docs/Web/API/Console/table#browser_compatibility

Could you provide a screenshot of the error and/or some more details?

**Comment by SphinxKnight** [comment]
For example, here's what I get in Firefox:
image

**Comment by SphinxKnight** [comment]
Please let us know if you have details for reopening this PR.

**Pull request closed without merging**
