### PR TITLE
fr: Removes duplicated frontmatter keys (web folder)

### PR DESCRIPTION
**Pull request by Lou8is**
### Description

Removes duplicated frontmatter keys (see #7412) from the **files/fr/web** sub-folder.

Only `title`, `short_title`, `slug` and` l10n.*` are left, essentially removed `tags`, `original_slug`, `browser-compat`, `file-type`.

### Motivation

Help keeping the FR translation nice and up-to-date :)

### Related issues and pull requests

Relates to #7412 
Relates to 6 other PR for the other subfolders (#13629, #13630, #13631, #13632, #13633, #13663)

### CODE REVIEW

**Comment by cw118** [comment]
Sorry for the delay here :/ Even though the changes are simple, there are a lot of files so it will take some time, but I hope to finish the review soon.

**Comment by SphinxKnight** [comment]
@Lou8is sorry for being late to the party as well, just in case you were to work on similar "huge surface changes", I'd advocate to split the work in separate PRs for each subsection of /web.
That being written, let's keep this one. @cw118 I'll review this in the coming days as well to have 2 pairs of eyes.

**Comment by Lou8is** [comment]
> @Lou8is sorry for being late to the party as well, just in case you were to work on similar "huge surface changes", I'd advocate to split the work in separate PRs for each subsection of /web. That being written, let's keep this one. @cw118 I'll review this in the coming days as well to have 2 pairs of eyes.

Yeah my bad on this one, I now understand that /web and /learn are very hyge in comparison to other folders. I'll keep that in mind in the future.

Take all the time your need I'll try to keep it up to date with main if needed.

**Review by SphinxKnight — APPROVED** [review]
OK pour moi. j'ai plutôt joué en local avec `git diff --merge-base main HEAD` puis isolé les ajouts (`grep -E "^\+" log_diff_pr13664.diff > add_diff.txt`) et suppressions (`grep -E "^-" log_diff_pr13664.diff > sub_diff.txt`) pour voir : 
- que rien n'avait été ajouté ✔️ 
- que sur les retraits, on avait bien que des tags et autres met

J'ai aussi vérifié sur le contenu les passages à la ligne avec `>-` et vérifié que les `l10n.sourceCommit` étaient inchangés.

Vu le volume, on attend @cw118 pour la suite :)

**Review by cw118 — APPROVED** [review]
Tout est bon pour moi (je me suis permis de pousser un commit pour supprimer `spec-urls`) :)

Merci à nouveau @Lou8is pour tout le travail ici et merci beaucoup @SphinxKnight pour la revue supplémentaire 🙏 🙏

**Comment by Lou8is** [comment]
Merci à tous les deux !

**Pull request merged**
