### PR TITLE
Add a code example

### PR DESCRIPTION
**Pull request by SnowingFox**
A code example is added to the warning content at the beginning of the article. 

This example can clearly show its meaning.

 Why should I give this example? Because when I first read it, I found it difficult to imagine and understand this concept.

please accept

### CODE REVIEW

**Comment by SnowingFox** [comment]
I'm sorry in last PR, Beacause I wrote Promise.resolve to Promise.then...

**Comment by SnowingFox** [comment]
@t7yang 大佬，能看看这个PR么...

**Comment by t7yang** [comment]
> @t7yang 大佬，能看看这个PR么...

這部分原文沒有，但有一定的價值，是否可以貢獻到英文那邊再進行翻譯？

**Comment by SnowingFox** [comment]
> > @t7yang 大佬，能看看这个PR么...
> 
> 這部分原文沒有，但有一定的價值，是否可以貢獻到英文那邊再進行翻譯？

好的

**Comment by SnowingFox** [comment]
@t7yang
 [英文PR](https://github.com/mdn/content/pull/10347)
[英文PR测试网址](https://pr10347.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

**Review by t7yang — APPROVED** [review]

**Pull request merged**
