### PR TITLE
Web API section to Markdown - French

### PR DESCRIPTION
**Pull request by SphinxKnight**
This is a followup of https://github.com/mdn/translated-content/pull/2464

The conversion report is available [here](https://gist.github.com/SphinxKnight/cefa8bfe7ec332542d86aba29d4a054e)

### CODE REVIEW

**Comment by SphinxKnight** [comment]
### :warning: DO NOT SQUASH MERGE :warning:

**Comment by SphinxKnight** [comment]
Converting this as a draft since I've applied fixes for errors detected in CI afterwards and I'm not sure it's the best course of action.

**Review by tristantheb — APPROVED** [review]
Let's go :D

**Comment by SphinxKnight** [comment]
Conversion report after rebasing the branch after synchronization commits from cron task which introduced conflicts for two moved/removed doc : https://gist.github.com/SphinxKnight/e02571be61ce96af46da97ab939d3dce

**Pull request merged**
