### PR TITLE
de: replace all remaining {{(m)anch}} calls with anchor tags

### PR DESCRIPTION
**Pull request by queengooborg**
This PR is a part of #4614 that removes all remaining calls to the now-deprecated `{{anch}}`  and `{{manch}}` macros and replacing them with anchor tags or Markdown links, using the script from https://github.com/mdn/content/pull/13802.

### CODE REVIEW

**Comment by cw118** [comment]
@queengooborg Thank you so much for this PR :)

However, (I believe) it was decided that we shouldn't remove these macros for frozen locales since they're unmaintained and have no reviewing teams (cf. https://github.com/mdn/translated-content/issues/4614#issuecomment-1067917946). Would it be OK to close this or perhaps further discuss what to do with frozen locales?

**Comment by queengooborg** [comment]
Oh I didn't realize frozen locales were included in this repository!  I'm surprised German is unmaintained though, I thought for sure this is a locale that'd be maintained.

I'm down to close this (and Polish) while awaiting a decision on macro removal in frozen locales.  This was a scripted change that can easily be recreated!

**Comment by cw118** [comment]
Based on https://github.com/mdn/translated-content/issues/4614#issuecomment-1068086240 and https://github.com/mdn/translated-content/issues/4614#issuecomment-1072352920 (my bad for not mentioning these earlier :/), it seems the decision is to *not* update macros in frozen locales, but just to check:

@schalkneethling I hope it's alright to ping you, I was wondering if referencing deleted macros (in frozen locales) will break the build or if it's OK for us to avoid removing deleted macros from unmaintained locales? Thanks in advance :)

**Comment by schalkneethling** [comment]
> Based on [#4614 (comment)](https://github.com/mdn/translated-content/issues/4614#issuecomment-1068086240) and [#4614 (comment)](https://github.com/mdn/translated-content/issues/4614#issuecomment-1072352920) (my bad for not mentioning these earlier :/), it seems the decision is to _not_ update macros in frozen locales, but just to check:
> 
> @schalkneethling I hope it's alright to ping you, I was wondering if referencing deleted macros (in frozen locales) will break the build or if it's OK for us to avoid removing deleted macros from unmaintained locales? Thanks in advance :)

Completely fine to ping me! That is a good question. I have a feeling it will not break the build, but let me make sure.

**Comment by caugner** [comment]
@queengooborg @cw118 Removing usages of deprecated macros from frozen locales is absolutely appreciated. 👍

**Background**: We still build all locales, including _frozen_ ones, every night. This means we can only remove deprecated macros if they are no longer used in any locale, including _frozen_ locales.

**Note**: The locales that we no longer "care" about are elsewhere, e.g. [retired-content](https://github.com/mdn/retired-content) and [retired-archived-content](https://github.com/mdn/retired-archived-content).

**Review by cw118 — APPROVED** [review]
Good to know @caugner, thank you for explaining! I did a quick review and everything seems fine, but I don't speak German so I may have missed some things

*Edit:* is there a (review) process for removing macros from frozen locales since they don't have review teams?

**Comment by caugner** [comment]
> _Edit:_ is there a (review) process for removing macros from frozen locales since they don't have review teams?

Probably there isn't (I would be suprised), but I can cover `de`.

**Review by caugner — APPROVED** [review]

**Pull request merged**
