### PR TITLE
Fix Learn Flexbox image sources

### LINKED ISSUE #3229: Issue with "Flexbox": (short summary here please)
MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox

broken image link: https://developer.mozilla.org/files/3739/flex_terms.png after text "Когда элементы выложены как flex блоки, они располагаются вдоль двух осей"

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/css/css_layout/flexbox`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/css_layout/flexbox/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1adc79897fe49bc407dbd7e71a61c854bc92f347
* Document last modified: 2021-11-28T22:17:21.000Z

</details>

### LINKED ISSUE #3294: Flexbox pages not displaying image
## What is the problem?

It seems that the image **flex_terms.png** isn't displaying on any of the non-English pages on CSS Flexbox (Learn).
Fixing this would also close #3229 for the Russian Flexbox page.

(The French version has a few more issues with images mentioned separately in #3288)

## Specific page section or heading?

The Flex Model (should be the fourth h2 heading of each page). Here are a few examples just to be clear:
- ru: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox#внутри_flex_модели
- ja: https://developer.mozilla.org/ja/docs/Learn/CSS/CSS_layout/Flexbox#an_aside_on_the_flex_model
- ko: https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Flexbox#flex_모델의_측방

### PR DESCRIPTION
**Pull request by cw118**
Fixes image source for image *flex_terms.png* so that it's displayed properly on all translated CSS Flexbox pages, and replaces external image links/sources as well—I've already tested each modified file/page locally to ensure this works. 

**Note: The French page will be fixed with #3330 and was thus not modified here.**

***Edit: There seems to be an issue with the page previews where assets, such as relatively linked/sourced images, aren't displayed properly.*** This is why the modified files may appear broken in the previews rendered, despite working well in a local and/or production environment.

Also fixes #3229 and fixes #3294

### CODE REVIEW

**Review by nathipg — CHANGES_REQUESTED** [review]
Could you please add the images in the pt-br version? It is broken in the [preview](https://pr3331.content.dev.mdn.mozit.cloud/pt-BR/docs/Learn/CSS/CSS_layout/Flexbox)

**Comment by cw118** [comment]
> Could you please add the images in the pt-br version? It is broken in the [preview]

Hello, I'm still quite new to this so I may need a few pointers. What I've noticed is that the images show when I'm viewing the pages locally, but not in the previews provided here—so I'm not really sure how to fix it.

**Comment by sashasushko** [comment]
@cw118 @nathipg yes, there is a problem with assets on stage server. I saw same issue in another pull request

**Review by sashasushko — APPROVED** [review]
Approve from @mdn/yari-content-ru

**Comment by nathipg** [comment]
@cw118 @sashasushko Thank you for letting me know, I wasn't aware of that issue. I've approve this PR now :D

**Review by nathipg — APPROVED** [review]

**Comment by cw118** [comment]
> Thank you for letting me know, I wasn't aware of that issue. I've approve this PR now :D

:) Thanks so much!

**Review by t7yang — APPROVED** [review]

**Review by nathipg — APPROVED** [review]
Approve from @mdn/yari-content-pt-br

**Review by mfuji09 — APPROVED** [review]
I agree about the ja document.

**Review by yujo11 — APPROVED** [review]

**Review by yujo11 — APPROVED** [review]
Approve from @mdn/yari-content-ko

**Comment by cw118** [comment]
Thank you all, would it be possible to merge this PR now that all (active) locales have approved?

**Pull request merged**
