### PR TITLE
convert glossary html to md (4)

### PR DESCRIPTION
**Pull request by hochan222**
- issue: https://github.com/mdn/translated-content/issues/2894
- 단순 변환입니다. (내용 변화 x)
- rebase merge 부탁드립니다.

convert glossary html to md

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@hochan222 if you want you can use the "Markdown conversion" milestone in the metadata for those PR

**Comment by hochan222** [comment]
@SphinxKnight Thank you for telling me :)

We tried to deal with things that can be completed in a short period of time quickly, and then register and manage large-scale learn or web as milestones as an issue.

If you upload a PR to Milestone, it will be complicated to track other issues, so I'm only going to register an issue. What do you think? Any other recommendations?

**Comment by hochan222** [comment]
It is maintained [here](https://github.com/mdn/translated-content/issues/2894), but it seems like a good way to make it in advance for other people in the future.

**Comment by SphinxKnight** [comment]
> @SphinxKnight Thank you for telling me :)
> 
> I tried to deal with things that can be completed in a short period of time quickly, and then register and manage large-scale learn or web as milestones as an issue.
> 
> If I upload a PR to Milestone, I think it will be complicated to track other issues, so I'm only going to register an issue. What do you think? Any other recommendations?

Yes you're right :) I'll remove the PRs I put there. Tracking with a global issue per locale seems the right "balance"

**Comment by hochan222** [comment]
Yes, I understand. I will proceed in the same way. Thank you.🙇

**Comment by queengooborg** [comment]
IMO adding PRs to the milestone is alright, it's up to you all whether to do so!  I personally like the idea of adding these PRs to the milestone since their merge will increase the completion progress of the milestone.  :D

**Review by queengooborg — APPROVED** [review]
In regards to the PR itself, LGTM after a quick skimming of the files!

**Pull request merged**
