### PR TITLE
translate (zh-TW): web/tutorials/index.html

### PR DESCRIPTION
**Pull request by weixiang0815**
新增下列翻譯段落:
- CSS 教學#高級
- JavaScript 教學#初級
- JavaScript 教學#中級
- JavaScript 教學#高級
- JavaScript 教學#擴充功能開發

### CODE REVIEW

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Hello @weixiang0815 thanks for your contribution but your pull request includes files which should not be modified. Could you please fix that? If you need help, let us know.

**Comment by weixiang0815** [comment]
@SphinxKnight, the only page I edited is the one I wrote on the title, and I don't know why there are so many commits being made. This is the first time I ever used Github to make contribution to a project, so there may be some mistake I made; It would be much appreciated if you could guide me how to fix the problem in order to get my PR accepted. Thank you.

**Comment by SphinxKnight** [comment]
@weixiang0815 did you use the editor from GitHub's website or your Git client on your computer?

**Comment by t7yang** [comment]
I'll closed this PR, it affect to many unrelated files.

@weixiang0815 could you please re-submit you works with a new PR.
Please make sure you don't commit with other unrelated files.
If you have any problems working with git/github, you can join our [MozTW L10n Channel](https://moztw.org/community/telegram/) on telegram.

**Pull request closed without merging**
