### PR TITLE
fr: Format /learn using Prettier

### PR DESCRIPTION
**Pull request by queengooborg**
This PR formats the `/learn` folder for the French locale using Prettier.

### CODE REVIEW

**Comment by queengooborg** [comment]
I just checked to see if there would be any merge conflicts between these two PRs, and I am happy to say that there are none!  But regardless, if you'd like to hold off reviewing this PR for now, I'll happily await review at a later date!

(P.S. with the frontmatter keys, I recently added a configuration file for the localized content's frontmatter, so we can start using the frontmatter linter in upstream content as well!)

**Comment by SphinxKnight** [comment]
> I just checked to see if there would be any merge conflicts between these two PRs, and I am happy to say that there are none! But regardless, if you'd like to hold off reviewing this PR for now, I'll happily await review at a later date!

Thanks a lot, I was just thinking out loud, remembering the markdown conversion time when conflicts were unavoidable ^ ^ I should have known better. Thanks for checking :)

**Comment by queengooborg** [comment]
Of course!  I'll say that merge conflicts will probably occur regardless, but it shouldn't be anywhere near as big as the Markdown conversion (since we aren't renaming and completely changing files from the ground up).  I'm thinking that we'll end up with small merge conflicts that should be pretty easy to resolve if the need arises, and by taking it one folder/small batch at a time, it should stay at a minimum!

**Review by SphinxKnight — APPROVED** [review]
Scrolled through the changes and didn't notice anything, let's merge :) 

The EmbedLiveSample error in the test is also in https://github.com/mdn/translated-content/pull/13663 and I think we can bypass it for this one as this PR doesn't touch any EmbedLiveSample call

**Pull request merged**
