### PR TITLE
Remove deprecated Obsolete_Header macro from es

### PR DESCRIPTION
**Pull request by Graywolf9**
### Description

Remove deprecated Obsolete_Header macro from es

Process:

- remove the macro and replace with {{Deprecated_Header}} macro when apply
- remove some conflicting files that contains the macro
- remove an orphaned files that contains the macro

Deleted files:

- conflicting/web/javascript/reference/ ref https://github.com/mdn/content/pull/20257 https://github.com/mdn/content/issues/20040
- conflicting/Web/API/Blob ref https://github.com/mdn/content/pull/20245
- conflicting/Web/API/Element/clientHeight ref https://github.com/mdn/content/pull/20128
- conflicting/web/api/file/name https://github.com/mdn/content/pull/8928
- orphaned/web/api/fileerror https://github.com/mdn/content/pull/8166

### Motivation

The chore of deprecated macros removal

### Related issues and pull requests

Relates to https://github.com/orgs/mdn/discussions/263

### CODE REVIEW

**Comment by JuanVqz** [comment]
@Graywolf9 tienes algunos conflictos, podrias por favor resolverlos? Gracias

**Comment by Graywolf9** [comment]
Gracias! @JuanVqz sí, son por que algún PR intermedio hizo cambios y yo los estoy eliminando, será que con un rebase se soluciona?

**Comment by JuanVqz** [comment]
Si posiblemente, quieres que lo revisemos?

**Comment by Graywolf9** [comment]
Sí, por favor

**Comment by JuanVqz** [comment]
Lo acabo de ver! Te escribo en matrix

**Pull request closed without merging**
