### PR TITLE
[es] Add exponentiation operator page

### PR DESCRIPTION
**Pull request by fedeperin**
### Description
Translated the [exponentiation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation) page to spanish

### CODE REVIEW

**Comment by fedeperin** [comment]
I was checking the page in the preview and saw that in the first description a text is not bold, but it shows the asterisks that should be ignored. 

image

I think that it is because of a wrong correction that the github actions bot did. 

image

Is there any way to ignore the correction?

**Comment by JuanVqz** [comment]
> I was checking the page preview and saw that in the first description a text is not bold, but it shows the asterisks that should be ignored.
> 
> image
> 
> I think that it is because of a wrong correction that the github actions bot did.
> 
> image
> 
> Is there any way to ignore the correction?

You are right! I think we can merge without the suggestion, but if you want to go further please check it in the [workflows](https://github.com/mdn/translated-content/tree/main/.github/workflows) directory and make the needed changes.

**Review by JuanVqz — APPROVED** [review]
@fedeperin thanks for your help translating this page! 

Gracias Fede!

**Comment by fedeperin** [comment]
> > I was checking the page preview and saw that in the first description a text is not bold, but it shows the asterisks that should be ignored.
> > image
> > I think that it is because of a wrong correction that the github actions bot did.
> > image
> > Is there any way to ignore the correction?
> 
> You are right! I think we can merge without the suggestion, but if you want to go further please check it in the [workflows](https://github.com/mdn/translated-content/tree/main/.github/workflows) directory and make the needed changes.

@JuanVqz  Hola! Estuve viendo los workflows y no puede econtrar el error. Voy a abrir una issue referenciando a esta PR pero en el repositorio [content](https://github.com/mdn/content), ya que estuve viendo la página original del [operador de asignación de exponenciación](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation_assignment) en inglés y están teniendo el mismo problema, me parece que viene de ahí. Muchas gracias por el tiempo!
image

**Comment by JuanVqz** [comment]
> > > I was checking the page preview and saw that in the first description a text is not bold, but it shows the asterisks that should be ignored.
> 
> > > image
> 
> > > I think that it is because of a wrong correction that the github actions bot did.
> 
> > > image
> 
> > > Is there any way to ignore the correction?
> 
> > 
> 
> > You are right! I think we can merge without the suggestion, but if you want to go further please check it in the [workflows](https://github.com/mdn/translated-content/tree/main/.github/workflows) directory and make the needed changes.
> 
> 
> 
> @JuanVqz  Hola! Estuve viendo los workflows y no puede econtrar el error. Voy a abrir una issue referenciando a esta PR pero en el repositorio [content](https://github.com/mdn/content), ya que estuve viendo la página original del [operador de asignación de exponenciación](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation_assignment) en inglés y están teniendo el mismo problema, me parece que viene de ahí. Muchas gracias por el tiempo!
> 
> image
> 
> 

@fedeperin Gracias a ti por el tiempo de revistarlo, si viste el mismo comportamiento en el repositorio `content` (donde está la versión en inglés), si te recomendaría reportarlo ahí y una vez lo corrijan, poder copiar la solución a este repositorio. Saludos!

**Pull request merged**
