### PR TITLE
Remove obsolete `Node.isSupported` method

### PR DESCRIPTION
**Pull request by leon-win**
### Description

This PR remove obsolete `Node.isSupported` method from MDN translated content.

### Motivation

It has been removed from en-US locale a long time ago.

### Related issues and pull requests

Relates to https://github.com/mdn/content/pull/22863, #13499

### CODE REVIEW

**Review by cw118 — APPROVED** [review]
Looks good for `l10n-fr`, thank you @leon-win !

(It may be easier/faster to remove all obsolete methods in one locale in each PR, instead of removing one obsolete method for all locales, because only one reviewer would be needed for each PR.)

**Comment by leon-win** [comment]
> Looks good for `l10n-fr`, thank you @leon-win !
> 
> (It may be easier/faster to remove all obsolete methods in one locale in each PR, instead of removing one obsolete method for all locales, because only one reviewer would be needed for each PR.)

@cw118 thank you for reply!

I also wanted to do exactly that at first.
But then I thought that the changes are almost identical for all languages (might say trivial), and therefore one reviewer can look at them all :)
That is, in my opinion, the changes are understandable even without knowledge of a specific language. How do you think?

**Comment by cw118** [comment]
> I also wanted to do exactly that at first. But then I thought that the changes are almost identical for all languages (might say trivial), and therefore one reviewer can look at them all :) That is, in my opinion, the changes are understandable even without knowledge of a specific language. How do you think?

I agree that the changes are very small for all locales, but it happens somewhat often that locales have different conventions and requests, so even for this type of PR we prefer to wait for approval from a reviewer for each locale. Thanks for understanding!

**Comment by leon-win** [comment]
> > I also wanted to do exactly that at first. But then I thought that the changes are almost identical for all languages (might say trivial), and therefore one reviewer can look at them all :) That is, in my opinion, the changes are understandable even without knowledge of a specific language. How do you think?
> 
> I agree that the changes are very small for all locales, but it happens somewhat often that locales have different conventions and requests, so even for this type of PR we prefer to wait for approval from a reviewer for each locale. Thanks for understanding!

I'm understood, thank you!
I actually have already created several more similar PRs :smiling_face_with_tear: 
I am still convinced that bureaucracy can be unnecessary and can hinder progress.
In any case, the amount of time spent will be the same (if we wait for confirmation from all reviewers) -- it doesn’t matter one or several PR's =)

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es`

As @cw118 says, sometimes is better a PR per locale, so the locale can be updated soon, and then you can identify older locales that maybe ended hidden. Other times is good to have a unified change of all locales in a PR, we respect each locale lead so we wait to their review, depends on the change after two weeks someone more of the core team could approve the whole PR

Thank you so much for all your work and time!

**Review by JuanVqz — APPROVED** [review]

**Review by yin1999 — APPROVED** [review]
LGTM for `zh-CN`. Thank you @leon-win

**Review by saionaro — APPROVED** [review]
LGTM for RU

**Comment by leon-win** [comment]
> LGTM for `es`
> 
> As @cw118 says, sometimes is better a PR per locale, so the locale can be updated soon, and then you can identify older locales that maybe ended hidden. Other times is good to have a unified change of all locales in a PR, we respect each locale lead so we wait to their review, depends on the change after two weeks someone more of the core team could approve the whole PR
> 
> Thank you so much for all your work and time!

Thanks for the explanation, @Graywolf9 :hugs: 
I will keep it in mind in the future!

**Review by josielrocha — APPROVED** [review]
Approve for `pt-BR`

**Pull request merged**
