### PR TITLE
[es] remove obsolete `orphaned/Web/API/Canvas_API/A_basic_ray-caster`

### PR DESCRIPTION
**Pull request by leon-win**
### Description

This PR removes obsolete `orphaned/Web/API/Canvas_API/A_basic_ray-caster` page in `es` locale.

### Related issues and pull requests

Relates to https://github.com/mdn/content/pull/17352

### CODE REVIEW

**Review by JuanVqz — APPROVED** [review]
Gracias por contribuir!

**Review by Graywolf9 — CHANGES_REQUESTED** [review]
Thank you so much! It seems to have some mentions too

**Comment by leon-win** [comment]
> Thank you so much! It seems to have some mentions too

Something needs to be improved?

**Comment by JuanVqz** [comment]
> > Thank you so much! It seems to have some mentions too
> 
> Something needs to be improved?

I think what @Graywolf9 means is that there are some pages that still have the `ray-caster` word, I searched for it and found those:

- [ ] ./files/es/web/api/canvas_api/index.md
99:- [Demo: Un laberinto básico](/es/docs/Web/API/Canvas_API/A_basic_ray-caster)

- [ ] ./files/es/web/api/canvas_api/tutorial/basic_animations/index.md
327:- [Un ray-caster básico](/es/docs/Web/API/Canvas_API/A_basic_ray-caster)

**Comment by Graywolf9** [comment]
Yeah, sorry, there are some  mentions to the removed page

**Comment by leon-win** [comment]
> > > Thank you so much! It seems to have some mentions too
> > 
> > 
> > Something needs to be improved?
> 
> I think what @Graywolf9 means is that there are some pages that still have the `ray-caster` word, I searched for it and found those:
> 
>     * [ ]  ./files/es/web/api/canvas_api/index.md
>       99:- [Demo: Un laberinto básico](/es/docs/Web/API/Canvas_API/A_basic_ray-caster)
> 
>     * [ ]  ./files/es/web/api/canvas_api/tutorial/basic_animations/index.md
>       327:- [Un ray-caster básico](/es/docs/Web/API/Canvas_API/A_basic_ray-caster)

Oh, my mistake! I didn't search along the path from the redirects((
Thank you for your attention!

Updated PR :ok_hand:
I removed these links, they are not in the `en-us` version either

**Review by Graywolf9 — APPROVED** [review]
Thank you so much for all your help!

**Pull request merged**
