### PR TITLE
pt-BR: Replaced `{{HTMLRefTable}}` with markdown table

### PR DESCRIPTION
**Pull request by manjuu-eater**
### Description

The `{{HTMLRefTable}}` macro became obsolete, and the entire table content was gone. So, I converted the macros as described below:

1. Get the markdown corresponding to the "Element" cell of each table from the English version
2. Set the markdowns to the "Element" cells in the translated version
3. For each element (=HTML tag), get the first line of the translated version of the page
(specifically, the first line that is not a front-matter, heading, or Lv1 list)
4. Set the retrieved line to the "Description" cell
5. If "Description" cell was empty, fill with en-US description (`{{HTMLRefTable}}` did not seem to have this process)

I am not entirely sure what the `{{HTMLRefTable}}` macro was actually doing.
I assumed it probably did something like the above.
A PR in the Japanese version (#11993) was determined that there was no problem.

I can't understand what the translated text means.
So, I would like the reviewer to do the following tasks:

1. Since I did the conversion semi-mechanically, there may be some strange things in the text. Please check it lightly.
2. Please compare with [WayBackMachine page](http://web.archive.org/web/20230115140446/https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element) and check if there are any significant changes.
3. The chapters that existed in the English version but were not in the translated version ("Sectioning root", "SVG and MathML") have been copied directly from the English version. Please translate them later.

I am writing this English text with using a translator. Sorry if there are parts that are difficult to read.

Thank you in advance.

### Additional details

WayBackMachine page: http://web.archive.org/web/20230115140446/https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element
current page: https://developer.mozilla.org/es/docs/Web/HTML/Element

### Related issues and pull requests

Relates to #11953

### CODE REVIEW

**Comment by manjuu-eater** [comment]
Sorry, but I miss converted about pt-BR.
Description was all English...
Please wait for a while.

**Comment by manjuu-eater** [comment]
Now I converted to pt-BR correctly.
Sorry for mistake.

**Review by josielrocha — APPROVED** [review]
LGTM ;)

**Comment by josielrocha** [comment]
Thank you for your help @manjuu-eater! 🚀

**Pull request merged**
