### PR TITLE
es: Observations from frontmatter lintintg

### PR DESCRIPTION
**Pull request by Graywolf9**
### Description

`original_slug` are a needy frontmatter for fixing `orphaned` and `conflicting` files. I remember that it was an optional frontmatter but we love to keep at least in those folders

### CODE REVIEW

**Review by queengooborg — CHANGES_REQUESTED** [review]
Re-adding `orignal_slug` sounds good to me if it is needed for `conflicting/` and `orphaned/`!  It looks like some other keys were added back, however (ex. `browser-compat`), may we remove those?

**Comment by Graywolf9** [comment]
I remember added some of that in `conflicting` due to the `spec` and `compat` macros, but let me take a look

**Comment by Graywolf9** [comment]
I already checked and in fact, all those files (10) have the `browser-compat` macro to not break `specs` and `compat` sections. If it's possible I would rather keep until I solve and move or delete that files.

**Comment by queengooborg** [comment]
I gotta be honest, keeping those keys will cause an issue with front matter linting when it is introduced.  (The front matter linter doesn't have a file ignore feature, and it would be best not to have to add one in.)

**Comment by Graywolf9** [comment]
keep `original_slug` in `conflicting`/`orphaned` does not have that problem?

**Comment by queengooborg** [comment]
Not anymore; I just updated the front matter linting config to allow for `original_slug`!

**Comment by Graywolf9** [comment]
Great! Thanks for all your time, I removed `browser-compat` frontmatter and the `specs`/`compat` sections to not show the errors

**Review by queengooborg — APPROVED** [review]
Thanks!

I imagine that we'll probably remove a lot of these files in the end,

**Pull request merged**
