### PR TITLE
fix(css-tools): replace with GHLiveSample

### PR DESCRIPTION
**Pull request by caugner**
### Description

Replaces remaining CSS Tools live samples with the corresponding GitHub live sample.

### Motivation

The CSS Tools (border-image generator, box-shadow-generator, color-picker-tool) have been migrated upstream in https://github.com/mdn/content/commit/1f3d608c21062556167cad135eabaee4b107af34, but these changes have not yet been propagated to all locales.

In fact, the live samples no longer work, e.g. https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Colors/Color_picker_tool:

image

### Related issues and pull requests

Extracted from https://github.com/mdn/translated-content/pull/10402.

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for l10n-zh. Thank you @caugner

**Review by sashasushko — APPROVED** [review]
Approve from RU. Thank you @caugner 🙏

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es`, Thank you!

**Comment by caugner** [comment]
Since those pages are currently broken in `ko` and `pt-BR`, and this PR fixes that, I will go ahead and merge as is, without waiting for approval. Hope this is okay! 🙂

**Pull request merged**
