### PR TITLE
fix: Markdownlint cleanup for KO

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by hochan222 — APPROVED** [review]
LGTM. Have a nice Day :)

**Comment by hochan222** [comment]
@nschonni, Hello. Can you please tell me how you checked markdown lint?

**Comment by nschonni** [comment]
- To install the cli locally `npm i -g markdownlint-cli`
- To lint everything `markdownlint "**/*.md" --fix" to autofix what it can, but there are manual fixups required. Or if you just wanted to do the KO docs `markdownlint "files/ko/**/*.md" --fix`
- Most of the config should pass, but the new MD051 and MD052 rules probably need to be disabled, but I haven't done a PR for that yet

**Comment by hochan222** [comment]
@nschonni , Hello. thank you for your reply! 

It actually looks very useful. Have a good day. :)

**Pull request merged**
