### PR TITLE
Delete old How to contribute page

### PR DESCRIPTION
**Pull request by yanaklose**
This page is detailing ways to contribute to MDN for people with different levels of experience (beginner, web-developer, teacher). It seems to be a very old version of [this one](https://developer.mozilla.org/en-US/docs/MDN/Contribute). As far as I am able to piece together, contribution guides used to be in the Learn directory and then at some point were moved to the separate Contribute directory and rewritten. @chrisdavidmills please correct me if I’m wrong.
The aforementioned _Contributing to MDN_ English page already has a separate Russian translation [here](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/index.html) (albeit incomplete), so I assume it’s safe to delete this old one.

### CODE REVIEW

**Comment by mpstv** [comment]
I think deleting this old page is safe, but I'm confused... Why is @peterbe commit locate in your branch?

**Comment by captainspring** [comment]
> I think deleting this old page is safe, but I'm confused... Why is @peterbe commit locate in your branch?

He didn’t commit it to this branch specifically, his commit was a part of [this PR](https://github.com/mdn/translated-content/issues/297). I guess, I created my PR while that PR was still pending, but since my commit and @peterbe’s commit both change the same file, my PR also includes his commit. (At least, as far as I understand the inner workings of GitHub.)
Either way, that PR is already merged/closed so it should be ok?

**Comment by mpstv** [comment]
I saw this https://github.com/mdn/translated-content/pull/302 also contain similar commit, but on "File changed" tab not showing changes from this commit. I'm really not sure what we should do. @lex111 is it safe to merge current PR ?

**Comment by peterbe** [comment]
You can either get someone else's commit in your PR if you don't start from `main` but from an outdated `main`. 
Or, if you `git cherry-pick` someones commit in the same git repo.

**Comment by mpstv** [comment]
I think I understand. https://github.com/mdn/translated-content/pull/302 contain commit with merge `main` into PR branch. 

@captainspring can you merge fresh `main` into your `captainspring-delete-old` branch ? 

If after doing this, other changes, except for deleting the old page, disappear from the "Files Changed" tab, then we can be sure that the merge is safe.

**Comment by captainspring** [comment]
> You can either get someone else's commit in your PR if you don't start from `main` but from an outdated `main`.
> Or, if you `git cherry-pick` someones commit in the same git repo.

@peterbe thank you for the explanation!
I was actually editing the file directly on GitHub, so it’s a bit confusing to me how this happened. 😕 



> can you merge fresh `main` into your `captainspring-delete-old` branch ?

@mpstv I was trying to avoid working with this repo locally, but it seems impossible to merge/pull anything into the branch without cloning the repo.
Okay. So. I am not yet very well-versed in using git, so bear with me, please.
I tried doing this, I’ll just copy what I got in Terminal:
```
% git rebase origin/main
Current branch captainspring-delete-old is up to date.
% git merge origin/main -m "Updates this branch with main"
Already up to date.
% git status
On branch captainspring-delete-old
Your branch and 'origin/captainspring-delete-old' have diverged,
and have 33 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```
So naturally I tried following the instructions and pulled, and now the status message I’m getting for my local branch is:
```
Your branch is ahead of 'origin/captainspring-delete-old' by 34 commits.
  (use "git push" to publish your local commits)
```
At this point I am getting slightly scared and feel like I somehow messed this up along the way.

I think it will be much easier for everyone to just close this PR and delete this branch entirely and start from scratch.

**Comment by mpstv** [comment]
As far as I can tell, you did everything right. 

> `Your branch is ahead of 'origin/captainspring-delete-old' by 34 commits.`

It is normal. Your branch now contain new commits from `main`.

> At this point I am getting slightly scared and feel like I somehow messed this up along the way.

@captainspring feel free to push this changes.
If something goes wrong, there is always an option to close this one and start new PR.

**Comment by captainspring** [comment]
> feel free to push this changes.
> If something goes wrong, there is always an option to close this one and start new PR.

Oh, good! Thank you for your patience.
Done.

**Comment by mpstv** [comment]
So... i think something went wrong )) 
Perhaps this was due to the use of `rebase` command. Did you do `git push -f` ? 
@captainspring now we should create new PR, sorry for this!

**Comment by captainspring** [comment]
> So... i think something went wrong ))
> Perhaps this was due to the use of `rebase` command. Did you do `git push -f` ?
> @captainspring now we should create new PR, sorry for this!

No problem :)))
That was quite a learning curve for me. No, I didn’t `git push -f`, unfortunately, but I’ll know to do that if I ever find myself in such situation again. Thank you for your time!

**Pull request closed without merging**
