### PR TITLE
KS: Removal of the least used macros - l10n-frozen

### PR DESCRIPTION
**Pull request by tristantheb**
### 🎫 Related issues
mdn/yari#3063

### 👀 Observed issues
KumaScript macros are being phased out, to help the Yari dev team, here is a list of macros that will disappear from your files.

I invite you to check your files in your languages to make sure it doesn't break any translations. You can edit them directly on my branch. If you want to take care of it after merging this request, feel free :)

### 🔁 Changes in commits
*This list is taken from the issue quoted above, the numbers are not current.*
```
kumascript/macros/原語併記.ejs                         88
kumascript/macros/HTML5ArticleTOC.ejs              77
kumascript/macros/EditorGuideQuicklinks.ejs        42
kumascript/macros/gecko_callout_heading.ejs        38
kumascript/macros/IRCLink.ejs                      26
kumascript/macros/ref.ejs                          25
kumascript/macros/gecko_minversion_note.ejs        22
kumascript/macros/h1_gecko_minversion.ejs          20
kumascript/macros/FontAwesomeIcon.ejs              11
kumascript/macros/endnote.ejs                      11
kumascript/macros/h2_gecko_minversion.ejs          10
kumascript/macros/UserLink.ejs                     9
kumascript/macros/訳語.ejs                           6
kumascript/macros/LXRSearch.ejs                    2
kumascript/macros/tree.ejs                         2
kumascript/macros/B2GOnlyHeader2.ejs               1
```

```diff
! Only macros used less than 100 times for the moment.
! The pull request would be too big to process everything at once.
```

The compatibility tables are not done in this pull request (except when I stumble upon them). They require a query of their own, as there are many of them.

### CODE REVIEW

**Comment by peterbe** [comment]
I'm not sure how to review this. 228 files is a lot to take responsibility for. 
Also, the files that are in a folder called `orphaned` or `conflicting` should not be edited because they're going to be deleted in a couple of weeks. 

Would it be at all possible to break this up into 1 PR per locale and then skip the `orphaned` and `conflicting` ones?
You could take a complete copy of this branch, put it aside, then start over by copying over every single `index.html`, one locale at a time into a new branch. 

Also, sorry about this but I would like get @escattone 's opinion on https://github.com/mdn/yari/issues/3063#issuecomment-823333705 first.

**Comment by tristantheb** [comment]
No worries @peterbe ^^
I'm doing this to help the Yari team on the deletion of macros 😉

I'm going to make PRs for the active locales, the freezes will be able to stay on this PR 👍🏻

**Comment by mfuji09** [comment]
原語併記 (which means "with the original word") and 訳語 (which means "translation word") macros are only used in Japanese translation.
I agree with to remove these macros, but they have semantic meanings. So I want to remove them (and replace other expressions) manually. Could you give us a time?

**Comment by tristantheb** [comment]
@mfuji09 As I said in my main comment, you can use my branch to correct what is wrong with your language after this deletion.
On top of that, the active languages will be moved to a pure RP, so you will have your language on a single RP, free to correct what is changed before merging 😄
I'll put you on reviewer for l10n-ja on the new pull request?

**Comment by mfuji09** [comment]
@tristantheb These macros tend to be used in older translated documents, and it is likely that translations containing them will have to be re-translated.
So could you please leave them to us (Ja community) to fix the Japanese translation, rather than replacing machinally?

**Comment by tristantheb** [comment]
Don't worry about it, you can close the request #612 if needed to make a new one with the version reviewed by your community ;)
Personally, I have only set up a working branch with modifications, but it is up to you to decide how you want to work afterwards ^^ At least this branch already gives you a list of pages to modify 🙂

**Comment by peterbe** [comment]
> I agree with to remove these macros, but they have semantic meanings. So I want to remove them (and replace other expressions) manually. Could you give us a time?

We're *not* in a hurry to get rid of all kumascript macros. In fact, we are going to keep some. 
But in general, for stuff that can be expressed with pure HTML or pure Markdown, always prefer that. 

If the `原語併記.ejs` macro is genuinely useful, let's not delete it at all then. It's your call @mfuji09

**Pull request merged**
