### PR TITLE
Fix - Issue #102

### LINKED ISSUE #102: 404 Bad link in french https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Using_IndexedDB
at https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Using_IndexedDB#%C3%A0_propos_de_ce_document
in 
> Ce tutoriel vous guide à travers l'utilisation de l'API asynchrone de IndexedDB. Si vous n'êtes pas familier avec le principe de IndexedDB, vous devriez d'abord lire les concepts basiques d'IndexedDB.

 the link goes to the 404 https://developer.mozilla.org/en-US/IndexedDB/Basic_Concepts_Behind_IndexedDB 

instead of https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Basic_Concepts_Behind_IndexedDB

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Fixes #102 replaced the english with a french link

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@CreaTorAlexander could you split the commits so that only the one about fr is in this PR?

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
cf. previous comment about picking only one commit (the one about the fr doc)

**Comment by CreaTorAlexander** [comment]
@SphinxKnight sorry haven't seen it. How can I remove the other commit?

**Comment by SphinxKnight** [comment]
There are different strategies that you could use here. A quite straightforward (but "violent") one would be to rebase your branch on a previous commit to avoid https://github.com/mdn/translated-content/pull/248/commits/f067d73aa702510ac3d0551a39d7e9fbd75bc972 and then force-push the branch anew here.

**Comment by CreaTorAlexander** [comment]
@SphinxKnight thanks for your help, I am not confident with this because I never did it before. I will do a new PR

**Pull request closed without merging**
