### PR TITLE
[ru] convert conflicting to markdown

### PR DESCRIPTION
**Pull request by yin1999**
### Description

convert to markdown for conflicting folder.

### Related issues and pull requests

- https://github.com/orgs/mdn/discussions/227
- mdn/yari#7574

### CODE REVIEW

**Comment by yin1999** [comment]
convertion log:

[md-conversion-problems-report-2022-11-20T13_28_39.518Z.md](https://github.com/mdn/translated-content/files/10061604/md-conversion-problems-report-2022-11-20T13_28_39.518Z.md)

**Comment by yin1999** [comment]
Hi @sashasushko, do you need any help from me :)

**Comment by sashasushko** [comment]
@yin1999 if only the 25th hour in the day 😞

**Comment by yin1999** [comment]
Hi @sashasushko, I've manually checked those rendered documents, and applied some fixes. If this is ok, we can merge it.

**Review by sashasushko — APPROVED** [review]
LGTM 🔥

**Pull request merged**
