### PR TITLE
delete conflicting/orphaned docs (zh-CN)

### PR DESCRIPTION
**Pull request by peterbe**
Ever since early spring 2021, we decided to not index the conflicting (and orphaned) documents but leave them in the repo. These documents will not be found by Google searching or our own internal site-search. 
The original motive was to keep these around until each localization team has decided that the slug that *should* be kept is more up-to-date.

### CODE REVIEW

**Review by fiji-flo — APPROVED** [review]
👍

**Comment by irvin** [comment]
I don't have problems with those conflict docs.
for orphan docs, I found that it's possible to identify some origin of them so I'll take some time to re-locate them.

**Review by irvin — CHANGES_REQUESTED** [review]
@peterbe I had re-locate those orphan files that I can able to identify the current path.
However I don't know how to fix _redirect conflict, please help rebase.

**Comment by irvin** [comment]
截圖 2021-07-17 上午3 43 14
Always pull before push, and please ensure you're not overwrite any commit from others before doing a force push.

**Comment by peterbe** [comment]
> 截圖 2021-07-17 上午3 43 14
> @peterbe Always pull first before push. Also please ensure you're not overwriting any commit from others, before doing a force push.

It took me by surprise. 
The mdn/translated-content repo is the only repo I've participated in where people are committing to my branch. Usually, on mdn/yari for example, if someone "disagrees" with something in the PR, they either post PR review comments or they make a PR to the first PR. 
I didn't realize that someone had committed into *my* PR and I thought the reason the push didn't work was because I had amended the git commit message, so I did the force push. I shouldn't have done that. Sorry.

**Comment by irvin** [comment]
> > 截圖 2021-07-17 上午3 43 14
> > @peterbe Always pull first before push. Also please ensure you're not overwriting any commit from others, before doing a force push.
> 
> It took me by surprise.
> The mdn/translated-content repo is the only repo I've participated in where people are committing to my branch. Usually, on mdn/yari for example, if someone "disagrees" with something in the PR, they either post PR review comments or they make a PR to the first PR.
> I didn't realize that someone had committed into _my_ PR and I thought the reason the push didn't work was because I had amended the git commit message, so I did the force push. I shouldn't have done that. Sorry.

push to your repo is the way to add commit to PR on main repo, so it's possible that we do that (like I'm re-applying at now)

**Comment by peterbe** [comment]
@irvin this became a mess and I'm sorry about that. But things went a bit more wrong because you merged into `main` even though the CI tests didn't pass.

**Comment by irvin** [comment]
oh, pretty sorry about the trouble.

**Pull request merged**
