### PR TITLE
Fix Math.max() initial value to -Infinity

### PR DESCRIPTION
**Pull request by hata6502**
from https://github.com/mdn/content/pull/12396

### CODE REVIEW

**Comment by nathipg** [comment]
@hata6502 Hello! I have a question about this change: In the English version the initial value is 0 (zero), why did you put -Infinity?

**Comment by hata6502** [comment]
Sony, the pull request of English version is merged.
But MDN site is not updated yet.

https://github.com/mdn/content/pull/12396
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max#getting_the_maximum_element_of_an_array

**Review by irvin — APPROVED** [review]

**Comment by nathipg** [comment]
> Sony, the pull request of English version is merged. But MDN site is not updated yet.
> 
> [mdn/content#12396](https://github.com/mdn/content/pull/12396)
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max#getting_the_maximum_element_of_an_array

Thank you for the answer! Sorry, I looked at the site and forgot to check the code before asking

**Review by nathipg — APPROVED** [review]
Approved by @mdn/yari-content-pt-br

**Review by yechoi42 — APPROVED** [review]

**Comment by irvin** [comment]
@mfuji09 please check the ja doc

**Review by mfuji09 — APPROVED** [review]
OK for ja doc

**Comment by hata6502** [comment]
Thank you! :)

**Pull request merged**
