### PR TITLE
zh-cn: init localizaiton of js performance

### PR DESCRIPTION
**Pull request by hanyujie2002**
### Description

Same as title
### Motivation
Ditto

### Additional details

I don't know how to translate the "hook into" in [line 239](https://github.com/mdn/content/blob/1f0e43c634f449bf1dbbb592db2e232c1be9a8ad/files/en-us/learn/performance/javascript/index.md?plain=1#L239)
### Related issues and pull requests

Relates to #16025

### CODE REVIEW

**Review by yin1999 — COMMENTED** [review]
Please lowercase the filepath

**Comment by hanyujie2002** [comment]
> Please lowercase the filepath

OK ( •̀ ω •́ )✧

**Comment by hanyujie2002** [comment]
Sorry, there seems some problem happen, I will try to fix it

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Please remove the french file(or update the description of the PR) and remove the public file

**Pull request closed without merging**
