### PR TITLE
[es, pt_br] fix the broken image link

### LINKED ISSUE #16485: [pt-BR] img not being loaded - page not found
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I opened up the [link](https://developer.mozilla.org/pt-BR/docs/Learn/Forms/Your_first_form) on the following web browsers:
Edge -  95.0.1020.30  (64-bit)
Brave - version 1.31.88 (64-bit)
Chrome - 95.0.4638.69 (64-bit)

As you can see in the attached picture below, the [img link](https://developer.mozilla.org/files/4579/form-sketch-low.jpg) won't be loaded up:
image
..,
image

Main page: 
https://developer.mozilla.org/pt-BR/docs/Learn/Forms/Your_first_form

The one containing the broken img link:
 https://developer.mozilla.org/pt-BR/docs/Learn/Forms/Your_first_form#desenhando_seu_formul%C3%A1rio

### PR DESCRIPTION
**Pull request by wtwang1998**
### Description

close #16485

### CODE REVIEW

**Review by Graywolf9 — APPROVED** [review]
Hello! I hope it don't minds to you I take the opportunity to fix some flaws in the `es` document

Fixed flaws:
image

**Comment by Snoopy1866** [comment]
@Graywolf9 Hello! No problem at all, feel free to make any changes to the document.

**Comment by Graywolf9** [comment]
Thank you so much! @Snoopy1866 

once some of the @mdn/yari-content-pt-br team approve the PR we are ready to merge

**Comment by JuanVqz** [comment]
Hey folks! @mdn/yari-content-pt-br we need your approval here, please!

**Comment by Snoopy1866** [comment]
@clovislima looks not avtivity, is there any other who can review it?

**Comment by JuanVqz** [comment]
> @clovislima looks not avtivity, is there any other who can review it?

Split the PR, one for ES one for BR, and we can merge the one for ES...

**Comment by Snoopy1866** [comment]
> Split the PR, one for ES one for BR, and we can merge the one for ES...

Here are they: #25230 #25231. I will close this pr, thanks!

**Pull request closed without merging**
