### PR TITLE
Updated (broken link to image) #4139

### LINKED ISSUE #4139: Issue with "並行モデルとイベントループ": (broken link to image)
MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop

#### What information was incorrect, unhelpful, or incomplete?

Unlike the other languages, the image (alt: Stack, heap, queue) has a broken link and disappears:

https://github.com/mdn/translated-content/blob/a901ccf2b7747322b75d9f81014d7d88426bea8a/files/ja/web/javascript/eventloop/index.html#L19

The English version shows with this image: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop/the_javascript_runtime_environment_example.svg

#### Specific section or headline?

The section is 「視覚表示」.

#### What did you expect to see?

It should shows the image like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop/the_javascript_runtime_environment_example.svg

Or like other languages: https://github.com/mdn/translated-content/search?q=the_javascript_runtime_environment_example

#### Did you test this? If so, how?

By browsing the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/javascript/eventloop`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/eventloop/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a69836c420c06922cc657992d0c4dadec297d061
* Document last modified: 2022-02-13T19:09:38.000Z

</details>

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hi @cw118 I have fixed /files/4617/default.svg to the_javascript_runtime_environment_example.svg in the file. Please review my PR.
If any changes still needed do inform me.
Thanks!
Fix #4139

### CODE REVIEW

**Comment by cw118** [comment]
@mfuji09 Apologies for the ping, just wondering if there's anything holding this back from being merged? The fix doesn't show on the preview, which has had issues serving assets for a while now, but I can confirm it works locally.

<details>
<summary>Testing the fix with the styles removed as well:</summary>

```html
<p><img alt="Stack, heap, queue" src="the_javascript_runtime_environment_example.svg"></p>
```

ja-stack-heap-queue
</details>

**Review by mfuji09 — APPROVED** [review]
Ok

**Comment by mfuji09** [comment]
It seems ok. Firstly I couldn't confirm whether it is resolved or not, but I can confirm now.

**Comment by cw118** [comment]
> It seems ok. Firstly I couldn't confirm whether it is resolved or not, but I can confirm now.

I see, thank you so much :)

**Comment by NaincyKumariKnoldus** [comment]
Thankyou so much @cw118 and @mfuji09

**Pull request merged**
