### PR TITLE
fix: metadata spacing ES

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by Graywolf9 — APPROVED** [review]
Thank you!

**Comment by taciojoga10** [comment]
<a href=https://www.youtube.com/watch?v=RpSOM7qTZjk>prodentim</a>

**Comment by taciojoga10** [comment]
<a href=https://www.youtube.com/watch?v=m9NAiYwQcbc>prodentim</a>

**Comment by taciojoga10** [comment]
<a href=https://www.youtube.com/watch?v=GYx9xkfXIZo>https://www.youtube.com/watch?v=GYx9xkfXIZo</a>

**Pull request merged**
