### PR TITLE
add code to make it more elegant

### PR DESCRIPTION
**Pull request by KevinZonda**

### CODE REVIEW

**Review by mfuji09 — CHANGES_REQUESTED** [review]
It shouldn't be changed because `<code>`s in `<pre>` are reported as flaws by the Yari platform.
And this change is meaningless because the original version (in English) has been already convert to Markdown.

**Comment by KevinZonda** [comment]
> It shouldn't be changed because `<code>`s in `<pre>` are reported as flaws by the Yari platform.
> And this change is meaningless because the original version (in English) has been already convert to Markdown.

So 
image
JP edition

image
EN edition

image
CN edition

could u tell me why Japanese one looks so different?

**Comment by mfuji09** [comment]
@KevinZonda 
It is because the English version has been converted to Markdown and uses the syntax highlight of `js`. Japanese one hasn't been converted yet and isn't used a class `brush: js` in the `<pre>` element.
So the code in Japanese one isn't decorated and it is shown in normal monospace font. Perhaps the default monospace font of Japanese in **your** browser is MS Gothic. It is a very old font (created about 30 years ago) and it uses bitmap fonts for smaller characters for compatibility reason. So it looks ugly.

This problem should be corrected (to be shown as well as English version) by being converted to Markdown, or using a class `brush: js`.
Please note that a problem of presentation mustn't be fixed by modifying HTML markup because it should be fixed by CSS.

**Comment by KevinZonda** [comment]
Cool, thx :)

**Pull request closed without merging**
