### PR TITLE
Update fr team to reflect current activity

### PR DESCRIPTION
**Pull request by SphinxKnight**
This goes with #1243.

### CODE REVIEW

**Review by tristantheb — APPROVED** [review]
FR : ok

**Review by mfuji09 — APPROVED** [review]

**Comment by SphinxKnight** [comment]
@fiji-flo is this OK for you?

**Comment by SphinxKnight** [comment]
I have rebased this one after https://github.com/mdn/translated-content/pull/1729 and I have added @audrasjb. I intend to merge this one as soon as https://github.com/mdn/translated-content/issues/1243 is solved.

**Review by mfuji09 — APPROVED** [review]
It looks okay for Japanese translation.

**Pull request merged**
