### PR TITLE
ja: replace all remaining {{(m)anch}} calls with anchor tags

### LINKED ISSUE #4687: {{manch}} macros on Japanese pages
This is related/very similar to issue 4614. The `{{manch}}` macro has also been deprecated (credit goes to **SphinxKnight** for finding it) and should be removed from these Japanese files (excludes `orphaned` and `conflicting`):

- [ ] web/api/blobbuilder/index.html
- [ ] web/api/websocket/bufferedamount/index.html

### PR DESCRIPTION
**Pull request by queengooborg**
This PR is a part of #4614 that removes all remaining calls to the now-deprecated `{{anch}}`  and `{{manch}}` macros and replacing them with anchor tags or Markdown links, using the script from https://github.com/mdn/content/pull/13802. Fixes #4687.

### CODE REVIEW

**Review by mfuji09 — APPROVED** [review]

**Comment by mfuji09** [comment]
@queengooborg 
Thank you, and can you resolve the conflicts?

**Comment by queengooborg** [comment]
Done!

**Comment by queengooborg** [comment]
FYI @mfuji09, since I don't have write access to the repository, your auto-merge was automatically disabled!

**Review by mfuji09 — APPROVED** [review]

**Comment by mfuji09** [comment]
Thanks!

**Pull request merged**
