### PR TITLE
fix(ru): article __defineSetter__

### PR DESCRIPTION
**Pull request by scffs**
var -> let

### CODE REVIEW

**Comment by sashasushko** [comment]
@scffs thank you. Let's use `const` as in [original article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineSetter__)

**Comment by sashasushko** [comment]
@scffs please, also check other your RP 🙏  We should sync translation version with the original one, with English.

**Comment by scffs** [comment]
oh, sry I didn't think about it
got it now tnaks!

**Comment by sashasushko** [comment]
Source of the original version you can find here – https://github.com/mdn/content/ – the file structure is the same

**Comment by scffs** [comment]
I think that's done

**Review by saionaro — APPROVED** [review]
@scffs спасибо за правки!

**Pull request merged**
