### PR TITLE
Fix small typo in "Примечание : "

### PR DESCRIPTION
**Pull request by ivan-developer-01**
### Description

I just saw a small typo and I want to fix it.

### Motivation

I'm just fixing small problems, concentrating on small typos, fixes, etc.

### Additional details

This typo has seen [here](https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements).
screenshot

### CODE REVIEW

**Review by saionaro — APPROVED** [review]
@ivan-developer-01 спасибо за вклад в MDN!

**Comment by ivan-developer-01** [comment]
@Saionairo спасибо!

**Comment by ivan-developer-01** [comment]
Как я понял, тут можно писать issues на русском?

**Comment by Saionaro** [comment]
@ivan-developer-01 верно, если они относятся к русской локализации

**Pull request merged**
