### PR TITLE
chore: Add Markdownlint Search/Replace rule

### PR DESCRIPTION
**Pull request by nschonni**
### Description

Upstream, this custom rule is used to enforace several other conventions that aren't supported directly in Markdownlint. Some of the upstream rules like the ones around smart quotes go against some of the conventions of the locales, so just porting one that will ajust spaceing similar to what Prettier will do in the long run.
Opening as Draft, since I've opened up several PRs for the various locales, so the auto-PRs don't get flooded with 1000 changes.

### CODE REVIEW

**Comment by nschonni** [comment]
Only one PR remains https://github.com/mdn/translated-content/pull/10215 so marking this as Ready

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
> Only one PR remains #10215 so marking this as Ready

@nschonni Do we need to wait for that PR to land before merging this one?

**Comment by nschonni** [comment]
@caugner it's OK to merge this one, and the auto-fix job will just create a new PR. There are only 7 files for the russian files affected, so it's ok to have the auto-fix job re-create that one

**Comment by nschonni** [comment]
https://github.com/mdn/translated-content/pull/10215 landed now, the new remaining issues will be swept up by the auto-fix job

**Pull request merged**
