### PR TITLE
[fr] Typofix for `mouseleave` event

### PR DESCRIPTION
**Pull request by dan0203**
Orthographe simple

### Description

There was a small typo

### Motivation

Enhance user's experience and happy to contribute for the 1st time :)

### CODE REVIEW

**Comment by dan0203** [comment]
Did I not do it right ? Do I need to do something else in ?

**Comment by Mr-BeanSir** [comment]
> Did I not do it right ? Do I need to do something else in ?

That might just be an automated reminder for managers to see

**Review by cw118 — APPROVED** [review]
> Did I not do it right ? Do I need to do something else in ?

The comment just provides a preview link, which is done for every PR :)

This looks great, thank you for the correction and congratulations on this first contribution to translated-content!

**Comment by dan0203** [comment]
yay thanks! :)

**Pull request merged**
