### PR TITLE
Update MDN Contribute content and change to markdown

### PR DESCRIPTION
**Pull request by Graywolf9**
Update MDN Contribute content and change to markdown

### CODE REVIEW

**Review by JuanVqz — APPROVED** [review]

**Comment by cw118** [comment]
Just wanted to note that to include localized/translated note cards (e.g. Spanish versions of **Note:** and **Warning:**) in Markdown files, (I believe) an `es.json` file can be added to the [this folder at mdn/yari](https://github.com/mdn/yari/tree/main/markdown/localizations). Otherwise, as seen in the preview, these cards won't have the "correct"/desired styling.

**Comment by JuanVqz** [comment]
> Just wanted to note that to include localized/translated note cards (e.g. Spanish versions of **Note:** and **Warning:**) in Markdown files, (I believe) an `es.json` file can be added to the [this folder at mdn/yari](https://github.com/mdn/yari/tree/main/markdown/localizations). Otherwise, as seen in the preview, these cards won't have the "correct"/desired styling.

@cw118 thank you! this means a lot for us as newbies. 
@Graywolf9 I'll add the Spanish file there.

**Comment by Graywolf9** [comment]
Thank you so much @cw118 !

**Review by JuanVqz — APPROVED** [review]

**Comment by JuanVqz** [comment]
This file is so important and interesting. The k you @Graywolf9 for your contribution! We are happy for having you 🚀

**Pull request merged**
