### PR TITLE
fix: update backdrop-filter-pt-BR-page

### PR DESCRIPTION
**Pull request by ghost**
Part of #3930

### CODE REVIEW

**Comment by cw118** [comment]
Thanks again for this @victor0x16, I just removed the link to the issue so that it stays open for the other affected locales :)

**Comment by victor0x16** [comment]
@cw118 , done!

**Comment by cw118** [comment]
Ah @victor0x16 my bad, your previous version was perfect... I mixed up the syntax with something else. 

I'm really sorry about this 😖, please let me know if you'd like me to revert the changes (I don't want to commit/push directly without permission)

**Comment by victor0x16** [comment]
> I'm really sorry about this 😖, please let me know if you'd like me to revert the changes (I don't want to commit/push directly without permission)

That's fine to me. 

The image seems to load now 😄

**Comment by cw118** [comment]
> The image seems to load now 😄

It actually would load without quotes as well, and (I believe, at least for MDN) the syntax without quotes is the "standard" one, so I do think it'd be best to change it back (I'd be happy to do this since this was my fault). Again, I apologize for misleading you 😖

**Comment by victor0x16** [comment]
Yes, you can revert it. I look it on MDN as well and it seems the right choice.

**Comment by cw118** [comment]
Alright, it's done (hope you don't mind the force push) :)

(also politely poking @mdn/yari-content-pt-br)

**Review by josielrocha — APPROVED** [review]

**Pull request merged**
