### PR TITLE
duplicate: remove h3_gecko_minversion macro for pt-br

### PR DESCRIPTION
**Pull request by ghost**
Part of #5145

`20 matches across 4 files`

### CODE REVIEW

**Comment by cw118** [comment]
@victor0x16 thanks so much for this :)

After discussing with @italogois who opened a similar pull request, it seems that this one changes some of the macros to `h2`s and not `h3`s (I checked the en-US versions and I believe they should be h3 headings). However, I see that in both PRs, a few headings weren't translated.

Would it be possible for the two of you to discuss and decide:
- which PR to "keep"
- the scope of that PR (e.g. just removing the macros, removing the macros and translating the headings from en-US to pt-BR, etc.)

Thank you both for your contributions and let me know if I can help in any way :)

**Comment by italogois** [comment]
> 

Hi, i see now in my pull request, have one header without translation. I can translate this header to fix your second appointment

> @victor0x16 thanks so much for this :)
> 
> After discussing with @italogois who opened a similar pull request (cf. #5385), it seems that this one changes some of the macros to `h2`s and not `h3`s (I checked the en-US versions and I believe they should be h3 headings). However, I see that in both PRs, a few headings weren't translated.
> 
> Would it be possible for the two of you to discuss and decide:
> 
> * which PR to "keep"
> * the scope of that PR (e.g. just removing the macros, removing the macros and translating the headings from en-US to pt-BR, etc.)
> 
> Thank you both for your contributions and let me know if I can help in any way :)

Hi, I just viewed it in my pull request, I have an untranslated header. Can I translate this header to make everything right.

**Comment by cw118** [comment]
@victor0x16 now that the PR made by @italogois has been merged, this one is unfortunately a duplicate.

Is it OK if we close this?

**Comment by victor0x16** [comment]
@cw118 , it's okay!

Sorry for not  answering here, ISP issues :(

Thank you both for helping here 😄 ! @italogois 🚀 !

**Comment by cw118** [comment]
No worries @victor0x16, thank you for understanding :)

**Pull request closed without merging**
