### PR TITLE
fr, ja, ko: update glossary/code_splitting

### PR DESCRIPTION
**Pull request by PassionPenguin**
linted one url. sync with mdn/content#33404

related hash: d821201936ea3f67634381b2086998ebfc29f39c

### CODE REVIEW

**Review by SphinxKnight — APPROVED** [review]
OK for `fr`, thanks for tackling the other locales @PassionPenguin :bow:

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`.

**Comment by wisedog** [comment]
The reviewer is replaced. @hochan222

**Comment by wisedog** [comment]
Looks good for `ko`. Thank you. @PassionPenguin

**Review by wisedog — APPROVED** [review]

**Comment by PassionPenguin** [comment]
> Looks good for `ko`. Thank you. @PassionPenguin 

thx：） so we have all our locales approved. may you merge the pr, appreciated!

**Pull request merged**
