### PR TITLE
Fix cursor page

### PR DESCRIPTION
**Pull request by clopso**
**fix:**
- "no-drop" with "float: left"
- pt-BR page does not show some cursors

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for zh-CN. Thanks

**Comment by irvin** [comment]
ping @mdn/yari-content-ko @mdn/yari-content-pt-br for review

**Review by hochan222 — APPROVED** [review]
ko-locale LGTM :)

**Comment by yin1999** [comment]
Is there anyone who can look at this @mdn/yari-content-pt-br :)

**Comment by josielrocha** [comment]
Hey @clopso,
There are some conflicts on pt-BR files. Could you please fix it?

**Review by josielrocha — APPROVED** [review]
pt-br 👍🏽

**Pull request merged**
