### PR TITLE
remove hidden bcd table paragraph of 'ja' (partial 1)

### PR DESCRIPTION
**Pull request by peterbe**
Part of #1008

### CODE REVIEW

**Comment by peterbe** [comment]
@mfuji09 This is a second attempt to break https://github.com/mdn/translated-content/pull/1285 down into multiple PRs.

**Comment by peterbe** [comment]
@mfuji09 Perhaps my attempts here aren't helping. I noticed that my tooling leaves one extra whitespace when it deletes the hidden tag. If you want to I can close this if you want to take care of the rest of the files.

**Comment by peterbe** [comment]
@mfuji09 Do you want me to close this now and leave it to you to clean up all the remaining spots?

**Comment by mfuji09** [comment]
@peterbe 
I have submitted PRs the all hidden instructions of browser-compat-data and they have been merged.

**Comment by peterbe** [comment]
> @peterbe
> I have submitted PRs the all hidden instructions of browser-compat-data and they have been merged.

You never cease to impress me. Keep up the excellent contributions. We love you.

**Pull request closed without merging**
