### PR TITLE
Revert "spelling errors fixed "cobrir" and "ies""

### PR DESCRIPTION
**Pull request by sergiogval**
Reverts mdn/translated-content#4260

Tiene espacios vacios con contenido invisible. @JuanVqz porfa revisa.

### CODE REVIEW

**Comment by sergiogval** [comment]
Guys, I did't pushed this. This has malware on it
Screenshot from 2022-02-23 12-01-42

**Comment by sergiogval** [comment]
Screenshot from 2022-02-23 12-00-24

**Review by Graywolf9 — CHANGES_REQUESTED** [review]
No veo los errores mencionados afectados en este commit

**Comment by sergiogval** [comment]
image

They were in the original PR but now the branch is delated. Nice move.

**Comment by Graywolf9** [comment]
> They were in the original PR but now the branch is delated. Nice move.

You can look for the altered files in closed PRs or in this PR in `Files changed` tab, git saves everything: Fig. 1.

Also you can see absolutly all the changes to the file and see from which commit came the `SPACE` character, there are only 5 commits in this file and it comes from the init commit.
commit history file: https://github.com/mdn/translated-content/commits/main/files/es/web/css/background-repeat
init commit: https://github.com/mdn/translated-content/blob/1109132f09d75da9a28b649c7677bb6ce07c40c0/files/es/web/css/background-repeat/index.html

Fig. 1.
Captura de Pantalla 2022-02-23 a la(s) 19 03 45

**Comment by sergiogval** [comment]
image

For instance, why leave a div that is apparently empty, but contains that character and the "hidden" class? this may be used to inject code. How? well just change the decoder you are using and whatever it should render will be hidden.


Also, yes, incertain decoding is just an inocent nob brakin _space. But there are encoders that this has a diferent funcitión. has a way different functión.

- [source1](https://codepoints.net/U+00A0) 
- [source2](https://www.fileformat.info/info/unicode/char/00a0/codepage_support.htm)

Leaving this on the main branch is a security breach. I invite to all of you to meditate and do the right decision.

**Comment by Graywolf9** [comment]
Hi! @sergiogval I agree with your comments, that's why I invite you to do all the necesary changes in a different PR, reverting this don't going to make the changes yo mentioned. Also I wish to respect the contribution from the other user.

**Comment by sergiogval** [comment]
> Hi! @sergiogval I agree with your comments, that's why I invite you to do all the necesary changes in a different PR, reverting this don't going to make the changes yo mentioned. Also I wish to respect the contribution from the other user.

Agree, I will add this to my patch branch and  the PR will be a pack of 4 updates. That said, i think that if we have decided to let the author of the PR be the one that merge it, stick to the agreements we do. As you may remember all the team explained to me the flow and this PR didn't had my approval nor was merged by the author.

Regards.

**Comment by Graywolf9** [comment]
> That said, i think that if we have decided to let the author of the PR be the one that merge it, stick to the agreements we do.

About that the agreement was that the author can't merge himself, it needs the approval of a team member. The flux is like the next one.

Author make a PR -> Some one reviews and requests changes -> Autor make change or give an explanation -> The reviewer check the changes and approve/merge or request a new changes if necessary

**Comment by sergiogval** [comment]
Correct me if I'm wrong, The guidelines says that the PR owner is the one that closes it after the approval of the CRs. Why aren't we following this pattern?

**Pull request closed without merging**
