### PR TITLE
Markdown conversion for `pt-BR` - Replace - Events section :warning:  Do not squash :warning: 

### PR DESCRIPTION
**Pull request by SphinxKnight**
No previous PR about this one since there were no error in the first place.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Please :warning: Do not squash merge :warning:

**Review by nathipg — CHANGES_REQUESTED** [review]
Some titles from this page disapeared.

This version:

image

Current version:

image


Could you gave a look, please?

**Comment by SphinxKnight** [comment]
Thanks @nathipg I'll check what's going on

**Comment by SphinxKnight** [comment]
OK the headings are in the tables. I'm going to submit another PR to fix that "upstream" and will rebase this one so that it only converts stuff.

**Comment by SphinxKnight** [comment]
Waiting for https://github.com/mdn/translated-content/pull/8836

**Review by josielrocha — APPROVED** [review]
LGTM ;)

**Comment by SphinxKnight** [comment]
> LGTM ;)

@josielrocha do you want to merge #8836 beforehand? :)

**Comment by SphinxKnight** [comment]
since the headings are fixed (cf. preview) and that @josielrocha approved earlier, I'm going to merge this one.

**Pull request merged**
