### PR TITLE
fix: using absolute path for image `src`s

### PR DESCRIPTION
**Pull request by yin1999**
Referenced Issues: #3752

### CODE REVIEW

**Comment by yin1999** [comment]
Images may cannot see because images are only available on domain "developer.mozilla.org".

**Review by cw118 — CHANGES_REQUESTED** [review]
Hi @yin1999, thank you for working on the fix, but SphinxKnight has actually already created a PR fully updating and fixing the French page in #3713, so could you undo the changes to the French file please?

**Comment by yin1999** [comment]
@cw118 ok, I'll do this tomorrow.

**Review by mfuji09 — APPROVED** [review]
I approve for ja files.

**Review by myshov — APPROVED** [review]
👍 for Ru files

**Comment by yin1999** [comment]
> Hi @yin1999, thank you for working on the fix, but SphinxKnight has actually already created a PR fully updating and fixing the French page in #3713, so could you undo the changes to the French file please?

Done

**Review by cw118 — APPROVED** [review]
> Done

Thank you, much appreciated :)

**Review by yujo11 — APPROVED** [review]
👍 👍 👍

**Review by JuanVqz — APPROVED** [review]

**Comment by JuanVqz** [comment]
@yin1999 I approve it for :es:, thank you!

**Comment by SphinxKnight** [comment]
@mdn/yari-content-es , @mdn/yari-content-ko , @mdn/yari-content-ja, @mdn/yari-content-ru, @mdn/yari-content-zh I don't want to block this one but this PR made me realize a more elegant way was possible and I've opened https://github.com/mdn/yari/pull/5215 

Basically, this solves the issue of "non-resolution" for images which are not under translated-content in live samples (while images "directly" in the pages were already fallbacking on mdn/content files)

I hope this will help avoid absolute (or semi-absolute) URLs and file duplication (as a lazy person, this is the road I took so far for fr :( ) 

Of course, feedback welcome (over mdn/yari) if you want to test this :)

**Review by tristantheb — APPROVED** [review]

**Pull request closed without merging**
