### PR TITLE
UPDATE: FR-ONLY - Remove all old CompatibilityTable to replace with {{Compat()}}

### PR DESCRIPTION
**Pull request by tristantheb**
### 🎫 Related issues
N/A

### 👀 Observed issues
A large number of pages are not up to date with the browser compatibility table. These still use the old HTML tables.

### 🔁 Changes in commits
400+ pages now contain the table generated from Compat()

### CODE REVIEW

**Comment by tristantheb** [comment]
452 pages with scripts Compat<X> and CompatibilityTable udpdated !

**Review by tristantheb — COMMENTED** [review]
437 pages has no new translation fyi ;)

**Comment by SphinxKnight** [comment]
just a friendly poke at @Elchi3 about this one :)

**Review by SphinxKnight — APPROVED** [review]
Looks good  :) 
Would appreciate less files per PR though : )

**Pull request merged**
