### PR TITLE
feat: update var doc zh-cn

### PR DESCRIPTION
**Pull request by CristoMonte**

### CODE REVIEW

**Review by irvin — CHANGES_REQUESTED** [review]
please remove the `.history` folder and the two dummy files inside.

**Comment by CristoMonte** [comment]
@irvin deleted

**Review by irvin — CHANGES_REQUESTED** [review]
conflict, please rebase

**Comment by yin1999** [comment]
This document has been converted to markdown and up to date with english version via #4868.

**Pull request closed without merging**
