### PR TITLE
chore: remove the last {{previousPage}} macro

### PR DESCRIPTION
**Pull request by yin1999**

### CODE REVIEW

**Comment by yin1999** [comment]
It's there anyone who can review this @mdn/yari-content-pt-br

**Comment by nathipg** [comment]
@yin1999 Hi, thanks for your contribution! 

I have a question, on the page currently live (https://developer.mozilla.org/pt-BR/docs/Learn/CSS/Styling_text/Styling_lists) the "previous" link was pointing to (/en-US/docs/Learn/CSS/Howto/Generated_content) but now it's pointing to (/en-US/docs/Learn/CSS/Styling_text/Fundamentals), a page that doesn't exist, is that right?

**Comment by yin1999** [comment]
> @yin1999 Hi, thanks for your contribution!
> 
> I have a question, on the page currently live (https://developer.mozilla.org/pt-BR/docs/Learn/CSS/Styling_text/Styling_lists) the "previous" link was pointing to (/en-US/docs/Learn/CSS/Howto/Generated_content) but now it's pointing to (/en-US/docs/Learn/CSS/Styling_text/Fundamentals), a page that doesn't exist, is that right?

Yes, this page does not exist. so it will fall back to `en-US`. For this macro replacement. I've jsut copied this from [`en-US`](https://github.com/mdn/content/blob/e672bd6772e7328a74f427b9fc35d39ab9625a85/files/en-us/learn/css/styling_text/styling_lists/index.md?plain=1#L15). For we are just localizing `en-US` documents.

**Review by nathipg — APPROVED** [review]

**Review by davincike — COMMENTED** [review]
youwin

**Pull request merged**
