### PR TITLE
docs: update Russian translation for ru/mdn/index.md

### PR DESCRIPTION
**Pull request by impocode**

### CODE REVIEW

**Comment by impocode** [comment]
@captainspring

Привет! Очень жду обратную связь)

**Comment by sashasushko** [comment]
@impocode thank you for your help. Sorry for long response. I remember about your PR. And I'll review it ASAP. Peace 🕊

**Comment by impocode** [comment]
> It's ok. I'll resolve conflicts.

Thank you!

**Comment by queengooborg** [comment]
Hey @impocode, thank you for your PR!  After closer review, it appears that the English version of this document was updated and rewritten in mdn/content#20005, but this PR seems to match up with mdn/content@6ec6bf2b95fb1d10631d99d16e71d40cd0e33020.

I'm not sure if we should just close this PR, or if we should merge it and add the commit hash so we can track the synchronization with upstream -- either way, we'll need to retranslate this page anyways.  Or, alternatively, if you're still interested in contributing, would you be down to retranslate the newest version of the page?

**Comment by queengooborg** [comment]
I now see that the repository this branch is from has been deleted, so I'm going to assume that you're probably not interested in further contributions; I'm going to close this PR accordingly.  Nevertheless, thank you for your time and effort working on this project, and apologies for not getting to you much sooner!

**Pull request closed without merging**
