### PR TITLE
Add ZeroMQ

### PR DESCRIPTION
**Pull request by InfoLibre**
Adding ZeroMQ to the list of WS APIs Tools

### CODE REVIEW

**Comment by SphinxKnight** [comment]
Hi @InfoLibre, thanks for the PR. However, this item is not available in the English article which serves as the reference for the localized content.
Before merging this one, could you please open a PR on `mdn/content` (see https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/index.md?plain=1#L42-L61) to add ZeroMQ there as well?

Thanks a lot :)

**Review by SphinxKnight — CHANGES_REQUESTED** [review]
Needs to be added in `en-US` beforehand

**Comment by InfoLibre** [comment]
I proposed an en-us version: https://github.com/mdn/content/pull/23991

**Comment by bsmth** [comment]
Thanks both, I've approved and merged the `mdn/content` PR. 🙌🏻

**Pull request merged**
