### PR TITLE
Remove previously orphaned file

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Review by escattone — APPROVED** [review]

**Comment by irvin** [comment]
the files in this pr are not orphaned. I had moved them to the corresponding folder in last week's PR 1412.
It seems I miss adjusting the slug to the corrent path on these files.

**Comment by peterbe** [comment]
> the files in this PR are not orphaned. I had moved them to the corresponding folder in last week's PR 1412.
> It seems I miss adjusting the slug to the correct path on these files.

We had to rush through this because of these files it broke the production builds.

**Comment by irvin** [comment]
@peterbe no problem. Does the issue came from wrong slug?

**Comment by peterbe** [comment]
> @peterbe no problem. Does the issue came from wrong slug?

Yeah, if the `slug: ...` value is not matching the name of the folder it sits in, then it crashes.

**Comment by irvin** [comment]
> > @peterbe no problem. Does the issue came from wrong slug?
> 
> Yeah, if the `slug: ...` value is not matching the name of the folder it sits in, then it crashes.

ok, will make sure to fix those before bringing them back.

**Comment by escattone** [comment]
@irvin Sorry! Like @peterbe said, we rushed this because these files were breaking the production build (their slug didn't match the name of the path of the folder they existed within).

**Pull request merged**
