### PR TITLE
zh-cn: prepare to fix resizeobserverentry

### PR DESCRIPTION
**Pull request by fwqaaq**

### CODE REVIEW

**Comment by yin1999** [comment]
请按指南创建 markdown 转换的 PR <https://github.com/mdn/translated-content/blob/main/docs/zh-cn/h2m-guide.md>

**Comment by Jack-Zhang-1314** [comment]
> 请按指南创建 markdown 转换的 PR https://github.com/mdn/translated-content/blob/main/docs/zh-cn/h2m-guide.md

* What do you mean? I am not done.

**Comment by yin1999** [comment]
> > 请按指南创建 markdown 转换的 PR https://github.com/mdn/translated-content/blob/main/docs/zh-cn/h2m-guide.md
> 
> * What do you mean? I am not done.

image

**Comment by Jack-Zhang-1314** [comment]
But when I converted for first time, the content changed along with the filename

**Comment by yin1999** [comment]
> But when I converted for first time, the content changed along with the filename

Use `yari` for convertion:

https://user-images.githubusercontent.com/15844309/181159896-2efcff03-cd6c-4d28-9b74-1057f6304aa7.mp4

Or you can use `git mv /path/to/index.html /path/to/index.md` and then commit the rename changes first.

**Comment by Jack-Zhang-1314** [comment]
>Use `yari` for `convertion`:

* I see. I was using yari. But I hope to correct its content.

**Comment by yin1999** [comment]
> * I see. I was using yari. But I hope to correct its content.

You can just use `git` to do this job, but you must use command `git mv` to rename this file with a commit, and correct the content in the second commit.

**Comment by Jack-Zhang-1314** [comment]
> > * I see. I was using yari. But I hope to correct its content.
> 
> You can just use `git` to do this job, but you must use command `git mv` to rename this file with a commit, and correct the content in the second commit.

Maybe I can understand

**Comment by yin1999** [comment]
temporarily converted to draft

**Comment by Jack-Zhang-1314** [comment]
> temporarily converted to draft

what improvement is needed? Maybe I don't understand what you mean

**Comment by yin1999** [comment]
为了保存文件的 commit 历史，对于markdown转换的PR，我们**需要**将commit分为两个：

- 第一个commit：文件重命名，请使用命令 `git mv /path/to/index.html /path/to/index.md`，然后提交暂存的修改
- 第二个commit：文件内容转换以及修正

> 请不要将两个 commit 合并为一个

你可以参考 #7151。

**Comment by Jack-Zhang-1314** [comment]
Ok, 重新来过

**Comment by Jack-Zhang-1314** [comment]
Is that so?

**Comment by yin1999** [comment]
> Is that so?

Yes

**Review by yin1999 — APPROVED** [review]
Thanks a lot

**Comment by yin1999** [comment]
Have you done all the job (ready for merging?)

**Comment by Jack-Zhang-1314** [comment]
> Have you done all the job (ready for merging?)

yes

**Pull request merged**
