### PR TITLE
zh: Remove arguments to {{Specifications}} macros

### PR DESCRIPTION
**Pull request by queengooborg**
This PR performs the last little bits needed to complete #11594 for the Chinese locales.

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
Thanks @queengooborg!

**Comment by yin1999** [comment]
Hi @queengooborg, I just notice that after we migrating to ESM. The CI in translated-content is slower. [This step](https://github.com/mdn/translated-content/actions/runs/4261747120/jobs/7416424977#step:7:63) just spent more time than [before](https://github.com/mdn/translated-content/actions/runs/4048314445/jobs/6963395796#step:7:30).

**Comment by queengooborg** [comment]
> Hi @queengooborg, I just notice that after we migrating to ESM. The CI in translated-content is slower. [This step](https://github.com/mdn/translated-content/actions/runs/4261747120/jobs/7416424977#step:7:63) just spent more time than [before](https://github.com/mdn/translated-content/actions/runs/4048314445/jobs/6963395796#step:7:30).

I think this is due to the fact that Yari isn't using async nearly as much as it should, and synchronous file reading is one of _the_ biggest bottlenecks for NodeJS scripts.

Would you mind opening an issue in Yari regarding that?

**Comment by yin1999** [comment]
> Would you mind opening an issue in Yari regarding that?

Filled in mdn/yari#8301

**Pull request merged**
