### PR TITLE
chore: update the links to MDN discord server

### PR DESCRIPTION
**Pull request by yin1999**
### Description

update the links to MDN discord server

### Related issues and pull requests

upstream changes: mdn/content#30127

### CODE REVIEW

**Review by jasonren0403 — APPROVED** [review]
LGTM for l10n-zh 👍

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es`, Thank you!

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`!

**Review by swimjiy — APPROVED** [review]
LGTM for `ko`!

cc. @hochan222

**Pull request merged**
