### PR TITLE
Update pt-br CSS cursor page

### LINKED ISSUE #4448: pt-br CSS cursor page uses wrong image filepaths and specs/compat data
## What page(s) did you find the problem on?

The brazilian portuguese `cursor` - CSS page (https://developer.mozilla.org/pt-br/docs/Web/CSS/cursor)

## Specific page section(s) or heading(s)?

- Under the [Valores](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#valores) heading, more specifically the table with cursor type demos: all `/@api/deki` and `/files/` image sources (filepaths) should be corrected (see #3934 for an example) so that the pictures show

- The [specifications section](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#especifica%C3%A7%C3%B5es) should use the `{{Specifications}}` macro

- The [compatibility table](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#compatibilidade) should be converted to use the `{{Compat}}` macro

### PR DESCRIPTION
**Pull request by ghost**
fixes #4448

### CODE REVIEW

**Comment by cw118** [comment]
@victor0x16 thanks for opening this! I'm not a pt-br reviewer but is there any reason why the `files/pt-br/web/javascript/reference/classes/index.html` file is included here?

**Comment by victor0x16** [comment]
@cw118 wow, it is from another pull request that I've made.

**Comment by cw118** [comment]
@victor0x16 I'm being a little picky here, but I feel it'd be best to remove that file. Could you please "undo the changes" to that file on this PR?

**Comment by victor0x16** [comment]
@cw118, is that right? Sorry, I haven't done it before.

**Comment by cw118** [comment]
That looks good, thank you :)

And as for the actual "content" of this pull request, I see quite a bit of text that hasn't been translated (including image `alt`s) — I'm just pointing this out, whether or not that should be done here (or perhaps in another PR) is up to you and the pt-br review team :)

**Comment by victor0x16** [comment]
@cw118 , Thank you for pointing that out and I look  it for sure.

**Comment by victor0x16** [comment]
Hi @josielrocha, any update?

**Comment by victor0x16** [comment]
Olá @josielrocha, essa página está realmente precisando deste PR, então uma olhadinha aqui seria muito bom! 
@mdn/yari-content-pt-br

**Comment by cw118** [comment]
Politely poking @mdn/yari-content-pt-br here as well :)

**Pull request merged**
