### PR TITLE
Update MediaRecorder format

### PR DESCRIPTION
**Pull request by zhenzhenChange**
### Description

image

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
Thanks @zhenzhenChange, welcome aboard :)

**Comment by zhenzhenChange** [comment]
Just a moment, there are a few punctuation marks to change.

**Comment by zhenzhenChange** [comment]
And some descriptions are missing.

image

image

**Comment by zhenzhenChange** [comment]
There are still many problems with this chapter, I will take time to perfect it, close it first.

**Pull request closed without merging**
