### PR TITLE
Web/API/Request を更新

### PR DESCRIPTION
**Pull request by mfuji09**
2021/07/17 時点の英語版に同期

### CODE REVIEW

**Comment by peterbe** [comment]
To unbreak CI (Check Redirects) can you merge in the latest `main` into this branch. 
See https://github.com/mdn/translated-content/pull/1573 for more details.

**Comment by mfuji09** [comment]
@peterbe
I have merged the latest version of mdn:main, but checking redirects is still failed.
It looks errors are reported in es and zh-CN locales.

**Comment by SphinxKnight** [comment]
@mfuji09 I pushed https://github.com/mdn/translated-content/pull/1575/commits/ef65120cc0bf3566f9167d5530090da9c4aeca88 to help and confirm it fixed it for me on #1574

**Comment by hmatrjp** [comment]
I'm not sure which is related to fix redirect error in 10 commits offered in fr, let's give it a try!

**Comment by mfuji09** [comment]
> 
> 
> @mfuji09 I pushed [ef65120](https://github.com/mdn/translated-content/commit/ef65120cc0bf3566f9167d5530090da9c4aeca88) to help and confirm it fixed it for me on #1574

Thank you very much! It is very helpful!

**Pull request merged**
