### PR TITLE
Markdown conversion for `pt-BR` - Replace - Manifest section :warning:  Do not squash :warning: 

### PR DESCRIPTION
**Pull request by SphinxKnight**
Follow-up of https://github.com/mdn/translated-content/pull/8474
Conversion report: https://gist.github.com/SphinxKnight/e66a41050cc8314ab9fcfd527ef8201f#file-md-conversion-problems-report-2022-09-15t05_37_09-599z-md

### CODE REVIEW

**Comment by SphinxKnight** [comment]
https://gist.github.com/SphinxKnight/e66a41050cc8314ab9fcfd527ef8201f#file-md-conversion-problems-report-2022-09-15t05_37_09-599z-md

**Comment by nathipg** [comment]
> Please ⚠️ Do not squash merge ⚠️

Could you tell me why, please?

**Comment by SphinxKnight** [comment]
> > Please ⚠️ Do not squash merge ⚠️
> 
> Could you tell me why, please?

If squashed, the git history of a given file will be "cut"/split: there will be one timeline for the HTML file and a subsequent one for the MD file (but no link between them). Not squashing the "move"+"convert" commits allow us to keep the same timeline for the converted files.

Please let me know if this is unclear 🙇

**Comment by nathipg** [comment]
> > > Please ⚠️ Do not squash merge ⚠️
> > 
> > 
> > Could you tell me why, please?
> 
> If squashed, the git history of a given file will be "cut"/split: there will be one timeline for the HTML file and a subsequent one for the MD file (but no link between them). Not squashing the "move"+"convert" commits allow us to keep the same timeline for the converted files.
> 
> Please let me know if this is unclear 🙇

Thank you! I didn't know that

**Pull request merged**
