### PR TITLE
What-is-extension

### PR DESCRIPTION
**Pull request by tolerious**

### CODE REVIEW

**Comment by yin1999** [comment]
Hi @tolerious [mdn/yari](https://github.com/mdn/yari) will fallback to `en-US` to find those images when they are not in `zh-CN`, so please remove those images in this pr (althrough we cannot see those images in `pr preview`, but it's ok for deployment).

**Comment by tolerious** [comment]
@yin1999 done.

**Comment by yin1999** [comment]
> @yin1999 done.

Please use git rebase to squash the last commit with the second one.

**Comment by tolerious** [comment]
> > @yin1999 done.
> 
> Please use git rebase to squash the last commit with the second one.

Already done , sir.  @irvin @yin1999

**Pull request merged**
