### PR TITLE
fix(jsxref): make $3 a number for all invocations

### PR DESCRIPTION
**Pull request by fiji-flo**
### Description

See https://github.com/mdn/content/pull/33490

Unify the last argument ($3 / do not wrap in code tags) of the jsxref macro. This is a preparation to be more strict regarding arguments. I would have opted for a boolean but it seems like the majority of invocations use 1.

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Leaving a +1, thanks!

**Review by leon-win — APPROVED** [review]

**Comment by leon-win** [comment]
Good for `ru`, thank you @fiji-flo ! :+1:

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja` contents.

**Review by JuanVqz — APPROVED** [review]
Good for ES cc @Graywolf9, Thank you! :shipit:

**Review by yin1999 — APPROVED** [review]
LGTM for the `l10n-zh` content. Thank you @fiji-flo

**Review by SphinxKnight — COMMENTED** [review]
Thanks @fiji-flo, LGTM for `fr`

**Review by SphinxKnight — APPROVED** [review]

**Review by sunhpark42 — APPROVED** [review]
LGTM for `ko` contents. thank you @fiji-flo :)

**Review by josielrocha — APPROVED** [review]
Approve for `pt-BR` 👍🏼

**Comment by yin1999** [comment]
Approved by all localization teams. I'm going to merge this. Thank you @fiji-flo

**Pull request merged**
