### PR TITLE
Remove at-rule @viewport links

### PR DESCRIPTION
**Pull request by mems**
### Description

Remove all links related to the at-rule @viewport.

### Motivation

All this links point to docs/Web/CSS/@viewport page are already redirected to docs/Web/CSS.
Links are already removed in original content.

### Additional details

https://github.com/w3c/csswg-drafts/pull/7670

### Related issues and pull requests

N/A

### CODE REVIEW

**Comment by mems** [comment]
See also https://github.com/mdn/data/pull/677

**Comment by mems** [comment]
There is also the file [files/ru/conflicting/web/css/index.md](https://github.com/mdn/translated-content/blob/7d566028e6e6829dd2e83e50ee057884c85f8df7/files/ru/conflicting/web/css/index.md) which is the content of @viewport at-rule [marked as "conflicted"](https://github.com/mdn/translated-content/blob/7d566028e6e6829dd2e83e50ee057884c85f8df7/files/ru/_wikihistory.json#L16742-L16745).

**Review by sashasushko — APPROVED** [review]
LGTM 🔥 Approve for `ru`. Thanks

**Comment by sashasushko** [comment]
I will figure out with conflicted one, thanks

**Review by SphinxKnight — APPROVED** [review]
Ok for @mdn/yari-content-fr, thanks @mems :)

**Review by mfuji09 — APPROVED** [review]
LGTM for `ja`.

**Review by Graywolf9 — APPROVED** [review]
LGTM for `es` , Thank you!

**Review by josielrocha — APPROVED** [review]
Approve for `pt-BR`

**Comment by SphinxKnight** [comment]
I'm going to go ahead and merge this one. Even if I don't speak Korean, the changes under /ko seems sane and consistent with the other locales.
@mdn/yari-content-ko please let me know if you disagree and would have preferred me to wait a bit longer.

**Pull request merged**
