### PR TITLE
Create README l10n-es

### PR DESCRIPTION
**Pull request by lasr21**
README for l10n-es MDN localization

### CODE REVIEW

**Comment by lasr21** [comment]
@Rumyra we are planning to add a Spanish README but we wonder that if that could broke something or is it ok?

**Comment by Rumyra** [comment]
I think technically there should be an issue - I'll merge this and check again tomorrow :)

**Comment by JuanVqz** [comment]
@Rumyra It seems like nothing was broken. isn't it?

**Comment by Rumyra** [comment]
Yes it seems fine @JuanVqz :D

**Comment by JuanVqz** [comment]
@Rumyra we just discover that the reason why the build hasn't broken was that the file hasn't extension it was just `README` instead of `README.md`.

[this](https://github.com/mdn/translated-content/runs/4953693637?check_suite_focus=true) is the failure when we changed it to `README.md`.

**Pull request merged**
