### PR TITLE
[ru][fr][es][ja][ko][pt][zh]: remove the deprecated manifest HTML attribute

### PR DESCRIPTION
**Pull request by sedlukha**
### Description

- manifest attribute deleting (because was deleted in original EN version of the page  https://github.com/mdn/content/pull/33932 )

- and version attribute deprecation

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for `l10n-zh`. Thank you @sedlukha

**Review by cw118 — APPROVED** [review]
LGTM for fr, thank you for this @sedlukha !

**Review by hochan222 — APPROVED** [review]
LGTM for `ko-locale`. Thank you @sedlukha

**Review by leon-win — APPROVED** [review]

**Comment by leon-win** [comment]
@sedlukha , благодарю за вклад в MDN! =)

**Comment by mfuji09** [comment]
LGTM for `ja` content. Thanks.

**Review by JuanVqz — APPROVED** [review]
Looks good for ES 👍 

cc @Graywolf9

**Review by josielrocha — APPROVED** [review]
It looks good for `pt-BR`

**Pull request merged**
