### PR TITLE
Исправлено двойное отрицание в предложении

### PR DESCRIPTION
**Pull request by Segodnya**
Исправлено двойное отрицание, мешающее восприятию смысла предложения

### CODE REVIEW

**Comment by sashasushko** [comment]
@Segodnya could you please update your fork and resolve conflicts? We're moving from `*.html` to `*.md`

**Comment by Segodnya** [comment]
> @Segodnya could you please update your fork and resolve conflicts? We're moving from `*.html` to `*.md`

Thanks for your review. Could you please explain what I should do? This is my first pull request sent and I dont clear understand how to merge my fork with main to apply the changes.

**Comment by sashasushko** [comment]
> This is my first pull request sent

Cool! Congratulations 🎉 And thank you for your help!

> what I should do?

1. [Sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).
2. Switch to your patch branch.
3. Merge or rebase to `main`.
4. Resolve conflicts (keep `*.md`, delete `*.html` article file). Move your changes to `*.md` file.
5. `git push`

**Comment by Segodnya** [comment]
> > This is my first pull request sent
> 
> Cool! Congratulations 🎉 And thank you for your help!
> 
> > what I should do?
> 
> 1. [Sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).
> 2. Switch to your patch branch.
> 3. Merge or rebase to `main`.
> 4. Resolve conflicts (keep `*.md`, delete `*.html` article file). Move your changes to `*.md` file.
> 5. `git push`

@sashasushko 
Thanks for your advice!
I have synced my fork and switched to patch branch. After that I cloned repo again and have only one branch - main. Do i understand clear - I have to merge main branch of mdn/translated-content with my segodnya//translated-content patch-1 branch? Or I have to merge segodnya//translated-content main with segodnya//translated-content  patch-1 branch?

Both ways I dont have any branches except main after cloning repo. :(

**Comment by Segodnya** [comment]
By the way, I think I have such issues as a result of making PR with Github Web (not through terminal)

**Comment by sashasushko** [comment]
> Both ways I dont have any branches except main after cloning repo. :(

It's not a big problem. We have your changes, here at PR. So give me a little bit more time, I'll figure out how we can fix all

**Pull request closed without merging**
